#!/usr/bin/env bash

export ACR_HOME="{{ACR_HOME}}"

# Add ~/bin to PATH if not already present
if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
    export PATH="$HOME/bin:$PATH"
fi

source "$ACR_HOME/acr_bash_completions"
