FROM registry.access.redhat.com/ubi10/openjdk-21-runtime@sha256:1f10cbee346b2f513085b7a81f7c69091735b98c7e22dd6acae0ebc5e2c713ef

ENV APP_URL="${docker.app.file}" \
    JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ADD "$APP_URL" /deployments

USER root

RUN chmod -R "ug=rwx" /deployments && chown -R 1001:0 /deployments

USER 1001
