FROM registry.access.redhat.com/ubi10/openjdk-21-runtime:latest

ENV APP_URL="${docker.app.file}" \
    JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ADD "$APP_URL" /deployments

USER root

RUN chmod -R "ug=rwx" /deployments && chown -R 1001:0 /deployments

USER 1001

# Quarkus fast-jar: run from quarkus-app directory
WORKDIR /deployments/quarkus-app
CMD ["sh", "-c", "exec java $JAVA_OPTIONS -jar quarkus-run.jar"]
