FROM registry.access.redhat.com/ubi10/openjdk-21-runtime@sha256:a8153015b17c271845f7882dc7f733f1cd5e5f719747707041f01e0e305395ef

ENV APP_URL="quarkus-app" \
    JAVA_OPTIONS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ADD "$APP_URL" /deployments

USER root

# Set appropriate permissions and ownership
RUN chmod -R "ug=rwx" /deployments \
    && chown -R 1001:0 /deployments

# Set user for running the container, according to OpenShift best practices
USER 1001
