FROM fabric8/java-alpine-openjdk8-jre

ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ENV AB_ENABLED=jmx_exporter

COPY target-${app.dir}/lib/* /deployments/lib/

COPY target-${app.dir}/*-runner.jar /deployments/app.jar

ENTRYPOINT [ "/deployments/run-java.sh" ]
