FROM registry.access.redhat.com/ubi8/ubi-minimal

WORKDIR /work/

COPY target-${app.dir}/*-runner /work/application

RUN chmod 775 /work

EXPOSE 8080

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
