// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Which compatibility a difference breaks.
type CompatibilityDifferenceDirection int

const (
	BACKWARD_COMPATIBILITYDIFFERENCEDIRECTION CompatibilityDifferenceDirection = iota
	FORWARD_COMPATIBILITYDIFFERENCEDIRECTION
	BOTH_COMPATIBILITYDIFFERENCEDIRECTION
)

func (i CompatibilityDifferenceDirection) String() string {
	return []string{"BACKWARD", "FORWARD", "BOTH"}[i]
}

func ParseCompatibilityDifferenceDirection(v string) (any, error) {
	result := BACKWARD_COMPATIBILITYDIFFERENCEDIRECTION
	switch v {
	case "BACKWARD":
		result = BACKWARD_COMPATIBILITYDIFFERENCEDIRECTION
	case "FORWARD":
		result = FORWARD_COMPATIBILITYDIFFERENCEDIRECTION
	case "BOTH":
		result = BOTH_COMPATIBILITYDIFFERENCEDIRECTION
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeCompatibilityDifferenceDirection(values []CompatibilityDifferenceDirection) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i CompatibilityDifferenceDirection) isMultiValue() bool {
	return false
}
