// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DifferenceLocation a location within one of the two documents compared by a rule. Locations are labelled by document - proposed or existing - rather than by the checker's original and updated schemas, so that the direction of the check does not change their meaning. Clients must tolerate a pointer that does not resolve in the content as written, falling back to the deepest part that does.
type DifferenceLocation struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// A JSON Pointer, in that document's own keywords. When the two documents use different drafts, each pointer uses its own document's spelling.
	pointer *string
	// When set, the location is in a referenced artifact, named as in the version's artifact references, and `pointer` points into that artifact. Absent means the location is in the document itself.
	reference *string
	// The existing version the difference was found against, when known - always the latest version for the non-transitive compatibility levels. Not set on a proposed location.
	version *string
}

// NewDifferenceLocation instantiates a new DifferenceLocation and sets the default values.
func NewDifferenceLocation() *DifferenceLocation {
	m := &DifferenceLocation{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateDifferenceLocationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDifferenceLocationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDifferenceLocation(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DifferenceLocation) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *DifferenceLocation) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["pointer"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPointer(val)
		}
		return nil
	}
	res["reference"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetReference(val)
		}
		return nil
	}
	res["version"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVersion(val)
		}
		return nil
	}
	return res
}

// GetPointer gets the pointer property value. A JSON Pointer, in that document's own keywords. When the two documents use different drafts, each pointer uses its own document's spelling.
// returns a *string when successful
func (m *DifferenceLocation) GetPointer() *string {
	return m.pointer
}

// GetReference gets the reference property value. When set, the location is in a referenced artifact, named as in the version's artifact references, and `pointer` points into that artifact. Absent means the location is in the document itself.
// returns a *string when successful
func (m *DifferenceLocation) GetReference() *string {
	return m.reference
}

// GetVersion gets the version property value. The existing version the difference was found against, when known - always the latest version for the non-transitive compatibility levels. Not set on a proposed location.
// returns a *string when successful
func (m *DifferenceLocation) GetVersion() *string {
	return m.version
}

// Serialize serializes information the current object
func (m *DifferenceLocation) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("pointer", m.GetPointer())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("reference", m.GetReference())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("version", m.GetVersion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DifferenceLocation) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetPointer sets the pointer property value. A JSON Pointer, in that document's own keywords. When the two documents use different drafts, each pointer uses its own document's spelling.
func (m *DifferenceLocation) SetPointer(value *string) {
	m.pointer = value
}

// SetReference sets the reference property value. When set, the location is in a referenced artifact, named as in the version's artifact references, and `pointer` points into that artifact. Absent means the location is in the document itself.
func (m *DifferenceLocation) SetReference(value *string) {
	m.reference = value
}

// SetVersion sets the version property value. The existing version the difference was found against, when known - always the latest version for the non-transitive compatibility levels. Not set on a proposed location.
func (m *DifferenceLocation) SetVersion(value *string) {
	m.version = value
}

type DifferenceLocationable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetPointer() *string
	GetReference() *string
	GetVersion() *string
	SetPointer(value *string)
	SetReference(value *string)
	SetVersion(value *string)
}
