// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Why a source could not be searched. Set only when the outcome is `failed`.* `unauthorized` - the peer answered 401 or 403.* `unreachable` - the peer could not be reached, or its address is not allowed.* `timeout` - the peer did not answer within the per-peer timeout.* `peer_error` - the peer answered with a server error, or with a redirect.* `invalid_response` - the peer's answer was malformed, too large or inconsistent.* `circuit_open` - the peer is failing repeatedly and was not called.* `capacity_exceeded` - this registry had no capacity left to call the peer.
type FederatedSearchFailureReason int

const (
	UNAUTHORIZED_FEDERATEDSEARCHFAILUREREASON FederatedSearchFailureReason = iota
	UNREACHABLE_FEDERATEDSEARCHFAILUREREASON
	TIMEOUT_FEDERATEDSEARCHFAILUREREASON
	PEER_ERROR_FEDERATEDSEARCHFAILUREREASON
	INVALID_RESPONSE_FEDERATEDSEARCHFAILUREREASON
	CIRCUIT_OPEN_FEDERATEDSEARCHFAILUREREASON
	CAPACITY_EXCEEDED_FEDERATEDSEARCHFAILUREREASON
)

func (i FederatedSearchFailureReason) String() string {
	return []string{"unauthorized", "unreachable", "timeout", "peer_error", "invalid_response", "circuit_open", "capacity_exceeded"}[i]
}

func ParseFederatedSearchFailureReason(v string) (any, error) {
	result := UNAUTHORIZED_FEDERATEDSEARCHFAILUREREASON
	switch v {
	case "unauthorized":
		result = UNAUTHORIZED_FEDERATEDSEARCHFAILUREREASON
	case "unreachable":
		result = UNREACHABLE_FEDERATEDSEARCHFAILUREREASON
	case "timeout":
		result = TIMEOUT_FEDERATEDSEARCHFAILUREREASON
	case "peer_error":
		result = PEER_ERROR_FEDERATEDSEARCHFAILUREREASON
	case "invalid_response":
		result = INVALID_RESPONSE_FEDERATEDSEARCHFAILUREREASON
	case "circuit_open":
		result = CIRCUIT_OPEN_FEDERATEDSEARCHFAILUREREASON
	case "capacity_exceeded":
		result = CAPACITY_EXCEEDED_FEDERATEDSEARCHFAILUREREASON
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeFederatedSearchFailureReason(values []FederatedSearchFailureReason) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i FederatedSearchFailureReason) isMultiValue() bool {
	return false
}
