// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// NewPeerEscaped the information needed to register a new peer registry.
type NewPeerEscaped struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Name of the key in the registry's peer credentials directory that holds the credential for this peer. A reference only: the credential value is never stored or returned.
	credentialSecretRef *string
	// Description of the peer registry.
	description *string
	// Whether the peer registry is used for federation. Defaults to `true`.
	enabled *bool
	// Display name of the peer registry.
	name *string
	// Unique id of the peer registry. Lowercase letters, digits, `.`, `_` and `-` only, at most 256 characters. `local` is reserved.
	peerId *string
	// Base URL of the peer registry, for example `https://registry.eu.example.com`.
	url *string
}

// NewNewPeerEscaped instantiates a new NewPeerEscaped and sets the default values.
func NewNewPeerEscaped() *NewPeerEscaped {
	m := &NewPeerEscaped{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateNewPeerEscapedFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNewPeerEscapedFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewNewPeerEscaped(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *NewPeerEscaped) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCredentialSecretRef gets the credentialSecretRef property value. Name of the key in the registry's peer credentials directory that holds the credential for this peer. A reference only: the credential value is never stored or returned.
// returns a *string when successful
func (m *NewPeerEscaped) GetCredentialSecretRef() *string {
	return m.credentialSecretRef
}

// GetDescription gets the description property value. Description of the peer registry.
// returns a *string when successful
func (m *NewPeerEscaped) GetDescription() *string {
	return m.description
}

// GetEnabled gets the enabled property value. Whether the peer registry is used for federation. Defaults to `true`.
// returns a *bool when successful
func (m *NewPeerEscaped) GetEnabled() *bool {
	return m.enabled
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error when successful
func (m *NewPeerEscaped) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["credentialSecretRef"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCredentialSecretRef(val)
		}
		return nil
	}
	res["description"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDescription(val)
		}
		return nil
	}
	res["enabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEnabled(val)
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["peerId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPeerId(val)
		}
		return nil
	}
	res["url"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUrl(val)
		}
		return nil
	}
	return res
}

// GetName gets the name property value. Display name of the peer registry.
// returns a *string when successful
func (m *NewPeerEscaped) GetName() *string {
	return m.name
}

// GetPeerId gets the peerId property value. Unique id of the peer registry. Lowercase letters, digits, `.`, `_` and `-` only, at most 256 characters. `local` is reserved.
// returns a *string when successful
func (m *NewPeerEscaped) GetPeerId() *string {
	return m.peerId
}

// GetUrl gets the url property value. Base URL of the peer registry, for example `https://registry.eu.example.com`.
// returns a *string when successful
func (m *NewPeerEscaped) GetUrl() *string {
	return m.url
}

// Serialize serializes information the current object
func (m *NewPeerEscaped) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("credentialSecretRef", m.GetCredentialSecretRef())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("description", m.GetDescription())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("enabled", m.GetEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("name", m.GetName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("peerId", m.GetPeerId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("url", m.GetUrl())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *NewPeerEscaped) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCredentialSecretRef sets the credentialSecretRef property value. Name of the key in the registry's peer credentials directory that holds the credential for this peer. A reference only: the credential value is never stored or returned.
func (m *NewPeerEscaped) SetCredentialSecretRef(value *string) {
	m.credentialSecretRef = value
}

// SetDescription sets the description property value. Description of the peer registry.
func (m *NewPeerEscaped) SetDescription(value *string) {
	m.description = value
}

// SetEnabled sets the enabled property value. Whether the peer registry is used for federation. Defaults to `true`.
func (m *NewPeerEscaped) SetEnabled(value *bool) {
	m.enabled = value
}

// SetName sets the name property value. Display name of the peer registry.
func (m *NewPeerEscaped) SetName(value *string) {
	m.name = value
}

// SetPeerId sets the peerId property value. Unique id of the peer registry. Lowercase letters, digits, `.`, `_` and `-` only, at most 256 characters. `local` is reserved.
func (m *NewPeerEscaped) SetPeerId(value *string) {
	m.peerId = value
}

// SetUrl sets the url property value. Base URL of the peer registry, for example `https://registry.eu.example.com`.
func (m *NewPeerEscaped) SetUrl(value *string) {
	m.url = value
}

type NewPeerEscapedable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCredentialSecretRef() *string
	GetDescription() *string
	GetEnabled() *bool
	GetName() *string
	GetPeerId() *string
	GetUrl() *string
	SetCredentialSecretRef(value *string)
	SetDescription(value *string)
	SetEnabled(value *bool)
	SetName(value *string)
	SetPeerId(value *string)
	SetUrl(value *string)
}
