// Tests for issue-assignment.js — run with: node --test .github/scripts/issue-assignment.test.js
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const os = require('os');

const assignment = require('./issue-assignment.js');

// The handler reads the maintainers list from `${cwd}/.github/pr-lifecycle.json`
// (generated by yq in the workflow). These tests run from a throwaway cwd rather
// than the repository root: pr-lifecycle.test.js manages the real file the same
// way, and `node --test` runs the two files concurrently, so writing to the shared
// path would make each suite delete the other's config mid-run.
let sandbox;
let originalCwd;
const configPath = () => path.join(sandbox, '.github', 'pr-lifecycle.json');

before(() => {
  originalCwd = process.cwd();
  sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'issue-assignment-test-'));
  fs.mkdirSync(path.join(sandbox, '.github'));
  fs.writeFileSync(configPath(), JSON.stringify({ maintainers: [] }));
  process.chdir(sandbox);
});
after(() => {
  process.chdir(originalCwd);
  fs.rmSync(sandbox, { recursive: true, force: true });
});

// Swaps the sandbox config for the duration of fn, then restores it.
async function withConfig(cfg, fn) {
  const backup = fs.readFileSync(configPath(), 'utf8');
  fs.writeFileSync(configPath(), JSON.stringify(cfg));
  try {
    await fn();
  } finally {
    fs.writeFileSync(configPath(), backup);
  }
}

// Runs fn with the config absent, to cover the unreadable-config path.
async function withoutConfig(fn) {
  const backup = fs.readFileSync(configPath(), 'utf8');
  fs.rmSync(configPath(), { force: true });
  try {
    await fn();
  } finally {
    fs.writeFileSync(configPath(), backup);
  }
}

// ---------------------------------------------------------------------------
// Stateful mock GitHub API
// ---------------------------------------------------------------------------

const ISSUE_NUMBER = 77;

function makeWorld({
  labels = [],
  assignees = [],
  author = 'issue-author',
  state = 'open',
  openIssuesForUser = 0,
} = {}) {
  const current = [...assignees];
  const calls = { comments: [], assigned: [], unassigned: [], warnings: [] };

  const issue = () => ({
    number: ISSUE_NUMBER,
    state,
    user: { login: author },
    labels: labels.map(name => ({ name })),
    assignees: current.map(login => ({ login })),
  });

  const github = {
    rest: {
      issues: {
        get: async () => ({ data: issue() }),
        addAssignees: async ({ assignees: as }) => {
          as.forEach(a => { current.push(a); calls.assigned.push(a); });
          return { data: issue() };
        },
        removeAssignees: async ({ assignees: as }) => {
          as.forEach(a => {
            const i = current.findIndex(c => c.toLowerCase() === a.toLowerCase());
            if (i >= 0) current.splice(i, 1);
            calls.unassigned.push(a);
          });
          return { data: issue() };
        },
        createComment: async ({ body }) => calls.comments.push(body),
        listForRepo: 'listForRepo',
      },
    },
    paginate: async () => Array.from(
      { length: openIssuesForUser },
      (_, i) => ({ number: 1000 + i })
    ),
  };

  const core = {
    info: () => {},
    warning: msg => calls.warnings.push(msg),
    error: () => {},
  };

  return { github, core, calls, currentAssignees: () => current };
}

function commentContext(body, commenter, worldIssue) {
  return {
    repo: { owner: 'Apicurio', repo: 'apicurio-registry' },
    payload: {
      issue: worldIssue,
      comment: { body, user: { login: commenter, type: 'User' } },
    },
  };
}

// Convenience: run the handler against a world, with a payload issue that matches it.
async function run(world, body, commenter, payloadIssue = {}) {
  const issue = {
    number: ISSUE_NUMBER,
    state: 'open',
    user: { login: 'issue-author' },
    labels: [],
    assignees: [],
    ...payloadIssue,
  };
  await assignment.handleIssueComment({
    github: world.github,
    context: commentContext(body, commenter, issue),
    core: world.core,
  });
}

// ---------------------------------------------------------------------------
// Maintainer-only labels (area/CI)
// ---------------------------------------------------------------------------

test('area/CI: self-assignment by a contributor is refused', async () => {
  await withConfig({ maintainers: ['maintainer-jane'] }, async () => {
    const w = makeWorld({ labels: ['area/CI'] });
    await run(w, '/assign-me', 'contributor');

    assert.deepEqual(w.calls.assigned, []);
    assert.deepEqual(w.currentAssignees(), []);
    assert.equal(w.calls.comments.length, 1);
    assert.match(w.calls.comments[0], /@contributor/);
    assert.match(w.calls.comments[0], /`area\/CI`/);
    assert.match(w.calls.comments[0], /not available for self-assignment/);
  });
});

test('area/CI: a maintainer who reported the issue is pinged by name, not the team', async () => {
  await withConfig({ maintainers: ['maintainer-jane'] }, async () => {
    const w = makeWorld({ labels: ['area/CI'], author: 'Maintainer-Jane' });
    await run(w, '/claim', 'contributor');

    assert.deepEqual(w.calls.assigned, []);
    assert.equal(w.calls.comments.length, 1);
    assert.match(w.calls.comments[0], /ping @Maintainer-Jane\./);
    assert.doesNotMatch(w.calls.comments[0], /@Apicurio\/maintainers/);
  });
});

test('area/CI: a non-maintainer reporter falls back to the team ping', async () => {
  await withConfig({ maintainers: ['maintainer-jane'] }, async () => {
    const w = makeWorld({ labels: ['area/CI'], author: 'reporter-bob' });
    await run(w, '/assign-me', 'contributor');

    assert.equal(w.calls.comments.length, 1);
    assert.match(w.calls.comments[0], /ping @Apicurio\/maintainers\./);
    assert.doesNotMatch(w.calls.comments[0], /@reporter-bob/);
  });
});

test('area/CI: who is assigned does not change who gets pinged', async () => {
  await withConfig({ maintainers: ['maintainer-jane'] }, async () => {
    const w = makeWorld({ labels: ['area/CI'], author: 'reporter-bob', assignees: ['Maintainer-Jane'] });
    await run(w, '/assign-me', 'contributor');

    assert.deepEqual(w.calls.assigned, []);
    assert.equal(w.calls.comments.length, 1);
    assert.match(w.calls.comments[0], /ping @Apicurio\/maintainers\./);
  });
});

test('area/CI: the refusal names the label rather than a hardcoded area', async () => {
  await withConfig({ maintainers: [] }, async () => {
    const w = makeWorld({ labels: ['area/CI'] });
    await run(w, '/assign-me', 'contributor');

    assert.match(w.calls.comments[0], /labelled `area\/CI`, which marks work that is handled by the maintainers/);
    assert.doesNotMatch(w.calls.comments[0], /CI\/CD/);
  });
});

test('area/CI: label matching is case-insensitive', async () => {
  await withConfig({ maintainers: [] }, async () => {
    const w = makeWorld({ labels: ['area/ci'] });
    await run(w, '/assign-me', 'contributor');

    assert.deepEqual(w.calls.assigned, []);
    // The label is echoed back with the casing the repository actually uses.
    assert.match(w.calls.comments[0], /`area\/ci`/);
  });
});

test('area/CI: maintainers are exempt and get assigned', async () => {
  await withConfig({ maintainers: ['maintainer-jane'] }, async () => {
    const w = makeWorld({ labels: ['area/CI'] });
    await run(w, '/assign-me', 'Maintainer-Jane');

    assert.deepEqual(w.calls.assigned, ['Maintainer-Jane']);
    assert.match(w.calls.comments[0], /assigned to you/);
  });
});

test('area/CI: the refusal takes precedence over the open-issue limit message', async () => {
  await withConfig({ maintainers: [] }, async () => {
    const w = makeWorld({ labels: ['area/CI'], openIssuesForUser: 5 });
    await run(w, '/assign-me', 'contributor');

    assert.equal(w.calls.comments.length, 1);
    assert.match(w.calls.comments[0], /not available for self-assignment/);
    assert.doesNotMatch(w.calls.comments[0], /limited to/);
  });
});

test('area/CI: unassigning is still allowed', async () => {
  await withConfig({ maintainers: [] }, async () => {
    const w = makeWorld({ labels: ['area/CI'], assignees: ['contributor'] });
    await run(w, '/unassign-me', 'contributor');

    assert.deepEqual(w.calls.unassigned, ['contributor']);
    assert.match(w.calls.comments[0], /You have been unassigned/);
  });
});

test('a missing config file refuses instead of throwing, and warns', async () => {
  await withoutConfig(async () => {
    const w = makeWorld({ labels: ['area/CI'] });
    await run(w, '/assign-me', 'maintainer-jane');

    assert.deepEqual(w.calls.assigned, []);
    assert.equal(w.calls.warnings.length, 1);
    assert.match(w.calls.warnings[0], /Could not read maintainers/);
  });
});

// ---------------------------------------------------------------------------
// Unrestricted issues keep the existing behaviour
// ---------------------------------------------------------------------------

test('an unlabelled issue is assigned to the contributor', async () => {
  await withConfig({ maintainers: [] }, async () => {
    const w = makeWorld({ labels: ['area/storage', 'bug'] });
    await run(w, '/assign-me', 'contributor');

    assert.deepEqual(w.calls.assigned, ['contributor']);
    assert.match(w.calls.comments[0], /Thanks for volunteering/);
  });
});

test('the open-issue limit still applies on unrestricted issues', async () => {
  await withConfig({ maintainers: [] }, async () => {
    const w = makeWorld({ labels: ['area/storage'], openIssuesForUser: assignment.MAX_ASSIGNED_ISSUES });
    await run(w, '/assign-me', 'contributor');

    assert.deepEqual(w.calls.assigned, []);
    assert.match(w.calls.comments[0], new RegExp(`limited to ${assignment.MAX_ASSIGNED_ISSUES} open issues`));
  });
});

test('an issue already claimed by someone else is reported as claimed', async () => {
  await withConfig({ maintainers: [] }, async () => {
    const w = makeWorld({ labels: [], assignees: ['someone-else'] });
    await run(w, '/assign-me', 'contributor');

    assert.deepEqual(w.calls.assigned, []);
    assert.match(w.calls.comments[0], /already claimed by @someone-else/);
  });
});

test('comments that are not assignment commands are ignored', async () => {
  await withConfig({ maintainers: [] }, async () => {
    const w = makeWorld({ labels: ['area/CI'] });
    await run(w, '/retry', 'contributor');

    assert.deepEqual(w.calls.comments, []);
    assert.deepEqual(w.calls.assigned, []);
  });
});
