// Tests for pr-lifecycle.js two-tier CI routing — run with: node --test .github/scripts/
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const lifecycle = require('./pr-lifecycle.js');
const { LABELS, FULL_SUITE_WORKFLOWS } = lifecycle;

// loadConfig() reads .github/pr-lifecycle.json (generated by yq in the
// workflow). Provide a minimal one for the duration of the tests.
const CONFIG_PATH = path.join(process.cwd(), '.github', 'pr-lifecycle.json');
let hadConfig = false;
before(() => {
  hadConfig = fs.existsSync(CONFIG_PATH);
  if (!hadConfig) {
    fs.writeFileSync(CONFIG_PATH, JSON.stringify({
      maintainers: [], merge: { strategy: 'rebase' },
      welcome_message: 'Thanks for opening this PR, {author}!',
    }));
  }
});
after(() => {
  if (!hadConfig) fs.rmSync(CONFIG_PATH, { force: true });
});

// Temporarily swaps .github/pr-lifecycle.json for the duration of fn (e.g. to set
// a maintainers list), then restores whatever was there before — regardless of
// hadConfig, so it composes safely with the suite-level before()/after() above.
async function withConfig(cfg, fn) {
  const backup = fs.readFileSync(CONFIG_PATH, 'utf8');
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(cfg));
  try {
    await fn();
  } finally {
    fs.writeFileSync(CONFIG_PATH, backup);
  }
}

// ---------------------------------------------------------------------------
// Stateful mock GitHub API
// ---------------------------------------------------------------------------

const SHA = 'abcdef1234567890';

function makeWorld(prLabels, { approved = false, suiteRuns = [] } = {}) {
  const labels = new Set(prLabels);
  const calls = { added: [], removed: [], comments: [], merges: [], branchUpdates: [] };

  const pr = () => ({
    number: 42,
    title: 'test',
    draft: false,
    labels: [...labels].map(name => ({ name })),
    user: { login: 'contributor' },
    head: { sha: SHA, ref: 'feature-x' },
    base: { ref: 'main' },
    requested_reviewers: [],
  });

  const github = {
    rest: {
      issues: {
        addLabels: async ({ labels: ls }) => ls.forEach(l => { labels.add(l); calls.added.push(l); }),
        removeLabel: async ({ name }) => { labels.delete(name); calls.removed.push(name); },
        createComment: async ({ body }) => calls.comments.push(body),
        getLabel: async () => { const e = new Error('nf'); e.status = 404; throw e; },
        createLabel: async () => ({}),
        updateLabel: async () => ({}),
      },
      pulls: {
        get: async () => ({ data: pr() }),
        list: async () => ({ data: [] }),
        listReviews: async () => ({}),
        merge: async () => { calls.merges.push('merge'); },
        updateBranch: async () => { calls.branchUpdates.push('update'); },
      },
      actions: {
        listWorkflowRuns: async () => ({ data: { workflow_runs: [] } }),
        listWorkflowRunsForRepo: async () => ({ data: { workflow_runs: suiteRuns } }),
        listWorkflowRunArtifacts: async () => ({}),
      },
    },
    // paginate: reviews list when asked for reviews, empty otherwise
    paginate: async (fn) => fn === github.rest.pulls.listReviews
      ? (approved ? [{ state: 'APPROVED', user: { login: 'maintainer-jane' } }] : [])
      : [],
  };

  const core = { info: () => {}, warning: () => {}, error: () => {} };
  return { github, core, calls, labels };
}

function runPayload(workflowName, conclusion) {
  return {
    repo: { owner: 'Apicurio', repo: 'apicurio-registry' },
    payload: {
      workflow_run: {
        name: workflowName,
        event: 'pull_request',
        conclusion,
        head_sha: SHA,
        head_branch: 'feature-x',
        head_repository: { owner: { login: 'Apicurio' } },
        pull_requests: [{ number: 42 }],
        html_url: 'https://example.com/run/1',
      },
    },
  };
}

// Latest-run state for all full-suite workflows, green except where overridden
// (e.g. greenSuite({ Verify: 'failure' })). Pass status via the special
// '<status>/' prefix (e.g. { 'Integration Tests': 'in_progress/' }).
function greenSuite(overrides = {}) {
  return FULL_SUITE_WORKFLOWS.map(name => {
    const o = overrides[name] || 'success';
    const inProgress = o.endsWith('/');
    const conclusion = inProgress ? null : o;
    return {
      name,
      status: inProgress ? o.slice(0, -1) : 'completed',
      conclusion,
      created_at: '2026-01-01T00:00:00Z',
      html_url: 'https://example.com/run/' + name.replace(/\s/g, '-'),
    };
  });
}

// ---------------------------------------------------------------------------
// PR Opened — maintainer auto-accept vs. contributor review gate
// ---------------------------------------------------------------------------

function openedPr(login) {
  return {
    number: 42,
    title: 'test',
    draft: false,
    labels: [],
    user: { login },
    head: { sha: SHA, ref: 'feature-x' },
    requested_reviewers: [],
  };
}

function openedContext(pr) {
  return {
    repo: { owner: 'Apicurio', repo: 'apicurio-registry' },
    payload: { pull_request: pr },
  };
}

test('maintainer PR open: auto-accepted straight to ready-for-review + review-skipped, fast gate only (not ready-to-merge yet)', async () => {
  await withConfig({ maintainers: ['maintainer-jane'], merge: { strategy: 'rebase' } }, async () => {
    const w = makeWorld([]);
    // retriggerVerify(waitForRun: true) polls for the ci.yaml run it just triggered;
    // already-green means retriggerWorkflowRun leaves it alone instead of re-running it.
    w.github.rest.actions.listWorkflowRuns = async () => ({
      data: { workflow_runs: [{ id: 1, status: 'completed', conclusion: 'success', head_sha: SHA }] },
    });
    await lifecycle.handlePrOpened({ github: w.github, context: openedContext(openedPr('maintainer-jane')), core: w.core });

    assert.ok(w.calls.added.includes(LABELS.READY_FOR_REVIEW));
    assert.ok(w.calls.added.includes(LABELS.REVIEW_SKIPPED));
    assert.ok(w.calls.added.includes(LABELS.WAITING_ON_MAINTAINER));
    assert.ok(!w.calls.added.includes(LABELS.READY_TO_MERGE),
      'must not skip straight to ready-to-merge — the fast gate still has to pass first');
    assert.ok(w.calls.comments.some(c => c.includes('auto-accepted')));
  });
});

test('non-maintainer PR open: lifecycle/new, waiting on a maintainer to /accept', async () => {
  const w = makeWorld([]);
  await lifecycle.handlePrOpened({ github: w.github, context: openedContext(openedPr('some-contributor')), core: w.core });

  assert.ok(w.calls.added.includes(LABELS.NEW));
  assert.ok(w.calls.added.includes(LABELS.WAITING_ON_MAINTAINER));
  assert.ok(!w.calls.added.includes(LABELS.READY_FOR_REVIEW));
  assert.ok(!w.calls.added.includes(LABELS.REVIEW_SKIPPED));
});

test('fast gate pass + review-skipped (maintainer) promotes straight to ready-to-merge, no review required', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW, LABELS.REVIEW_SKIPPED, LABELS.WAITING_ON_MAINTAINER]);
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Quick Check', 'success'), core: w.core });

  assert.ok(w.calls.added.includes(LABELS.TESTED));
  assert.ok(w.calls.added.includes(LABELS.READY_TO_MERGE),
    'review-skipped + tested must promote without waiting for a review');
  assert.ok(w.calls.comments.some(c => c.includes('full verification suite is now')));
});

test('fast gate pass without review or skip-review stays in ready-for-review (waiting on maintainer)', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW]);
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Quick Check', 'success'), core: w.core });

  assert.ok(w.calls.added.includes(LABELS.TESTED));
  assert.ok(!w.calls.added.includes(LABELS.READY_TO_MERGE),
    'an unreviewed, non-skipped PR must wait for an approval before the full suite runs');
  assert.ok(w.calls.added.includes(LABELS.WAITING_ON_MAINTAINER));
});

test('fast gate pass with an approved review promotes a contributor PR to ready-to-merge', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW], { approved: true });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Quick Check', 'success'), core: w.core });

  assert.ok(w.calls.added.includes(LABELS.TESTED));
  assert.ok(w.calls.added.includes(LABELS.READY_TO_MERGE),
    'an approved review + green fast gate must promote to ready-to-merge');
});

// ---------------------------------------------------------------------------
// Fast gate (Quick Check workflow) — drives lifecycle/tested during review
// ---------------------------------------------------------------------------

test('Quick Check success in ready-for-review adds lifecycle/tested', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW]);
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Quick Check', 'success'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.TESTED));
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
});

test('Quick Check failure in ready-for-review sets waiting-on-author', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW, LABELS.WAITING_ON_MAINTAINER]);
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Quick Check', 'failure'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.WAITING_ON_AUTHOR));
  assert.ok(w.calls.removed.includes(LABELS.WAITING_ON_MAINTAINER));
  assert.ok(!w.calls.added.includes(LABELS.TESTED));
  assert.ok(w.calls.comments.some(c => c.includes('Quick Check gate failed')));
});

test('CI result is ignored at ready-to-merge (full suite owns the result)', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED], { approved: true });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('CI', 'success'), core: w.core });
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
  assert.equal(w.calls.merges.length, 0);
});

// ---------------------------------------------------------------------------
// Full suite (Verify workflow) — the pre-merge gate
// ---------------------------------------------------------------------------

test('Verify success in ready-for-review is a no-op (must not mark tested)', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW]);
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'success'), core: w.core });
  assert.ok(!w.calls.added.includes(LABELS.TESTED));
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
});

test('Verify success at ready-to-merge adds lifecycle/full-verified when the whole suite is green', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED], { approved: true, suiteRuns: greenSuite() });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'success'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.FULL_VERIFIED));
  assert.equal(w.calls.merges.length, 0);
});

test('Verify success at ready-to-merge completes a queued (pending) merge', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED, LABELS.PENDING_MERGE], { approved: true, suiteRuns: greenSuite() });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'success'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.FULL_VERIFIED));
  assert.ok(w.calls.removed.includes(LABELS.PENDING_MERGE));
  assert.equal(w.calls.merges.length, 1);
});

test('full suite stays pending while a sibling workflow is still running', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED], { approved: true, suiteRuns: greenSuite({ 'Integration Tests': 'in_progress/' }) });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'success'), core: w.core });
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
  assert.equal(w.calls.merges.length, 0);
  assert.equal(w.calls.comments.length, 0);
});

test('a failure in any full-suite workflow reverts to ready-for-review', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED, LABELS.FULL_VERIFIED, LABELS.PENDING_MERGE], { approved: true, suiteRuns: greenSuite({ 'Extra Tests': 'failure' }) });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'success'), core: w.core });
  assert.ok(w.calls.removed.includes(LABELS.FULL_VERIFIED));
  assert.ok(w.calls.removed.includes(LABELS.TESTED));
  assert.ok(w.calls.added.includes(LABELS.READY_FOR_REVIEW));
  assert.ok(w.calls.added.includes(LABELS.WAITING_ON_AUTHOR));
  assert.ok(w.calls.comments.some(c => c.includes('Extra Tests')));
  assert.equal(w.calls.merges.length, 0);
});

test('CI success at ready-to-merge counts towards the full suite', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED], { approved: true, suiteRuns: greenSuite() });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('CI', 'success'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.FULL_VERIFIED));
});

test('late Quick Check success does not promote the PR after a full-suite failure', async () => {
  // State after the failure revert: ready-for-review, no tested label. A late
  // Quick Check completion (full-tier run) must not re-add lifecycle/tested.
  const w = makeWorld([LABELS.READY_FOR_REVIEW, LABELS.WAITING_ON_AUTHOR], { suiteRuns: greenSuite({ 'Integration Tests': 'failure' }) });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Quick Check', 'success'), core: w.core });
  assert.ok(!w.calls.added.includes(LABELS.TESTED));
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
});

test('Verify failure at ready-to-merge reverts to ready-for-review', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED, LABELS.FULL_VERIFIED, LABELS.PENDING_MERGE], { approved: true, suiteRuns: greenSuite({ Verify: 'failure' }) });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'failure'), core: w.core });
  assert.ok(w.calls.removed.includes(LABELS.FULL_VERIFIED));
  assert.ok(w.calls.removed.includes(LABELS.TESTED));
  assert.ok(w.calls.removed.includes(LABELS.PENDING_MERGE));
  assert.ok(w.calls.added.includes(LABELS.READY_FOR_REVIEW));
  assert.ok(w.calls.added.includes(LABELS.WAITING_ON_AUTHOR));
  assert.equal(w.calls.merges.length, 0);
});

test('Verify result with stale SHA is ignored', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED], { approved: true });
  const ctx = runPayload('Verify', 'success');
  ctx.payload.workflow_run.head_sha = '0000000000different';
  await lifecycle.handleTestResult({ github: w.github, context: ctx, core: w.core });
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
});
