// Tests for pr-lifecycle.js two-tier CI routing — run with: node --test .github/scripts/
const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const lifecycle = require('./pr-lifecycle.js');
const { LABELS } = lifecycle;

// loadConfig() reads .github/pr-lifecycle.json (generated by yq in the
// workflow). Provide a minimal one for the duration of the tests.
const CONFIG_PATH = path.join(process.cwd(), '.github', 'pr-lifecycle.json');
let hadConfig = false;
before(() => {
  hadConfig = fs.existsSync(CONFIG_PATH);
  if (!hadConfig) {
    fs.writeFileSync(CONFIG_PATH, JSON.stringify({ maintainers: [], merge: { strategy: 'rebase' } }));
  }
});
after(() => {
  if (!hadConfig) fs.rmSync(CONFIG_PATH, { force: true });
});

// ---------------------------------------------------------------------------
// Stateful mock GitHub API
// ---------------------------------------------------------------------------

const SHA = 'abcdef1234567890';

function makeWorld(prLabels, { approved = false } = {}) {
  const labels = new Set(prLabels);
  const calls = { added: [], removed: [], comments: [], merges: [], branchUpdates: [] };

  const pr = () => ({
    number: 42,
    title: 'test',
    draft: false,
    labels: [...labels].map(name => ({ name })),
    user: { login: 'contributor' },
    head: { sha: SHA, ref: 'feature-x' },
    requested_reviewers: [],
  });

  const github = {
    rest: {
      issues: {
        addLabels: async ({ labels: ls }) => ls.forEach(l => { labels.add(l); calls.added.push(l); }),
        removeLabel: async ({ name }) => { labels.delete(name); calls.removed.push(name); },
        createComment: async ({ body }) => calls.comments.push(body),
        getLabel: async () => { const e = new Error('nf'); e.status = 404; throw e; },
        createLabel: async () => ({}),
        updateLabel: async () => ({}),
      },
      pulls: {
        get: async () => ({ data: pr() }),
        list: async () => ({ data: [] }),
        listReviews: async () => ({}),
        merge: async () => { calls.merges.push('merge'); },
        updateBranch: async () => { calls.branchUpdates.push('update'); },
      },
      actions: {
        listWorkflowRuns: async () => ({ data: { workflow_runs: [] } }),
        listWorkflowRunArtifacts: async () => ({}),
      },
    },
    // paginate: reviews list when asked for reviews, empty otherwise
    paginate: async (fn) => fn === github.rest.pulls.listReviews
      ? (approved ? [{ state: 'APPROVED', user: { login: 'maintainer-jane' } }] : [])
      : [],
  };

  const core = { info: () => {}, warning: () => {}, error: () => {} };
  return { github, core, calls, labels };
}

function runPayload(workflowName, conclusion) {
  return {
    repo: { owner: 'Apicurio', repo: 'apicurio-registry' },
    payload: {
      workflow_run: {
        name: workflowName,
        event: 'pull_request',
        conclusion,
        head_sha: SHA,
        head_branch: 'feature-x',
        head_repository: { owner: { login: 'Apicurio' } },
        pull_requests: [{ number: 42 }],
        html_url: 'https://example.com/run/1',
      },
    },
  };
}

// ---------------------------------------------------------------------------
// Fast gate (CI workflow) — drives lifecycle/tested during review
// ---------------------------------------------------------------------------

test('CI success in ready-for-review adds lifecycle/tested', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW]);
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('CI', 'success'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.TESTED));
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
});

test('CI failure in ready-for-review sets waiting-on-author', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW, LABELS.WAITING_ON_MAINTAINER]);
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('CI', 'failure'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.WAITING_ON_AUTHOR));
  assert.ok(w.calls.removed.includes(LABELS.WAITING_ON_MAINTAINER));
  assert.ok(!w.calls.added.includes(LABELS.TESTED));
  assert.ok(w.calls.comments.some(c => c.includes('fast CI gate failed')));
});

test('CI result is ignored at ready-to-merge (full suite owns the result)', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED], { approved: true });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('CI', 'success'), core: w.core });
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
  assert.equal(w.calls.merges.length, 0);
});

// ---------------------------------------------------------------------------
// Full suite (Verify workflow) — the pre-merge gate
// ---------------------------------------------------------------------------

test('Verify success in ready-for-review is a no-op (must not mark tested)', async () => {
  const w = makeWorld([LABELS.READY_FOR_REVIEW]);
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'success'), core: w.core });
  assert.ok(!w.calls.added.includes(LABELS.TESTED));
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
});

test('Verify success at ready-to-merge adds lifecycle/full-verified', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED], { approved: true });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'success'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.FULL_VERIFIED));
  assert.equal(w.calls.merges.length, 0);
});

test('Verify success at ready-to-merge completes a queued (pending) merge', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED, LABELS.PENDING_MERGE], { approved: true });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'success'), core: w.core });
  assert.ok(w.calls.added.includes(LABELS.FULL_VERIFIED));
  assert.ok(w.calls.removed.includes(LABELS.PENDING_MERGE));
  assert.equal(w.calls.merges.length, 1);
});

test('Verify failure at ready-to-merge reverts to ready-for-review', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED, LABELS.FULL_VERIFIED, LABELS.PENDING_MERGE], { approved: true });
  await lifecycle.handleTestResult({ github: w.github, context: runPayload('Verify', 'failure'), core: w.core });
  assert.ok(w.calls.removed.includes(LABELS.FULL_VERIFIED));
  assert.ok(w.calls.removed.includes(LABELS.TESTED));
  assert.ok(w.calls.removed.includes(LABELS.PENDING_MERGE));
  assert.ok(w.calls.added.includes(LABELS.READY_FOR_REVIEW));
  assert.ok(w.calls.added.includes(LABELS.WAITING_ON_AUTHOR));
  assert.equal(w.calls.merges.length, 0);
});

test('Verify result with stale SHA is ignored', async () => {
  const w = makeWorld([LABELS.READY_TO_MERGE, LABELS.TESTED], { approved: true });
  const ctx = runPayload('Verify', 'success');
  ctx.payload.workflow_run.head_sha = '0000000000different';
  await lifecycle.handleTestResult({ github: w.github, context: ctx, core: w.core });
  assert.ok(!w.calls.added.includes(LABELS.FULL_VERIFIED));
});
