version: 3

project:
  id: github.com/Apicurio/apicurio-registry
  name: apicurio-registry

maven:
  scope-exclude:
    - test
    - provided

paths:
  exclude:
    # Test-only modules (dependencies here are not shipped)
    - integration-tests/
    - utils/concurrency-tests/
