package io.apicurio.registry.systemtest.operator.types;

public enum OperatorKind {
    APICURIO_REGISTRY_BUNDLE_OPERATOR,
    APICURIO_REGISTRY_OLM_OPERATOR,
    STRIMZI_CLUSTER_BUNDLE_OPERATOR,
    STRIMZI_CLUSTER_OLM_OPERATOR,
    KEYCLOAK_OLM_OPERATOR
}
