// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration-tests/testsuite/src/test/resources/serdes/testmessage.proto

package io.apicurio.tests.protobuf;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.apicurio.tests.protobuf.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp time = 1;</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <code>.google.protobuf.Timestamp time = 1;</code>
   * @return The time.
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

  /**
   * <code>string source = 2;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 2;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string destination = 3;</code>
   * @return The destination.
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 3;</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>string uuid = 4;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 4;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>repeated string source_uuids = 5;</code>
   * @return A list containing the sourceUuids.
   */
  java.util.List<java.lang.String>
      getSourceUuidsList();
  /**
   * <code>repeated string source_uuids = 5;</code>
   * @return The count of sourceUuids.
   */
  int getSourceUuidsCount();
  /**
   * <code>repeated string source_uuids = 5;</code>
   * @param index The index of the element to return.
   * @return The sourceUuids at the given index.
   */
  java.lang.String getSourceUuids(int index);
  /**
   * <code>repeated string source_uuids = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the sourceUuids at the given index.
   */
  com.google.protobuf.ByteString
      getSourceUuidsBytes(int index);

  /**
   * <code>string message_type_id = 6;</code>
   * @return The messageTypeId.
   */
  java.lang.String getMessageTypeId();
  /**
   * <code>string message_type_id = 6;</code>
   * @return The bytes for messageTypeId.
   */
  com.google.protobuf.ByteString
      getMessageTypeIdBytes();

  /**
   * <code>string raw_message = 7;</code>
   * @return The rawMessage.
   */
  java.lang.String getRawMessage();
  /**
   * <code>string raw_message = 7;</code>
   * @return The bytes for rawMessage.
   */
  com.google.protobuf.ByteString
      getRawMessageBytes();
}
