// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration-tests/testsuite/src/test/resources/serdes/testmessage.proto

package io.apicurio.tests.protobuf;

/**
 * Protobuf type {@code io.apicurio.tests.protobuf.Point}
 */
public final class Point extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.apicurio.tests.protobuf.Point)
    PointOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Point.newBuilder() to construct.
  private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Point() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Point();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Point(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {
            longitudeOneofCase_ = 1;
            longitudeOneof_ = input.readDouble();
            break;
          }
          case 17: {
            latitudeOneofCase_ = 2;
            latitudeOneof_ = input.readDouble();
            break;
          }
          case 25: {
            altitudeOneofCase_ = 3;
            altitudeOneof_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.apicurio.tests.protobuf.Testmessage.internal_static_io_apicurio_tests_protobuf_Point_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.apicurio.tests.protobuf.Testmessage.internal_static_io_apicurio_tests_protobuf_Point_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.apicurio.tests.protobuf.Point.class, io.apicurio.tests.protobuf.Point.Builder.class);
  }

  private int longitudeOneofCase_ = 0;
  private java.lang.Object longitudeOneof_;
  public enum LongitudeOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LONGITUDE(1),
    LONGITUDEONEOF_NOT_SET(0);
    private final int value;
    private LongitudeOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LongitudeOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static LongitudeOneofCase forNumber(int value) {
      switch (value) {
        case 1: return LONGITUDE;
        case 0: return LONGITUDEONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public LongitudeOneofCase
  getLongitudeOneofCase() {
    return LongitudeOneofCase.forNumber(
        longitudeOneofCase_);
  }

  private int latitudeOneofCase_ = 0;
  private java.lang.Object latitudeOneof_;
  public enum LatitudeOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LATITUDE(2),
    LATITUDEONEOF_NOT_SET(0);
    private final int value;
    private LatitudeOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LatitudeOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static LatitudeOneofCase forNumber(int value) {
      switch (value) {
        case 2: return LATITUDE;
        case 0: return LATITUDEONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public LatitudeOneofCase
  getLatitudeOneofCase() {
    return LatitudeOneofCase.forNumber(
        latitudeOneofCase_);
  }

  private int altitudeOneofCase_ = 0;
  private java.lang.Object altitudeOneof_;
  public enum AltitudeOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ALTITUDE(3),
    ALTITUDEONEOF_NOT_SET(0);
    private final int value;
    private AltitudeOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AltitudeOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static AltitudeOneofCase forNumber(int value) {
      switch (value) {
        case 3: return ALTITUDE;
        case 0: return ALTITUDEONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public AltitudeOneofCase
  getAltitudeOneofCase() {
    return AltitudeOneofCase.forNumber(
        altitudeOneofCase_);
  }

  public static final int LONGITUDE_FIELD_NUMBER = 1;
  /**
   * <code>double longitude = 1;</code>
   * @return Whether the longitude field is set.
   */
  @java.lang.Override
  public boolean hasLongitude() {
    return longitudeOneofCase_ == 1;
  }
  /**
   * <code>double longitude = 1;</code>
   * @return The longitude.
   */
  @java.lang.Override
  public double getLongitude() {
    if (longitudeOneofCase_ == 1) {
      return (java.lang.Double) longitudeOneof_;
    }
    return 0D;
  }

  public static final int LATITUDE_FIELD_NUMBER = 2;
  /**
   * <code>double latitude = 2;</code>
   * @return Whether the latitude field is set.
   */
  @java.lang.Override
  public boolean hasLatitude() {
    return latitudeOneofCase_ == 2;
  }
  /**
   * <code>double latitude = 2;</code>
   * @return The latitude.
   */
  @java.lang.Override
  public double getLatitude() {
    if (latitudeOneofCase_ == 2) {
      return (java.lang.Double) latitudeOneof_;
    }
    return 0D;
  }

  public static final int ALTITUDE_FIELD_NUMBER = 3;
  /**
   * <code>double altitude = 3;</code>
   * @return Whether the altitude field is set.
   */
  @java.lang.Override
  public boolean hasAltitude() {
    return altitudeOneofCase_ == 3;
  }
  /**
   * <code>double altitude = 3;</code>
   * @return The altitude.
   */
  @java.lang.Override
  public double getAltitude() {
    if (altitudeOneofCase_ == 3) {
      return (java.lang.Double) altitudeOneof_;
    }
    return 0D;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (longitudeOneofCase_ == 1) {
      output.writeDouble(
          1, (double)((java.lang.Double) longitudeOneof_));
    }
    if (latitudeOneofCase_ == 2) {
      output.writeDouble(
          2, (double)((java.lang.Double) latitudeOneof_));
    }
    if (altitudeOneofCase_ == 3) {
      output.writeDouble(
          3, (double)((java.lang.Double) altitudeOneof_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (longitudeOneofCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            1, (double)((java.lang.Double) longitudeOneof_));
    }
    if (latitudeOneofCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            2, (double)((java.lang.Double) latitudeOneof_));
    }
    if (altitudeOneofCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            3, (double)((java.lang.Double) altitudeOneof_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.apicurio.tests.protobuf.Point)) {
      return super.equals(obj);
    }
    io.apicurio.tests.protobuf.Point other = (io.apicurio.tests.protobuf.Point) obj;

    if (!getLongitudeOneofCase().equals(other.getLongitudeOneofCase())) return false;
    switch (longitudeOneofCase_) {
      case 1:
        if (java.lang.Double.doubleToLongBits(getLongitude())
            != java.lang.Double.doubleToLongBits(
                other.getLongitude())) return false;
        break;
      case 0:
      default:
    }
    if (!getLatitudeOneofCase().equals(other.getLatitudeOneofCase())) return false;
    switch (latitudeOneofCase_) {
      case 2:
        if (java.lang.Double.doubleToLongBits(getLatitude())
            != java.lang.Double.doubleToLongBits(
                other.getLatitude())) return false;
        break;
      case 0:
      default:
    }
    if (!getAltitudeOneofCase().equals(other.getAltitudeOneofCase())) return false;
    switch (altitudeOneofCase_) {
      case 3:
        if (java.lang.Double.doubleToLongBits(getAltitude())
            != java.lang.Double.doubleToLongBits(
                other.getAltitude())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (longitudeOneofCase_) {
      case 1:
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
        break;
      case 0:
      default:
    }
    switch (latitudeOneofCase_) {
      case 2:
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
        break;
      case 0:
      default:
    }
    switch (altitudeOneofCase_) {
      case 3:
        hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAltitude()));
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.apicurio.tests.protobuf.Point parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.apicurio.tests.protobuf.Point parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.apicurio.tests.protobuf.Point parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.apicurio.tests.protobuf.Point parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.apicurio.tests.protobuf.Point prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.apicurio.tests.protobuf.Point}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.apicurio.tests.protobuf.Point)
      io.apicurio.tests.protobuf.PointOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.apicurio.tests.protobuf.Testmessage.internal_static_io_apicurio_tests_protobuf_Point_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.apicurio.tests.protobuf.Testmessage.internal_static_io_apicurio_tests_protobuf_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.apicurio.tests.protobuf.Point.class, io.apicurio.tests.protobuf.Point.Builder.class);
    }

    // Construct using io.apicurio.tests.protobuf.Point.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      longitudeOneofCase_ = 0;
      longitudeOneof_ = null;
      latitudeOneofCase_ = 0;
      latitudeOneof_ = null;
      altitudeOneofCase_ = 0;
      altitudeOneof_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.apicurio.tests.protobuf.Testmessage.internal_static_io_apicurio_tests_protobuf_Point_descriptor;
    }

    @java.lang.Override
    public io.apicurio.tests.protobuf.Point getDefaultInstanceForType() {
      return io.apicurio.tests.protobuf.Point.getDefaultInstance();
    }

    @java.lang.Override
    public io.apicurio.tests.protobuf.Point build() {
      io.apicurio.tests.protobuf.Point result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.apicurio.tests.protobuf.Point buildPartial() {
      io.apicurio.tests.protobuf.Point result = new io.apicurio.tests.protobuf.Point(this);
      if (longitudeOneofCase_ == 1) {
        result.longitudeOneof_ = longitudeOneof_;
      }
      if (latitudeOneofCase_ == 2) {
        result.latitudeOneof_ = latitudeOneof_;
      }
      if (altitudeOneofCase_ == 3) {
        result.altitudeOneof_ = altitudeOneof_;
      }
      result.longitudeOneofCase_ = longitudeOneofCase_;
      result.latitudeOneofCase_ = latitudeOneofCase_;
      result.altitudeOneofCase_ = altitudeOneofCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.apicurio.tests.protobuf.Point) {
        return mergeFrom((io.apicurio.tests.protobuf.Point)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.apicurio.tests.protobuf.Point other) {
      if (other == io.apicurio.tests.protobuf.Point.getDefaultInstance()) return this;
      switch (other.getLongitudeOneofCase()) {
        case LONGITUDE: {
          setLongitude(other.getLongitude());
          break;
        }
        case LONGITUDEONEOF_NOT_SET: {
          break;
        }
      }
      switch (other.getLatitudeOneofCase()) {
        case LATITUDE: {
          setLatitude(other.getLatitude());
          break;
        }
        case LATITUDEONEOF_NOT_SET: {
          break;
        }
      }
      switch (other.getAltitudeOneofCase()) {
        case ALTITUDE: {
          setAltitude(other.getAltitude());
          break;
        }
        case ALTITUDEONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.apicurio.tests.protobuf.Point parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.apicurio.tests.protobuf.Point) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int longitudeOneofCase_ = 0;
    private java.lang.Object longitudeOneof_;
    public LongitudeOneofCase
        getLongitudeOneofCase() {
      return LongitudeOneofCase.forNumber(
          longitudeOneofCase_);
    }

    public Builder clearLongitudeOneof() {
      longitudeOneofCase_ = 0;
      longitudeOneof_ = null;
      onChanged();
      return this;
    }

    private int latitudeOneofCase_ = 0;
    private java.lang.Object latitudeOneof_;
    public LatitudeOneofCase
        getLatitudeOneofCase() {
      return LatitudeOneofCase.forNumber(
          latitudeOneofCase_);
    }

    public Builder clearLatitudeOneof() {
      latitudeOneofCase_ = 0;
      latitudeOneof_ = null;
      onChanged();
      return this;
    }

    private int altitudeOneofCase_ = 0;
    private java.lang.Object altitudeOneof_;
    public AltitudeOneofCase
        getAltitudeOneofCase() {
      return AltitudeOneofCase.forNumber(
          altitudeOneofCase_);
    }

    public Builder clearAltitudeOneof() {
      altitudeOneofCase_ = 0;
      altitudeOneof_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>double longitude = 1;</code>
     * @return Whether the longitude field is set.
     */
    public boolean hasLongitude() {
      return longitudeOneofCase_ == 1;
    }
    /**
     * <code>double longitude = 1;</code>
     * @return The longitude.
     */
    public double getLongitude() {
      if (longitudeOneofCase_ == 1) {
        return (java.lang.Double) longitudeOneof_;
      }
      return 0D;
    }
    /**
     * <code>double longitude = 1;</code>
     * @param value The longitude to set.
     * @return This builder for chaining.
     */
    public Builder setLongitude(double value) {
      longitudeOneofCase_ = 1;
      longitudeOneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double longitude = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLongitude() {
      if (longitudeOneofCase_ == 1) {
        longitudeOneofCase_ = 0;
        longitudeOneof_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>double latitude = 2;</code>
     * @return Whether the latitude field is set.
     */
    public boolean hasLatitude() {
      return latitudeOneofCase_ == 2;
    }
    /**
     * <code>double latitude = 2;</code>
     * @return The latitude.
     */
    public double getLatitude() {
      if (latitudeOneofCase_ == 2) {
        return (java.lang.Double) latitudeOneof_;
      }
      return 0D;
    }
    /**
     * <code>double latitude = 2;</code>
     * @param value The latitude to set.
     * @return This builder for chaining.
     */
    public Builder setLatitude(double value) {
      latitudeOneofCase_ = 2;
      latitudeOneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double latitude = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatitude() {
      if (latitudeOneofCase_ == 2) {
        latitudeOneofCase_ = 0;
        latitudeOneof_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>double altitude = 3;</code>
     * @return Whether the altitude field is set.
     */
    public boolean hasAltitude() {
      return altitudeOneofCase_ == 3;
    }
    /**
     * <code>double altitude = 3;</code>
     * @return The altitude.
     */
    public double getAltitude() {
      if (altitudeOneofCase_ == 3) {
        return (java.lang.Double) altitudeOneof_;
      }
      return 0D;
    }
    /**
     * <code>double altitude = 3;</code>
     * @param value The altitude to set.
     * @return This builder for chaining.
     */
    public Builder setAltitude(double value) {
      altitudeOneofCase_ = 3;
      altitudeOneof_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double altitude = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAltitude() {
      if (altitudeOneofCase_ == 3) {
        altitudeOneofCase_ = 0;
        altitudeOneof_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.apicurio.tests.protobuf.Point)
  }

  // @@protoc_insertion_point(class_scope:io.apicurio.tests.protobuf.Point)
  private static final io.apicurio.tests.protobuf.Point DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.apicurio.tests.protobuf.Point();
  }

  public static io.apicurio.tests.protobuf.Point getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Point>
      PARSER = new com.google.protobuf.AbstractParser<Point>() {
    @java.lang.Override
    public Point parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Point(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Point> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Point> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.apicurio.tests.protobuf.Point getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

