// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration-tests/testsuite/src/test/resources/serdes/testmessage.proto

package io.apicurio.tests.protobuf;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.apicurio.tests.protobuf.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double longitude = 1;</code>
   * @return Whether the longitude field is set.
   */
  boolean hasLongitude();
  /**
   * <code>double longitude = 1;</code>
   * @return The longitude.
   */
  double getLongitude();

  /**
   * <code>double latitude = 2;</code>
   * @return Whether the latitude field is set.
   */
  boolean hasLatitude();
  /**
   * <code>double latitude = 2;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double altitude = 3;</code>
   * @return Whether the altitude field is set.
   */
  boolean hasAltitude();
  /**
   * <code>double altitude = 3;</code>
   * @return The altitude.
   */
  double getAltitude();

  public io.apicurio.tests.protobuf.Point.LongitudeOneofCase getLongitudeOneofCase();

  public io.apicurio.tests.protobuf.Point.LatitudeOneofCase getLatitudeOneofCase();

  public io.apicurio.tests.protobuf.Point.AltitudeOneofCase getAltitudeOneofCase();
}
