// Metadata created by nebel

[id="intro-to-registry"]
= {registry} overview

{registry} is a datastore for standard event schemas and API designs. {registry} enables enables you to decouple the structure of your data from your applications and to share and manage your data structure using a REST interface. For example, client applications can dynamically push/pull the latest schema updates to/from the registry at runtime without needing to redeploy.

{registry} also provides the following capabilities:

* Rules to govern how registry content evolves over time. For example, this includes rules for content validation and version compatibility.

* Full Apache Kafka schema registry support. 

* Client serializers/deserializers (SerDes) to validate Kafka and other message types at runtime.

* Compatibility with existing Confluent and IBM schema registry client applications.

ifdef::rh-service-registry[]

{registry} is based on the Apicurio Registry open source community project. For details, see https://github.com/apicurio/apicurio-registry. 

endif::[]

== Supported artifact types
{registry} supports the following artifact types:

[%header,cols=2*] 
|===
|Type
|Description
|`AVRO`
|Apache Avro schema
|`PROTOBUF`
|Google protocol buffers schema
|`PROTOBUF_FD`
|Google protocol buffers file descriptor
|`JSON`
|JSON Schema
|`GRAPHQL`
|GraphQL schema
|`OPENAPI`
|OpenAPI specification
|`ASYNCAPI`
|AsyncAPI specification
|===

== Storage implementations
{registry} supports the following artifact storage implementations: 

ifdef::apicurio-registry[]

* In-memory 
* Java Persistence API 
* Apache Kafka 
* Apache Kafka Streams
* Infinispan

NOTE: The in-memory storage option is suitable for a development environment only. All data is lost when restarting this storage implementation. All other storage options are suitable for development and production environments.

For more details, see https://github.com/Apicurio/apicurio-registry. 

endif::[]

ifdef::rh-service-registry[]

* Red Hat AMQ Streams 1.3
* Red Hat Data Grid 7.3
* Java Persistence API for relational databases

endif::[]

//The {registry} Operator enables you to install {registry} into your storage implementation on OpenShift.

== Available distributions

ifdef::apicurio-registry[]
{registry} provides the following container images for different storage options: 

[%header,cols=2*] 
|===
|Storage option
|Container Image
|In-memory
|https://hub.docker.com/r/apicurio/apicurio-registry-mem
|Java Persistence API  
|https://hub.docker.com/r/apicurio/apicurio-registry-jpa 
|Apache Kafka
|https://hub.docker.com/r/apicurio/apicurio-registry-kafka 
|Apache Kafka Streams
|https://hub.docker.com/r/apicurio/apicurio-registry-streams
|===

.Additional resources
* For details on building from source code, see https://github.com/Apicurio/apicurio-registry.

endif::[]

ifdef::rh-service-registry[]
{registry} distributions are available as follows:

[%header,cols=2*] 
|===
|Distribution
|Location
|Container image
|link:{download-url-registry-container-catalog}[Red Hat Container Catalog]
|Maven repository
|link:{download-url-registry-fuse-maven}[Software Downloads for Red Hat Fuse]
|Full Maven repository (with all dependencies)
|link:{download-url-registry-fuse-maven-full}[Software Downloads for Red Hat Fuse]
|Source code
|link:{download-url-registry-fuse-source-code}[Software Downloads for Red Hat Fuse]
|===

NOTE: You must have a subscription for Red Hat Fuse and be logged into the Red Hat Customer Portal to access the available {registry} distributions.
endif::[]

== Registry REST API
The {registry} REST API enables client applications to manage the artifacts in the registry. It provides create, read, update, and delete operations for the following:

* Schema and API artifacts
* Artifact versions 
* Artifact metadata
* Global rules
* Artifact rules 

For detailed information, see the link:files/registry-rest-api.htm[Apicurio Registry REST API documentation].

.Compatibility with other schema registries
The {registry} REST API is compatible with the Confluent and IBM schema registry REST APIs. This means that applications using Confluent or IBM client libraries can use {registry} instead as a drop-in replacement. 
ifdef::rh-service-registry[]
For more details, see link:https://developers.redhat.com/blog/2019/12/17/replacing-confluent-schema-registry-with-red-hat-integration-service-registry/[Replacing Confluent Schema Registry with Red Hat Integration Service Registry].
endif::[]

== Client serializers/deserializers 
Producer applications use serializers to create messages that conform to a specific schema. Consumer applications use deserializers to validate that the messages have been serialized using the correct schema, based on a specific schema ID. {registry} provides client serializers/deserializers to validate the following message types at runtime:

* Apache Avro
* Google protocol buffers
* JSON Schema

The {registry} Maven repositories and source code include the serializer/deserializer implementations, which can be used by client developers to integrate with {registry}. These implementations includes custom `io.apicurio.registry.utils.serde` Java classes, which enable client applications to push/pull their schemas from {registry} at runtime. 

ifdef::rh-service-registry[]
For details on how to use the Apache Avro client serializer/deserializer in AMQ Streams producer and consumer applications, see
link:https://access.redhat.com/documentation/en-us/red_hat_amq/{amq_version}/html/using_amq_streams_on_openshift/index[Using AMQ Streams on Openshift].
endif::[]

[id="registry-demo"]
== Registry demo
Apicurio Registry provides an open source demo of Apache Avro serialization/deserialization based on storage in Apache Kafka Streams. This demo shows how the serializer/deserializer gets the Avro schema from the registry at runtime and then uses it to serialize and deserialize Kafka messages. For more details, see link:https://github.com/Apicurio/apicurio-registry-demo[].

ifdef::rh-service-registry[]
For another demo of Avro serialization/deserialization, this time with storage in an Apache Kafka cluster based on Strimzi, see the Red Hat Developer article on link:https://developers.redhat.com/blog/2019/12/16/getting-started-with-red-hat-integration-service-registry/[Getting Started with Red Hat Integration Service Registry].
endif::[]
