// Metadata created by nebel

[id="intro-to-registry"]
= {registry} overview

{registry} is a datastore for standard event schemas and API designs. It enables developers to decouple the structure of their data from their applications and to share and manage their data structure using a REST interface. For example, client applications can dynamically push/pull the latest schema updates to/from the registry at runtime without needing to redeploy. 

{registry} enables developers to create rules to govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility. {registry} also provides full Apache Kafka schema registry support, client serializer/deserializer (SerDe) to validate Kafka messages at runtime, and compatibility with existing Confluent registry clients.

ifdef::rh-service-registry[]

{registry} is built on the Apicurio Registry open source community project. For details, see https://github.com/apicurio/apicurio-registry. 

[IMPORTANT]
====
{registry} is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. 

These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information about the support scope of Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview.
====

endif::[]

== Supported artifact types
{registry} supports the following artifact types:

[%header,cols=2*] 
|===
|Type
|Description
|`AVRO`
|Apache Avro schema
|`PROTOBUF`
|Google protocol buffers schema
|`JSON`
|JSON Schema
|`OPENAPI`
|OpenAPI specification
|`ASYNCAPI`
|AsyncAPI specification
|===

== Storage implementations
{registry} supports the following pluggable storage options: 

ifdef::apicurio-registry[]

* In-memory 
* Java Persistence API 
* Apache Kafka 
* Apache Kafka Streams

NOTE: The in-memory storage option is suitable for a development environment only. All data is lost when restarting this storage implementation. All other storage options are suitable for development and production environments.

For more details, see https://github.com/Apicurio/apicurio-registry. 

endif::[]

ifdef::rh-service-registry[]

* Red Hat AMQ Streams 1.3

endif::[]

== Distribution

ifdef::apicurio-registry[]
{registry} provides the following container images for the available storage options: 

[%header,cols=2*] 
|===
|Storage option
|Container Image
|In-memory
|https://hub.docker.com/r/apicurio/apicurio-registry-mem
|Java Persistence API  
|https://hub.docker.com/r/apicurio/apicurio-registry-jpa 
|Apache Kafka
|https://hub.docker.com/r/apicurio/apicurio-registry-kafka 
|Apache Kafka Streams
|https://hub.docker.com/r/apicurio/apicurio-registry-streams
|===

.Additional resources
* For details on building from source code, see https://github.com/Apicurio/apicurio-registry.

endif::[]

ifdef::rh-service-registry[]
{registry} is available as follows:

[%header,cols=2*] 
|===
|Distribution
|Location
|Container image
|link:https://access.redhat.com/containers/#/registry.access.redhat.com/fuse7-tech-preview/fuse-service-registry-rhel7[Red Hat Container Catalog]
|Maven repository
|link:https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=75261&product=jboss.fuse&version=7.5.0&downloadType=distributions[Software Downloads for Fuse v7.5.0]
|Full Maven repository (with all dependencies)
|link:https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=75271&product=jboss.fuse&version=7.5.0&downloadType=distributions[Software Downloads for Fuse v7.5.0]
|Source code
|link:https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=75251&product=jboss.fuse&version=7.5.0&downloadType=distributions[Software Downloads for Fuse v7.5.0]
|===

Both Maven repositories also include a custom Kafka client serializer/deserializer, which can be used by Kafka client developers to integrate with {registry}. These Java classes allow Kafka client applications to push/pull their schemas from the registry at runtime.

NOTE: You must be logged into the Red Hat Customer Portal to access these resources.

endif::[]

== {registry} REST API
The {registry} REST API enables client applications to manage the artifacts in the registry. It provides create, read, update, and delete operations for the following:

* Schema and API artifacts
* Versions 
* Metadata
* Global rules
* Artifact rules 

For detailed information, see the link:files/registry-rest-api.htm[Registry REST API documentation].

The Service Registry REST API is also compatible with the Confluent schema registry REST API. This means that applications using Confluent client libraries can use Service Registry instead.


== Registry demo
Apicurio Registry provides an open source demo of Apache Avro serialization/deserialization based storage in Apache Kafka Streams. 

This demo shows how the serializer/deserializer gets the Avro schema from the registry at runtime and then uses it to serialize and deserialize Kafka messages.

For more details, see link:https://github.com/Apicurio/apicurio-registry-demo[].
