// Metadata created by nebel

[id="intro-to-registry"]
= Apicurio Registry overview

Apicurio Registry is a datastore for standard event schemas and API designs. It enables developers to share and manage the structure of their data using a REST interface. For example, client applications can dynamically pull the latest updates from the registry at runtime without needing to redeploy. 

Apicurio Registry also enables developers to create rules to govern how the registry content can evolve over time. For example, this includes rules for content validation and version compatibility.

== Supported artifact types
The supported artifact format types that the registry can store are:

[%header,cols=2*] 
|===
|Type
|Description
|`AVRO`
|Apache Avro schema
|`PROTOBUF`
|Google protocol buffers schema 
|`JSON`
|JSON Schema
|`OPENAPI`
|OpenAPI specification
|`ASYNCAPI`
|AsyncAPI specification
|===

== Storage implementations
Apicurio Registry provides the following pluggable storage options: 

* In-memory 
* Java Persistence API 
* Apache Kafka 
* Apache Kafka Streams

NOTE: The in-memory storage option is suitable for a development environment only. All data is lost when using this storage implementation. All other storage options are suitable for development and production environments.

For more details, see https://github.com/Apicurio/apicurio-registry. 

== Container images
Apicurio Registry provides the following container images for each storage option: 

[%header,cols=2*] 
|===
|Storage option
|Container Image
|In-memory
|https://hub.docker.com/r/apicurio/apicurio-registry-mem
|Java Persistence API  
|https://hub.docker.com/r/apicurio/apicurio-registry-jpa 
|Apache Kafka
|https://hub.docker.com/r/apicurio/apicurio-registry-kafka 
|Apache Kafka Streams
|https://hub.docker.com/r/apicurio/apicurio-registry-streams
|===

.Additional resources

* For details on building from source, see https://github.com/Apicurio/apicurio-registry.

== Apicurio Registry REST API
The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. It provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata. 

For detailed information, see the link:files/index.html[Apicurio Registry REST API documentation].
