// Metadata created by nebel

[id="registry-rest-api"]
= Registry REST API
Using the Registry REST API, client applications can manage the artifacts in {registry}. This API provides create, read, update, and delete operations for:

Artifacts::
Manage the schema and API design artifacts stored in the registry. Also includes browse or search for artifacts, and manage the lifecycle state of an artifact: enabled, disabled, or deprecated. 
Artifact versions::
Manage the versions that are created when artifact content is updated. Also includes browse or search for versions, and manage the lifecycle state of a version: enabled, disabled, or deprecated.
Artifact metadata::
Manage details such as when the artifact was created, last updated, and so on.
Global rules::
Configure rules to govern the content evolution of all artifacts to prevent invalid or incompatible content from being added to the registry. Global rules are applied only if an artifact does not have its own specific artifact rules configured. 
Artifact rules::
Configure rules to govern the content evolution of a specific artifact to prevent invalid or incompatible content from being added to the registry. Artifact rules override any global rules configured. 

.Compatibility with other schema registries
The Registry REST API is compatible with the Confluent schema registry REST API. This means that applications using Confluent client libraries can use {registry} instead as a drop-in replacement. 
ifdef::rh-service-registry[]
For more details, see link:https://developers.redhat.com/blog/2019/12/17/replacing-confluent-schema-registry-with-red-hat-integration-service-registry/[Replacing Confluent Schema Registry with Red Hat Integration Service Registry].
endif::[]

.Additional resources
* For detailed information, see the link:files/registry-rest-api.htm[Apicurio Registry REST API documentation].
* The Registry REST API documentation is also available from the main endpoint of your {registry} deployment, for example, on `\http://MY-REGISTRY-URL/api`.  
