// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="installing-registry-kafka-storage"]
ifdef::apicurio-registry[]
= Installing {registry} with Apache Kafka storage
endif::[]

ifdef::rh-service-registry[]
= Installing {registry} with Apache Kafka storage using Docker
endif::[]

This topic explains how to install and run {registry} with Kafka storage from a container image. This storage option is suitable for production environments. 

The following Kafka-based systems are supported:

* Apache Kafka 2.2.x
* Apache Kafka 2.3

.Prerequisites

* You must have Docker installed and the Docker daemon running.
ifdef::apicurio-registry[]
* Ensure that you can connect to the container repository: https://hub.docker.com/r/apicurio/apicurio-registry-kafka.
endif::[] 
* Ensure that `KAFKA_HOME` is set to the location of your Kafka-based system. 
* You must already have your Kafka broker running. For example: 
+
[source,bash]
----
$KAFKA_HOME/bin/zookeeper-server-start.sh $KAFKA_HOME/config/zookeeper.properties &
$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties &
----
+ 
For more details, see https://kafka.apache.org/quickstart. 

.Procedure
ifdef::apicurio-registry[]
. Get the {registry} container image:
+
[source,bash]
----
$ docker pull apicurio/apicurio-registry-kafka 
----
. Run the container image and specify the following environment variable for your Kafka system: 
+
** `KAFKA_BOOTSTRAP_SERVERS` - The address(es) of your Kafka broker(s). 
+
For example:  
+
[source,bash]
----
$ docker run -it -p 8080:8080 -e "KAFKA_BOOTSTRAP_SERVERS=kafka:9092" apicurio/apicurio-registry-kafka:latest
----
endif::[]

ifdef::rh-service-registry[]
. Log in and authenticate using the following command: 
+
[source,bash]
----
$ docker login registry.redhat.io
----
. Get the {registry} container image:
+
[source,bash]
----
$ docker pull registry.redhat.io/fuse7-tech-preview/fuse-service-registry-rhel7 
----
. Run the container image and specify the following environment variable for your Kafka system: 
+
** `KAFKA_BOOTSTRAP_SERVERS` - The address(es) of your Kafka broker(s). 
+
For example:  
+
[source,bash]
----
$ docker run -it -p 8080:8080 -e "KAFKA_BOOTSTRAP_SERVERS=kafka:9092" registry.redhat.io/fuse7-tech-preview/fuse-service-registry-rhel7
----
endif::[]
. Send a test request using the {registry} REST API. For example, enter the following `curl` command to create a simple artifact:
+
[source,bash]
----
$ curl -X POST -H "Content-Type: application/json" --data '{"id": "Procurement Invoice", "name": "My Invoice", "description": "My invoice description", "type": "AVRO", "version": 1}' http://localhost:8080/artifacts 
----
. Verify that the response includes the expected JSON body. For example:
+
[source,bash]
----
{"createdOn":1571757704485,"modifiedOn":1571757704485,"id":"448bc6fe-bbf6-41c9-ba35-1a96a0d198bf","version":1,"type":"AVRO"}
----

.Additional resources
* For more REST API sample requests, see the link:files/registry-rest-api.htm[Registry REST API documentation].
* For a demo based on Kafka Streams storage, see the link:https://github.com/Apicurio/apicurio-registry-demo[Registry demo].
* For more details on Apache Kafka, see https://kafka.apache.org/documentation/.
ifdef::apicurio-registry[]
* For details on installing on OpenShift, see the following:
** link:https://github.com/Apicurio/apicurio-registry/tree/1.0.x/distro/openshift-template[{registry} OpenShift  template]
** link:https://docs.openshift.com/container-platform/3.11/dev_guide/templates.html[Using templates on OpenShift v3.11]
** link:https://docs.openshift.com/container-platform/4.2/openshift_images/using-templates.html[Using templates on OpenShift v4.x]
endif::[]
