// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="installing-registry-in-memory-storage"]
= Installing {prodname} with in-memory storage

This section explains how to install and run {prodname} with simple in-memory storage from a container image. 

NOTE: The in-memory storage option is suitable for development only. All data is lost when the container image is restarted.  

.Prerequisites

* Ensure that you can connect to the container repository: 
https://hub.docker.com/r/apicurio/apicurio-registry-mem

.Procedure

. Get the {prodname} container image:
+
[source,bash]
----
$ docker pull apicurio/apicurio-registry-mem
----
. Run the container image: 
+
[source,bash]
----
$ docker run -it -p 8080:8080 apicurio/apicurio-registry-mem:latest
----

. Send a test request using the {prodname} REST API. For example, enter the following `curl` command to create a simple artifact:
+
[source,bash]
----
$ curl -X POST -H "Content-Type: application/json" --data '{"id": "Procurement Invoice", "name": "My Invoice", "description": "My invoice description", "type": "AVRO", "version": 1}' http://localhost:8080/artifacts 
----
. Verify that the response includes the expected JSON body. For example:
+
[source,bash]
----
{"createdOn":1571757704485,"modifiedOn":1571757704485,"id":"448bc6fe-bbf6-41c9-ba35-1a96a0d198bf","version":1,"type":"AVRO"}
----

.Additional resources
* For more REST API sample requests, see the link:files/index.html[{prodname} REST API documentation].
* For details on installing on OpenShift, see the following:
** link:https://github.com/Apicurio/apicurio-registry/tree/1.0.x/distro/openshift-template[Apicurio registry OpenShift template]
** link:https://docs.openshift.com/container-platform/3.11/dev_guide/templates.html[Using templates on OpenShift v4.x]
** link:https://docs.openshift.com/container-platform/4.2/openshift_images/using-templates.html[Using templates on OpenShift v3.x]
