// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="installing-registry-kafka-storage"]
= Installing Apicurio Registry with Apache Kafka storage

This topic explains how to install and run Apicurio Registry with Apache Kafka storage from a container image. This storage option is suitable for production environments. 

The Kafka storage implementation uses the following architecture:

* Storage producer to forward HTTP requests from the Apicurio Registry REST API to the Kafka broker
* Storage consumer to handle previously sent HTTP requests from the REST API as Kafka messages
* Snapshot producer to send the current state's snapshot to the Kafka broker
* Snapshot consumer for initial snapshot handling at application start

.Prerequisites
* Ensure that you can connect to the container repository: https://hub.docker.com/r/apicurio/apicurio-registry-kafka 
* You must already have a Kafka broker running. You can specify your Kafka system configuration when starting the container image. 

.Procedure
. Get the Apicurio Registry container image:
+
[source,bash]
----
$ docker pull apicurio/apicurio-registry-kafka 
----
. Run the container image and specify the following environment variables for your Kafka system: 
+
** `KAFKA_HOME`  - The location of your Kafka system.
** `KAFKA_BOOTSTRAP_SERVERS` - The address(es) of your Kafka broker(s). 
+
For example:  
+
[source,bash]
----
$ docker run -it -p 8080:8080 \   
-e "KAFKA_HOME=opt/kafka" \
-e "KAFKA_BOOTSTRAP_SERVERS=kafka-broker1" \ 
apicurio/apicurio-registry-kafka:latest
----

. Send a test request using the Apicurio Registry REST API. For example, enter the following curl command to create a simple artifact:
+
[source,bash]
----
$ curl -X POST -H "Content-Type: application/json" --data '{"id": "Procurement Invoice", "name": "My Invoice", "description": "My invoice description", "type": "AVRO", "version": 1}' http://localhost:8080/artifacts 
----
. Verify that the response includes the expected JSON body. For example:
+
[source,bash]
----
{"createdOn":1571757704485,"modifiedOn":1571757704485,"id":"448bc6fe-bbf6-41c9-ba35-1a96a0d198bf","version":1,"type":"AVRO"}
----

.Additional resources
• For more sample requests, see the link:files/index.html[Apicurio Registry REST API documentation].
• For more details on Kafka, see the link:https://kafka.apache.org/documentation/[Apache Kafka documentation].
