// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="installing-registry-kafka-kubernetes-storage"]
ifdef::apicurio-registry[]
= Installing {registry} with Apache Kafka storage on OpenShift

This topic explains how to install and run {registry} with storage in Apache Kafka on OpenShift from a container image using Strimzi. This storage option is suitable for production environments. 

The following versions are supported:

* Apache Kafka 2.2.x
* Apache Kafka 2.3
endif::[]

ifdef::rh-service-registry[]
=  Installing {registry} with AMQ Streams storage on OpenShift

This topic explains how to install and run {registry} with storage in Red Hat AMQ Streams on OpenShift from a container image. This storage option is suitable for production environments. 

The following versions are supported:

* Red Hat AMQ Streams 1.3
endif::[]

.Prerequisites

ifdef::apicurio-registry[]
* You must have a Kubernetes or OpenShift cluster with cluster administrator access.

* Ensure that you can connect to the {registry} container image in GitHub: link:https://hub.docker.com/r/apicurio/apicurio-registry-kafka[].
* You must have installed and deployed Strimzi on your Kubernetes or OpenShift cluster. For example: 
+
[source,bash]
----
minikube start --memory="8000m"
kubectl create namespace kafka
curl -L https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.14.0/strimzi-cluster-operator-0.14.0.yaml \
  | sed 's/namespace: .*/namespace: kafka/' \
  | kubectl apply -f - -n kafka
kubectl apply -f kubernetes/resources.yaml
kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n kafka
----
+ 
For more details, see https://strimzi.io/docs/quickstart/master/
endif::[] 

ifdef::rh-service-registry[]
* You must have an OpenShift cluster with cluster administrator access. OpenShift 3.11 and 4.x are supported.
* You must have already installed AMQ Streams on your cluster. For more details, see link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.5/html/using_amq_streams_on_openshift/getting-started-str?lb_target=stage[Getting Started with AMQ Streams on OpenShift].  
* Ensure that you can access the 
link:https://access.redhat.com/containers/#/registry.access.redhat.com/fuse7-tech-preview/fuse-service-registry-rhel7[{registry} image in the Container Catalog]:
** Create a service account and pull secret for the image. For details, see link:https://access.redhat.com/terms-based-registry/[Container Service Accounts].
** Download the pull secret and submit it to your OpenShift cluster. For example: 
+
[source,bash]
----
$ oc create -f 11223344_service-registry-secret.yaml --namespace=my-project
----
endif::[]

.Procedure
ifdef::apicurio-registry[]
. Get the link:https://github.com/Apicurio/apicurio-registry/blob/1.0.x/distro/openshift-template/apicurio-registry-template-kafka.yml[{registry} OpenShift template].
endif::[]

ifdef::rh-service-registry[]
. Get the 
link:https://github.com/Apicurio/apicurio-registry/blob/1.0.x-redhat/distro/openshift-template/service-registry-template.yml[{registry} OpenShift template].
endif::[]

. Enter the following command to get the name of the Kafka bootstrap service running on your OpenShift cluster:
+
[source,bash]
----
$ oc get services | grep .*kafka-bootstrap
----

ifdef::rh-service-registry[]
. Create a new OpenShift application and specify the following parameters: 
** `service-registry-template.yml`: The OpenShift template file for {registry}.
** `KAFKA_BOOTSTRAP_SERVERS`: The name of the Kafka bootstrap service on your cluster, followed by the Kafka broker port (for example, `my-cluster-kafka-bootstrap:9092`).  
** `REGISTRY_ROUTE`: The name of the route that will expose {registry}, which is based on your cluster environment (for example, `my-cluster-service-registry-myproject.example.com`).
+
For example: 
+
[source,bash]
----
$ oc new-app service-registry-template.yml -p KAFKA_BOOTSTRAP_SERVERS=my-cluster-kafka-bootstrap:9092 -p REGISTRY_ROUTE=my-cluster-service-registry-myproject.example.com
----
+
You should see output such as the following: 
+
----
Deploying template "myproject/service-registry" for "service-registry-template.yml" to project myproject

    service-registry
    ---------
    Congratulations on deploying Service Registry into OpenShift!
    
    All components have been deployed and configured.

    * With parameters:
       * Registry Route Name=my-cluster-service-registry-myproject.example.com
       * Registry Max Memory Limit=1300Mi
       * Registry Memory Requests=600Mi
       * Registry Max CPU Limit=1
       * Registry CPU Requests=100m
       * Kafka Bootstrap Servers=my-cluster-kafka-bootstrap:9092

--> Creating resources ...
   imagestream.image.openshift.io "registry" created
   service "service-registry" created
   deploymentconfig.apps.openshift.io "service-registry" created
   route.route.openshift.io "service-registry" created
--> Success
   Access your application via route 'my-cluster-service-registry-myproject.example.com' 
   Run 'oc status' to view your app.
----
endif::[]

ifdef::apicurio-registry[]
. Create a new OpenShift application and specify the following: 
+
** `apicurio-registry-template-kafka`: The OpenShift template file for {registry}.
** `KAFKA_BOOTSTRAP_SERVERS`: The name of the Kafka bootstrap service on your cluster, followed by the Kafka broker port (for example, `my-cluster-kafka-bootstrap:9092`).  
** `REGISTRY_ROUTE`: The name of the route that will expose {registry}, which is based on your cluster environment (for example, `my-cluster-service-registry-myproject.example.com`).
+
For example: 
+
[source,bash]
----
$ oc new-app apicurio-registry-template-kafka.yml -p KAFKA_BOOTSTRAP_SERVERS=my-cluster-kafka-bootstrap:9092 -p REGISTRY_ROUTE=my-cluster-service-registry-myproject.example.com
----
endif::[]

. Send a test request using the {registry} REST API. For example, enter the following `curl` command to create a simple Avro schema artifact for a share price application in the registry:
+
[source,bash]
----
$ curl -X POST -H "Content-type: application/json; artifactType=AVRO" -H "X-Registry-ArtifactId: prices-value" --data '{"type":"record","name":"price","namespace":"com.redhat","fields":[{"name":"symbol","type":"string"},{"name":"price","type":"string"}]}' my-cluster-service-registry-myproject.example.com/artifacts
----
. Verify that the response includes the expected JSON body to confirm that the Avro schema artifact was created in the registry. For example:
+
[source,bash]
----
{"createdOn":1578310374517,"modifiedOn":1578310374517,"id":"prices-value","version":1,"type":"AVRO","globalId":8}
----

.Additional resources
* For more REST API sample requests, see the link:files/registry-rest-api.htm[Registry REST API documentation].
ifdef::rh-service-registry[]
* For more details on registry demo applications: 
** https://github.com/Apicurio/apicurio-registry-demo
** link:https://developers.redhat.com/blog/2019/12/16/getting-started-with-red-hat-integration-service-registry/[Getting Started with Red Hat Integration Service Registry]
* For more details on AMQ Streams:
** link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.5/html/using_amq_streams_on_openshift/index?[Using AMQ Streams on OpenShift]
** link:https://developers.redhat.com/blog/2018/10/29/how-to-run-kafka-on-openshift-the-enterprise-kubernetes-with-amq-streams[How to run AMQ Streams on Minishift]
endif::[]
* For more details on OpenShift templates, see the link:https://docs.openshift.com/container-platform/4.2/openshift_images/using-templates.html[OpenShift user documention].
