// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="installing-registry-kafka-streams-storage"]
= Installing Apicurio Registry with Apache Kafka Streams storage

This topic explains how to install and run Apicurio Registry with Apache Kafka Streams storage from a container image. This storage option is suitable for production environments. 

The Kafka Streams storage implementation uses the following architecture:

* Storage producer to forward HTTP requests from the Apicurio Registry REST API to the Kafka broker
* Streams input `KStream` to handle previously sent HTTP requests from the REST API as Kafka messages
* Streams `KStream` to handle the result of the input `KStream`
* Each `KStream` uses a `KeyValueStore` to keep the current storage state

.Prerequisites
* Ensure that you can connect to the container repository: https://hub.docker.com/r/apicurio/apicurio-registry-kafka.
* Ensure that `KAFKA_HOME` is set to the location of your Kafka v2.2.x system. 
* You must already have a Kafka broker running and set up your Kafka topics.

.Procedure
. Get the Apicurio Registry container image:
+
[source,bash]
----
$ docker pull apicurio/apicurio-registry-kafka-streams 
----
. Run the container image and specify the following environment variables for your Kafka system: 
+
** `KAFKA_BOOTSTRAP_SERVERS` - The address(es) of your Kafka broker(s).
** `APPLICATION_ID` - The name of your Kafka Streams application.
+
For example:  
+
[source,bash]
----
$ docker run -it -p 8080:8080 -e "KAFKA_BOOTSTRAP_SERVERS=kafka:9092" -e "APPLICATION_ID=my-kafka-streams-app" --link apicurio/apicurio-registry-kafka-streams:latest
----

. Send a test request using the Apicurio Registry REST API. For example, enter the following curl command to create a simple artifact:
+
[source,bash]
----
$ curl -X POST -H "Content-Type: application/json" --data '{"id": "Procurement Invoice", "name": "My Invoice", "description": "My invoice description", "type": "AVRO", "version": 1}' http://localhost:8080/artifacts 
----
. Verify that the response includes the expected JSON body. For example:
+
[source,bash]
----
{"createdOn":1571757704485,"modifiedOn":1571757704485,"id":"448bc6fe-bbf6-41c9-ba35-1a96a0d198bf","version":1,"type":"AVRO"}
----

.Additional resources
* For more REST API sample requests, see the link:files/index.html[Apicurio Registry REST API documentation].
* For a demo based on Kafka Streams storage, see the link:https://github.com/alesj/registry-demo[Apicurio Registry Demo].
* For more details on Kafka Streams, see the link:https://kafka.apache.org/documentation/streams//[Apache Kafka Streams documentation].
