// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="installing-registry-kafka-storage"]
= Installing {prodname} with Apache Kafka storage

This topic explains how to install and run {prodname} with Apache Kafka storage from a container image. This storage option is suitable for production environments. 

.Prerequisites

* Ensure that `KAFKA_HOME` is set to the location of your Kafka v2.2.x or v2.3 system. 
* You must already have your Kafka broker running. For example: 
+
[source,bash]
----
$KAFKA_HOME/bin/zookeeper-server-start.sh $KAFKA_HOME/config/zookeeper.properties &
$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties &
----
+ 
For more details, see https://kafka.apache.org/quickstart. 
* Ensure that you can connect to the container repository: https://hub.docker.com/r/apicurio/apicurio-registry-kafka 


.Procedure
. Get the {prodname} container image:
+
[source,bash]
----
$ docker pull apicurio/apicurio-registry-kafka 
----
. Run the container image and specify the following environment variable for your Kafka system: 
+
** `KAFKA_BOOTSTRAP_SERVERS` - The address(es) of your Kafka broker(s). 
+
For example:  
+
[source,bash]
----
$ docker run -it -p 8080:8080 -e "KAFKA_BOOTSTRAP_SERVERS=kafka:9092" -link apicurio/apicurio-registry-kafka:latest
----

. Send a test request using the {prodname} REST API. For example, enter the following curl command to create a simple artifact:
+
[source,bash]
----
$ curl -X POST -H "Content-Type: application/json" --data '{"id": "Procurement Invoice", "name": "My Invoice", "description": "My invoice description", "type": "AVRO", "version": 1}' http://localhost:8080/artifacts 
----
. Verify that the response includes the expected JSON body. For example:
+
[source,bash]
----
{"createdOn":1571757704485,"modifiedOn":1571757704485,"id":"448bc6fe-bbf6-41c9-ba35-1a96a0d198bf","version":1,"type":"AVRO"}
----

.Additional resources
* For more REST API sample requests, see the link:files/index.html[{prodname} REST API documentation].
* For a demo based on Kafka Streams storage, see the link:https://github.com/alesj/registry-demo[{prodname} Demo].
* For more details on Kafka, see the link:https://kafka.apache.org/documentation/[Apache Kafka documentation].
