// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts.adoc

[id="browsing-artifacts-using-console"]
= Viewing artifacts using the {registry} web console

You can use the {registry} web console to browse the event schema and API design artifacts stored in the registry. This section shows simple examples of viewing {registry} artifacts, versions, and artifact rules. For more details on the artifact types stored in the registry, see xref:registry-artifact-types[]. 

.Prerequisites

* {registry} must be installed and running in your environment. For details, see xref:installing-the-registry[].
* Artifacts must have been added to the registry using the {registry} web console, REST API commands, Maven repository, or a Java client application. 

.Procedure

. Connect to the {registry} web console on: 
+
`*\http://MY_REGISTRY_URL/ui*`

. Browse the list of artifacts stored in the registry, or enter a search string to find an artifact. You can select to search by a specific *Name*, *Description*, *Label*, or *Everything*.  

. Click *View artifact* to view the *Artifact Details*:

** *Info*: Displays artifact metadata including name, description, status, created, and modified. Artifact actions include *Edit Artifact Metadata* and *Download*. Also displays artifact *Content Rules* that you can enable and configure.

** *Documentation* (OpenAPI and WSDL only): Displays automatically-generated REST or Web Service API documentation.
** *Content*: Displays a read-only view of the full artifact content. 

. Select to view a different artifact *Version* from the drop-down, if additional versions have been added.

.Additional resources

* xref:adding-artifacts-using-console[]
* xref:configuring-rules-using-console[]
