// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts.adoc

[id="adding-artifacts-using-console"]
= Adding artifacts using the {registry} web console

You can use the {registry} web console to upload event schema and API design artifacts to the registry. For more details on the artifacts types that you can upload, see xref:registry-artifact-types[]. This section shows simple examples of uploading {registry} artifacts, applying artifact rules, and adding new artifact versions.  

.Prerequisites

* {registry} must be installed and running in your environment. For details, see xref:installing-the-registry[].

.Procedure

. Connect to the {registry} web console on: 
+
`*\http://MY_REGISTRY_URL/ui*`

. Click *Upload Artifact*, and specify the following:
** *ID*: Use the default empty setting to automatically generate an ID, or enter a specific artifact ID.
** *Type*: Use the default *Auto-Detect* setting to automatically detect the artifact type, or select the artifact type from the drop-down, for example, *Avro Schema* or *OpenAPI*. 
** *Artifact*: Drag and drop or click *Browse* to upload a file, for example, `my-schema.json` or `my-openapi.json`.

. Click *Upload* and view the *Artifact Details*:

** *Info*: Displays artifact metadata including name, description, status, created, and modified. Artifact actions include *Edit Artifact Metadata* and *Download*. Also displays artifact *Content Rules* that you can enable and configure.

** *Documentation* (OpenAPI and WSDL only): Displays automatically-generated REST or Web Service API documentation.
** *Content*: Displays a read-only view of the full artifact content. 

. In *Content Rules*, click *Enable* to configure a *Validity Rule* or *Compatibility Rule*, and select the appropriate rule configuration from the drop-down. For more details, see xref:registry-rule-types[].

. Click *Upload new version* to add a new artifact version, and drag and drop or click *Browse* to upload the file, for example, `my-schema.json` or `my-openapi.json`. 

. To delete an artifact, click the trash icon next to *Upload new version*. 
+
WARNING: Deleting an artifact deletes the artifact and all of its versions, and cannot be undone.  

.Additional resources
* xref:browsing-artifacts-using-console[]
* xref:configuring-rules-using-console[]
