// Metadata created by nebel
//
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="installing-registry-operatorhub"]
= Installing {registry} from the OpenShift OperatorHub
// Start the title of a procedure module with a verb, such as Creating or Create. See also _Wording of headings_ in _The IBM Style Guide_.

You can install the {registry} Operator on your OpenShift cluster from the OperatorHub. The OperatorHub is available from the OpenShift Container Platform web console and provides an interface for cluster administrators to discover and install Operators. For more details, see the https://docs.openshift.com/container-platform/4.3/operators/olm-understanding-operatorhub.html[OpenShift documentation].

.Prerequisites

* You must have cluster administrator access to an OpenShift cluster.

.Procedure

. In the OpenShift Container Platform web console, log in using an account with cluster administrator privileges.

. Create a new OpenShift project:

.. In the left navigation menu, click *Home* > *Project* > *Create Project*.
.. Enter a project name, for example, `my-project`, and click *Create*.

. In the left navigation menu, click *Catalog* > *OperatorHub*.
ifdef::apicurio-registry[]
. In the *Filter by keyword* text box, enter `Registry` to find the *{registry} Operator*.
endif::[]
ifdef::rh-service-registry[]
. In the *Filter by keyword* text box, enter `Registry` to find the *Red Hat Integration - {registry} Operator*.
endif::[]
. Read the information about the Operator, and click *Install*. This displays the *Create Operator Subscription* page.

. Select your subscription settings, for example:
** *Installation Mode* > *A specific namespace on the cluster* > *my-project*
ifdef::rh-service-registry[]
** *Update Channel* > *serviceregistry-1.0*
endif::[]
ifdef::apicurio-registry[]
** *Update Channel* > *alpha*
endif::[]
** *Approval Strategy* > *Manual*

. Click *Subscribe*. This displays the *Operators* > *Installed Operators* page.

. Wait a few moments until the *Status* for the {registry} Operator displays *Succeeded* and the subscription is *Up to Date*. 


.Additional resources
* link:https://docs.openshift.com/container-platform/{registry-ocp-version}/operators/olm-adding-operators-to-cluster.html[Adding Operators to an OpenShift cluster]
* link:https://github.com/Apicurio/apicurio-registry-operator[Apicurio Registry Operator community in GitHub]
