apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: example-apicurioregistry-mem
spec:
  app:
    # No storage configuration required for in-memory (default)
    ingress:
      host: example-mem-app.apps.cluster.example
  ui:
    ingress:
      host: example-mem-ui.apps.cluster.example
