apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: example-apicurioregistry-sql
spec:
  app:
    storage:
      type: postgresql
      sql:
        dataSource:
          url: "jdbc:postgresql://<service name>.<namespace>.svc:5432/<database name>"
          username: "postgres"
          password:
            name: postgresql-credentials
            key: password
    ingress:
      host: example-sql-app.apps.cluster.example
  ui:
    ingress:
      host: example-sql-ui.apps.cluster.example
