{
 "title": "Apicurio Registry Metrics",
 "description": "Apicurio Registry Grafana Dashboard",
 "tags": [
  "quarkus",
  "microprofile",
  "jvm",
  "java"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_uptime_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{instance=\"localhost:8080\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem",
   "type": "gauge",
   "description": "Used / max heap memory",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})*100/sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "REST API",
   "type": "stat",
   "description": "REST API/HTTP stats in selected time range.\n\nResponse time displayed here is measured inside JVM, it is not full end to end latency the users see, which can be few times bigger.",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(rest_requests_seconds_count{instance=\"$instance\"}[$__range])))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(increase(rest_requests_seconds_sum{instance=\"$instance\"}[$__range])) / sum(increase(rest_requests_seconds_count{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Database",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agroal_active_count{instance=\"$instance\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(agroal_available_count{instance=\"$instance\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(agroal_max_used_count{instance=\"$instance\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(agroal_leak_detection_count_total{instance=\"$instance\"})",
     "legendFormat": "Leaks"
    },
    {
     "expr": "sum(round(increase(agroal_acquire_count_total{instance=\"$instance\"}[$__range])))",
     "legendFormat": "Acquire count"
    }
   ]
  },
  { "title": "REST API - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests per second",
   "type": "graph",
   "description": "Requests per second as measured (averaged) over the last minute",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_requests_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Server Response Time",
   "type": "graph",
   "description": "Server Response Time (averaged over 1m)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_requests_seconds_sum{instance=\"$instance\"}[1m])) / sum(rate(rest_requests_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Http errors (400s & 500s) [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(rest_requests_seconds_count{status_code_group=\"4xx\"}[1m])))",
     "legendFormat": "HTTP 4xx"
    },
    {
     "expr": "sum(round(increase(rest_requests_seconds_count{status_code_group=\"5xx\"}[1m])))",
     "legendFormat": "HTTP 5xx"
    }
   ]
  },
  { "title": "REST API - Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Requests per minute",
   "type": "graph",
   "description": "HTTP avg requests/minute for all instances in a cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rest_requests_seconds_count{instance=\"$instance\"}[1m])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Avg server response times",
   "type": "graph",
   "description": "HTTP average response times over last [1m] for all instances in a cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(rest_requests_seconds_sum{}[1m]) / increase(rest_requests_seconds_count{}[1m]) > 0) by (method, path)",
     "legendFormat": "Average {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Http errors (400s & 500s) [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(rest_requests_seconds_count{status_code_group=\"4xx\"}[1m]))) by (path, method)",
     "legendFormat": "HTTP 4xx {{method}} {{path}}"
    },
    {
     "expr": "sum(round(increase(rest_requests_seconds_count{status_code_group=\"5xx\"}[1m]))) by (path, method)",
     "legendFormat": "HTTP 5xx {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Endpoint utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rest_requests_seconds_count{instance=\"$instance\"}[1d])) by (path)",
     "legendFormat": "Path {{path}}:"
    }
   ]
  },
  { "title": "Storage - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Storage ops per second",
   "type": "graph",
   "description": "Requests per second as measured (averaged) over the last minute",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_method_call_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Storage Response Time",
   "type": "graph",
   "description": "Storage Response Time (averaged over 1m)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storage_method_call_seconds_sum{instance=\"$instance\"}[1m])) / sum(rate(storage_method_call_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Storage Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(round(increase(storage_method_call_seconds_count{instance=\"$instance\",success=\"false\"}[1m])))",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Storage - Methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Storage ops per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(storage_method_call_seconds_count{instance=\"$instance\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Avg storage response times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(storage_method_call_seconds_sum{}[1m]) / increase(storage_method_call_seconds_count{}[1m]) > 0) by (method)",
     "legendFormat": "Average {{method}}"
    }
   ]
  },
  { "title": "Hardware utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Displays  the \"recent cpu usage\" for the Java Virtual Machine process. This value is a double in the [0.0,1.0] interval. A value of 0.0 means that none of the CPUs were running threads from the JVM process during the recent period of time observed, while a value of 1.0 means that all CPUs were actively running threads from the JVM 100% of the time during the recent period being observed. Threads from the JVM include the application threads as well as the JVM internal threads. All values betweens 0.0 and 1.0 are possible depending of the activities going on in the JVM process and the whole system. If the Java Virtual Machine recent CPU usage is not available, the method returns a negative value.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(process_cpu_usage{instance=\"$instance\"})",
     "legendFormat": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM"
    },
    {
     "expr": "sum(avg_over_time(process_cpu_usage{instance=\"$instance\"}[1h]))",
     "legendFormat": "Usage for the JVM process - last hour average"
    },
    {
     "expr": "sum(system_cpu_usage{instance=\"$instance\"})",
     "legendFormat": "Usage for the whole system. 100% means that all CPUs were actively running 100% of the time"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platforms where it is expensive to implement this method.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_load_average_1m{instance=\"$instance\"})",
     "legendFormat": "System load average for the last minute"
    },
    {
     "expr": "sum(system_cpu_count{instance=\"$instance\"})",
     "legendFormat": "Number of processors available to the JVM"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}-jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "Live threads"
    },
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "Live daemon threads"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "Live threads total"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$instance\"})",
     "legendFormat": "Container working set"
    },
    {
     "expr": "sum(base_memory_maxHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "sum(vendor_memory_freeSwapSize_bytes{pod=\"$instance\"})",
     "legendFormat": "Free swap space"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$instance\"})",
     "legendFormat": "Container limit"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Heap",
   "type": "graph",
   "description": "Java objects reside in an area called the heap. The heap is created when the JVM starts up and may increase or decrease in size while the application runs. When the heap becomes full, garbage is collected. During the garbage collection objects that are no longer used are cleared, thus making space for new objects.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",instance=\"$instance\"})",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\",instance=\"$instance\"})",
     "legendFormat": "Memory committed (guaranteed) for the JVM to use"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\",instance=\"$instance\"})",
     "legendFormat": "Maximum amount (not guaranteed) of heap memory that can be used for memory management"
    }
   ]
  },
  {
   "title": "Heap Memory Pools",
   "type": "graph",
   "description": "Memory Pools are created by JVM memory managers to create a pool of immutable objects. Memory Pool can belong to Heap or Perm Gen, depending on JVM memory manager implementation.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 53 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (id) (jvm_memory_used_bytes{area=\"heap\",instance=\"$instance\"})",
     "legendFormat": "Usage {{id}}"
    },
    {
     "expr": "sum by (id) (jvm_memory_max_bytes{area=\"heap\",instance=\"$instance\"} > 0)",
     "legendFormat": "Max {{id}}"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "graph",
   "description": "The JVM has memory other than the heap, referred to as Non-Heap Memory. It is created at the JVM startup and stores per-class structures such as runtime constant pool, field and method data, and the code for methods and constructors, as well as interned Strings. The default maximum size of non-heap memory is 64 MB.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\", instance=\"$instance\"})",
     "legendFormat": "Used non-heap memory"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\", instance=\"$instance\"})",
     "legendFormat": "Non heap memory committed (guaranteed) for the JVM to use"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\", instance=\"$instance\"})",
     "legendFormat": "Maximum amount of used non-heap memory"
    }
   ]
  },
  {
   "title": "Class Loader",
   "type": "graph",
   "description": "Class loaders are responsible for loading Java classes during runtime dynamically to the JVM (Java Virtual Machine). Also, they are part of the JRE (Java Runtime Environment). Hence, the JVM doesn't need to know about the underlying files or file systems in order to run Java programs thanks to class loaders.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_classes_loaded_classes{instance=\"$instance\"})",
     "legendFormat": "Classes currently loaded in the JVM"
    },
    {
     "expr": "sum(delta(jvm_classes_loaded_classes{instance=\"$instance\"}[1m]))",
     "legendFormat": "Classes currently loaded in the JVM - delta 1m"
    }
   ]
  },
  { "title": "Datasource (Agroal)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Connection pool over last [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(agroal_destroy_count_total{instance=\"$instance\"}[1m]))",
     "legendFormat": "Destroyed connections last minute"
    },
    {
     "expr": "sum(rate(agroal_invalid_count_total{instance=\"$instance\"}[1m]))",
     "legendFormat": "Connections removed from the pool for being invalid [1m]"
    },
    {
     "expr": "sum(agroal_available_count{instance=\"$instance\"})",
     "legendFormat": "Idle connections, available to be acquired"
    },
    {
     "expr": "sum(agroal_active_count{instance=\"$instance\"})",
     "legendFormat": "Active connections"
    },
    {
     "expr": "sum(increase(agroal_leak_detection_count_total{instance=\"$instance\"}[1m]))",
     "legendFormat": "Leak detections"
    },
    {
     "expr": "sum(increase(agroal_creation_count_total{instance=\"$instance\"}[1m]))",
     "legendFormat": "Created connections in the last minute"
    },
    {
     "expr": "sum(agroal_max_used_count{instance=\"$instance\"})",
     "legendFormat": "Maximum number of connections active simultaneously"
    },
    {
     "expr": "sum(rate(agroal_acquire_count_total{instance=\"$instance\"}[1m]))",
     "legendFormat": "Acquire operation per second"
    }
   ]
  },
  {
   "title": "Timing over last [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agroal_creation_time_total_milliseconds{instance=\"$instance\"}[1m]))",
     "legendFormat": "Time to create a connection"
    },
    {
     "expr": "sum(rate(agroal_blocking_time_total_milliseconds{instance=\"$instance\"}[1m]))",
     "legendFormat": "Time to acquire a connection"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Collections over last [1m]",
   "type": "graph",
   "description": "JVM garbage collectors summary:\nhttps://www.baeldung.com/jvm-garbage-collectors",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(jvm_gc_pause_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Number of collections that have occurred last minute ({{name}})"
    }
   ]
  },
  {
   "title": "Durations over last [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (cause) (increase(jvm_gc_pause_seconds_sum{instance=\"$instance\"}[1m]))",
     "legendFormat": "Approximate accumulated collection elapsed time ({{cause}})"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "{pod=\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}