-- H2 2.2.224; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '2ff99bc3a0ae4f76' HASH '3398cf73b7242d893c56e3c7617e8e205bb00834cfe6ca71e9934d8890c77ca7' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."APICURIO"(
    "PROPNAME" CHARACTER VARYING(255) NOT NULL,
    "PROPVALUE" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."APICURIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("PROPNAME");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.APICURIO; 
INSERT INTO "PUBLIC"."APICURIO" VALUES
('db_version', '100');  
CREATE MEMORY TABLE "PUBLIC"."SEQUENCES"(
    "SEQNAME" CHARACTER VARYING(32) NOT NULL,
    "SEQVALUE" BIGINT NOT NULL
);      
ALTER TABLE "PUBLIC"."SEQUENCES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_63" PRIMARY KEY("SEQNAME");               
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.SEQUENCES;
INSERT INTO "PUBLIC"."SEQUENCES" VALUES
('contentId', 265),
('globalId', 395),
('commentId', 3);               
CREATE MEMORY TABLE "PUBLIC"."CONFIG"(
    "PROPNAME" CHARACTER VARYING(255) NOT NULL,
    "PROPVALUE" CHARACTER VARYING(1024) NOT NULL,
    "MODIFIEDON" BIGINT NOT NULL
);   
ALTER TABLE "PUBLIC"."CONFIG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("PROPNAME");  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CONFIG;   
INSERT INTO "PUBLIC"."CONFIG" VALUES
('apicurio.storage.read-only.enabled', 'false', 1715687568633);           
CREATE INDEX "PUBLIC"."IDX_CONFIG_1" ON "PUBLIC"."CONFIG"("MODIFIEDON" NULLS FIRST);           
CREATE MEMORY TABLE "PUBLIC"."ACLS"(
    "PRINCIPALID" CHARACTER VARYING(256) NOT NULL,
    "ROLE" CHARACTER VARYING(32) NOT NULL,
    "PRINCIPALNAME" CHARACTER VARYING(256)
);               
ALTER TABLE "PUBLIC"."ACLS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("PRINCIPALID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACLS;     
CREATE MEMORY TABLE "PUBLIC"."DOWNLOADS"(
    "DOWNLOADID" CHARACTER VARYING(128) NOT NULL,
    "EXPIRES" BIGINT NOT NULL,
    "CONTEXT" CHARACTER VARYING(1024)
);            
ALTER TABLE "PUBLIC"."DOWNLOADS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("DOWNLOADID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOWNLOADS;
CREATE HASH INDEX "PUBLIC"."IDX_DOWN_1" ON "PUBLIC"."DOWNLOADS"("EXPIRES" NULLS FIRST);        
CREATE MEMORY TABLE "PUBLIC"."GLOBAL_RULES"(
    "TYPE" CHARACTER VARYING(32) NOT NULL,
    "CONFIGURATION" CHARACTER VARYING NOT NULL
);      
ALTER TABLE "PUBLIC"."GLOBAL_RULES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("TYPE");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GLOBAL_RULES;             
CREATE MEMORY TABLE "PUBLIC"."CONTENT"(
    "CONTENTID" BIGINT NOT NULL,
    "CANONICALHASH" CHARACTER VARYING(64) NOT NULL,
    "CONTENTHASH" CHARACTER VARYING(64) NOT NULL,
    "CONTENT" BINARY VARYING NOT NULL,
    "REFS" CHARACTER VARYING
);          
ALTER TABLE "PUBLIC"."CONTENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_638" PRIMARY KEY("CONTENTID");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CONTENT;  
CREATE HASH INDEX "PUBLIC"."IDX_CONTENT_1" ON "PUBLIC"."CONTENT"("CANONICALHASH" NULLS FIRST); 
CREATE HASH INDEX "PUBLIC"."IDX_CONTENT_2" ON "PUBLIC"."CONTENT"("CONTENTHASH" NULLS FIRST);   
CREATE MEMORY TABLE "PUBLIC"."CONTENT_REFERENCES"(
    "CONTENTID" BIGINT NOT NULL,
    "GROUPID" CHARACTER VARYING(512),
    "ARTIFACTID" CHARACTER VARYING(512) NOT NULL,
    "VERSION" CHARACTER VARYING(256),
    "NAME" CHARACTER VARYING(512) NOT NULL
);
ALTER TABLE "PUBLIC"."CONTENT_REFERENCES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("CONTENTID", "NAME");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CONTENT_REFERENCES;       
CREATE MEMORY TABLE "PUBLIC"."GROUPS"(
    "GROUPID" CHARACTER VARYING(512) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(1024),
    "ARTIFACTSTYPE" CHARACTER VARYING(32),
    "OWNER" CHARACTER VARYING(256),
    "CREATEDON" TIMESTAMP NOT NULL,
    "MODIFIEDBY" CHARACTER VARYING(256),
    "MODIFIEDON" TIMESTAMP,
    "LABELS" CHARACTER VARYING
);     
ALTER TABLE "PUBLIC"."GROUPS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7D" PRIMARY KEY("GROUPID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC."GROUPS"; 
CREATE MEMORY TABLE "PUBLIC"."GROUP_LABELS"(
    "GROUPID" CHARACTER VARYING(512) NOT NULL,
    "LABELKEY" CHARACTER VARYING(256) NOT NULL,
    "LABELVALUE" CHARACTER VARYING(512)
);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GROUP_LABELS;             
CREATE INDEX "PUBLIC"."IDX_GLABELS_1" ON "PUBLIC"."GROUP_LABELS"("LABELKEY" NULLS FIRST);      
CREATE INDEX "PUBLIC"."IDX_GLABELS_2" ON "PUBLIC"."GROUP_LABELS"("LABELVALUE" NULLS FIRST);    
CREATE MEMORY TABLE "PUBLIC"."GROUP_RULES"(
    "GROUPID" CHARACTER VARYING(512) NOT NULL,
    "TYPE" CHARACTER VARYING(32) NOT NULL,
    "CONFIGURATION" CHARACTER VARYING(1024) NOT NULL
);  
ALTER TABLE "PUBLIC"."GROUP_RULES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F8" PRIMARY KEY("GROUPID", "TYPE");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GROUP_RULES;              
CREATE MEMORY TABLE "PUBLIC"."ARTIFACTS"(
    "GROUPID" CHARACTER VARYING(512) NOT NULL,
    "ARTIFACTID" CHARACTER VARYING(512) NOT NULL,
    "TYPE" CHARACTER VARYING(32) NOT NULL,
    "OWNER" CHARACTER VARYING(256),
    "CREATEDON" TIMESTAMP NOT NULL,
    "MODIFIEDBY" CHARACTER VARYING(256),
    "MODIFIEDON" TIMESTAMP,
    "NAME" CHARACTER VARYING(512),
    "DESCRIPTION" CHARACTER VARYING(1024),
    "LABELS" CHARACTER VARYING
);             
ALTER TABLE "PUBLIC"."ARTIFACTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("GROUPID", "ARTIFACTID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ARTIFACTS;
CREATE HASH INDEX "PUBLIC"."IDX_ARTIFACTS_0" ON "PUBLIC"."ARTIFACTS"("TYPE" NULLS FIRST);      
CREATE HASH INDEX "PUBLIC"."IDX_ARTIFACTS_1" ON "PUBLIC"."ARTIFACTS"("OWNER" NULLS FIRST);     
CREATE INDEX "PUBLIC"."IDX_ARTIFACTS_2" ON "PUBLIC"."ARTIFACTS"("CREATEDON" NULLS FIRST);      
CREATE INDEX "PUBLIC"."IDX_ARTIFACTS_3" ON "PUBLIC"."ARTIFACTS"("NAME" NULLS FIRST);           
CREATE INDEX "PUBLIC"."IDX_ARTIFACTS_4" ON "PUBLIC"."ARTIFACTS"("DESCRIPTION" NULLS FIRST);    
CREATE MEMORY TABLE "PUBLIC"."ARTIFACT_LABELS"(
    "GROUPID" CHARACTER VARYING(512) NOT NULL,
    "ARTIFACTID" CHARACTER VARYING(512) NOT NULL,
    "LABELKEY" CHARACTER VARYING(256) NOT NULL,
    "LABELVALUE" CHARACTER VARYING(512)
);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ARTIFACT_LABELS;          
CREATE INDEX "PUBLIC"."IDX_ALABELS_1" ON "PUBLIC"."ARTIFACT_LABELS"("LABELKEY" NULLS FIRST);   
CREATE INDEX "PUBLIC"."IDX_ALABELS_2" ON "PUBLIC"."ARTIFACT_LABELS"("LABELVALUE" NULLS FIRST); 
CREATE MEMORY TABLE "PUBLIC"."ARTIFACT_RULES"(
    "GROUPID" CHARACTER VARYING(512) NOT NULL,
    "ARTIFACTID" CHARACTER VARYING(512) NOT NULL,
    "TYPE" CHARACTER VARYING(32) NOT NULL,
    "CONFIGURATION" CHARACTER VARYING(1024) NOT NULL
);             
ALTER TABLE "PUBLIC"."ARTIFACT_RULES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5E" PRIMARY KEY("GROUPID", "ARTIFACTID", "TYPE");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ARTIFACT_RULES;           
CREATE MEMORY TABLE "PUBLIC"."VERSIONS"(
    "GLOBALID" BIGINT NOT NULL,
    "GROUPID" CHARACTER VARYING(512) NOT NULL,
    "ARTIFACTID" CHARACTER VARYING(512) NOT NULL,
    "VERSION" CHARACTER VARYING(256),
    "VERSIONORDER" INTEGER NOT NULL,
    "STATE" CHARACTER VARYING(64) NOT NULL,
    "NAME" CHARACTER VARYING(512),
    "DESCRIPTION" CHARACTER VARYING(1024),
    "OWNER" CHARACTER VARYING(256),
    "CREATEDON" TIMESTAMP NOT NULL,
    "LABELS" CHARACTER VARYING,
    "CONTENTID" BIGINT NOT NULL
);      
ALTER TABLE "PUBLIC"."VERSIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("GLOBALID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VERSIONS; 
CREATE INDEX "PUBLIC"."IDX_VERSIONS_1" ON "PUBLIC"."VERSIONS"("VERSION" NULLS FIRST);          
CREATE HASH INDEX "PUBLIC"."IDX_VERSIONS_2" ON "PUBLIC"."VERSIONS"("STATE" NULLS FIRST);       
CREATE INDEX "PUBLIC"."IDX_VERSIONS_3" ON "PUBLIC"."VERSIONS"("NAME" NULLS FIRST);             
CREATE INDEX "PUBLIC"."IDX_VERSIONS_4" ON "PUBLIC"."VERSIONS"("DESCRIPTION" NULLS FIRST);      
CREATE HASH INDEX "PUBLIC"."IDX_VERSIONS_5" ON "PUBLIC"."VERSIONS"("OWNER" NULLS FIRST);       
CREATE INDEX "PUBLIC"."IDX_VERSIONS_6" ON "PUBLIC"."VERSIONS"("CREATEDON" NULLS FIRST);        
CREATE HASH INDEX "PUBLIC"."IDX_VERSIONS_7" ON "PUBLIC"."VERSIONS"("CONTENTID" NULLS FIRST);   
CREATE MEMORY TABLE "PUBLIC"."VERSION_LABELS"(
    "GLOBALID" BIGINT NOT NULL,
    "LABELKEY" CHARACTER VARYING(256) NOT NULL,
    "LABELVALUE" CHARACTER VARYING(512)
);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VERSION_LABELS;           
CREATE INDEX "PUBLIC"."IDX_VLABELS_1" ON "PUBLIC"."VERSION_LABELS"("LABELKEY" NULLS FIRST);    
CREATE INDEX "PUBLIC"."IDX_VLABELS_2" ON "PUBLIC"."VERSION_LABELS"("LABELVALUE" NULLS FIRST);  
CREATE MEMORY TABLE "PUBLIC"."VERSION_COMMENTS"(
    "COMMENTID" CHARACTER VARYING(128) NOT NULL,
    "GLOBALID" BIGINT NOT NULL,
    "OWNER" CHARACTER VARYING(256),
    "CREATEDON" TIMESTAMP NOT NULL,
    "CVALUE" CHARACTER VARYING(1024) NOT NULL
);     
ALTER TABLE "PUBLIC"."VERSION_COMMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("COMMENTID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.VERSION_COMMENTS;         
CREATE INDEX "PUBLIC"."IDX_VERSION_COMMENTS_1" ON "PUBLIC"."VERSION_COMMENTS"("OWNER" NULLS FIRST);            
CREATE MEMORY TABLE "PUBLIC"."ARTIFACT_BRANCHES"(
    "GROUPID" CHARACTER VARYING(512) NOT NULL,
    "ARTIFACTID" CHARACTER VARYING(512) NOT NULL,
    "BRANCHID" CHARACTER VARYING(256) NOT NULL,
    "BRANCHORDER" INTEGER NOT NULL,
    "VERSION" CHARACTER VARYING(256) NOT NULL
);        
ALTER TABLE "PUBLIC"."ARTIFACT_BRANCHES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1E" PRIMARY KEY("GROUPID", "ARTIFACTID", "BRANCHID", "BRANCHORDER");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ARTIFACT_BRANCHES;        
CREATE INDEX "PUBLIC"."IDX_ARTIFACT_BRANCHES_1" ON "PUBLIC"."ARTIFACT_BRANCHES"("GROUPID" NULLS FIRST, "ARTIFACTID" NULLS FIRST, "BRANCHID" NULLS FIRST, "BRANCHORDER" NULLS FIRST);           
ALTER TABLE "PUBLIC"."CONTENT" ADD CONSTRAINT "PUBLIC"."UQ_CONTENT_1" UNIQUE("CONTENTHASH");   
ALTER TABLE "PUBLIC"."VERSIONS" ADD CONSTRAINT "PUBLIC"."UQ_VERSIONS_1" UNIQUE("GROUPID", "ARTIFACTID", "VERSION");            
ALTER TABLE "PUBLIC"."VERSIONS" ADD CONSTRAINT "PUBLIC"."UQ_VERSIONS_2" UNIQUE("GLOBALID", "VERSIONORDER");    
ALTER TABLE "PUBLIC"."CONTENT_REFERENCES" ADD CONSTRAINT "PUBLIC"."FK_CONTENT_REFERENCES_1" FOREIGN KEY("CONTENTID") REFERENCES "PUBLIC"."CONTENT"("CONTENTID") ON DELETE CASCADE NOCHECK;     
ALTER TABLE "PUBLIC"."ARTIFACT_BRANCHES" ADD CONSTRAINT "PUBLIC"."FK_ARTIFACT_BRANCHES_1" FOREIGN KEY("GROUPID", "ARTIFACTID") REFERENCES "PUBLIC"."ARTIFACTS"("GROUPID", "ARTIFACTID") ON DELETE CASCADE NOCHECK;             
ALTER TABLE "PUBLIC"."VERSION_COMMENTS" ADD CONSTRAINT "PUBLIC"."FK_VERSION_COMMENTS_1" FOREIGN KEY("GLOBALID") REFERENCES "PUBLIC"."VERSIONS"("GLOBALID") ON DELETE CASCADE NOCHECK;          
ALTER TABLE "PUBLIC"."ARTIFACT_BRANCHES" ADD CONSTRAINT "PUBLIC"."FK_ARTIFACT_BRANCHES_2" FOREIGN KEY("GROUPID", "ARTIFACTID", "VERSION") REFERENCES "PUBLIC"."VERSIONS"("GROUPID", "ARTIFACTID", "VERSION") ON DELETE CASCADE NOCHECK;        
ALTER TABLE "PUBLIC"."GROUP_LABELS" ADD CONSTRAINT "PUBLIC"."FK_GLABELS_1" FOREIGN KEY("GROUPID") REFERENCES "PUBLIC"."GROUPS"("GROUPID") ON DELETE CASCADE NOCHECK;           
ALTER TABLE "PUBLIC"."GROUP_RULES" ADD CONSTRAINT "PUBLIC"."FK_GRULES_1" FOREIGN KEY("GROUPID") REFERENCES "PUBLIC"."GROUPS"("GROUPID") ON DELETE CASCADE NOCHECK;             
ALTER TABLE "PUBLIC"."ARTIFACT_LABELS" ADD CONSTRAINT "PUBLIC"."FK_ALABELS_1" FOREIGN KEY("GROUPID", "ARTIFACTID") REFERENCES "PUBLIC"."ARTIFACTS"("GROUPID", "ARTIFACTID") ON DELETE CASCADE NOCHECK;         
ALTER TABLE "PUBLIC"."VERSIONS" ADD CONSTRAINT "PUBLIC"."FK_VERSIONS_1" FOREIGN KEY("GROUPID", "ARTIFACTID") REFERENCES "PUBLIC"."ARTIFACTS"("GROUPID", "ARTIFACTID") ON DELETE CASCADE NOCHECK;               
ALTER TABLE "PUBLIC"."VERSIONS" ADD CONSTRAINT "PUBLIC"."FK_VERSIONS_2" FOREIGN KEY("CONTENTID") REFERENCES "PUBLIC"."CONTENT"("CONTENTID") NOCHECK;           
ALTER TABLE "PUBLIC"."VERSION_LABELS" ADD CONSTRAINT "PUBLIC"."FK_VLABELS_1" FOREIGN KEY("GLOBALID") REFERENCES "PUBLIC"."VERSIONS"("GLOBALID") ON DELETE CASCADE NOCHECK;     
