FROM registry.access.redhat.com/ubi8/ubi-minimal

ENV APP_PATH=app/target/apicurio-registry-app-*-runner

WORKDIR /work/

COPY ${APP_PATH} /work/application

RUN chmod 775 /work

EXPOSE 8080

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
