FROM registry.access.redhat.com/ubi10/openjdk-21-runtime@sha256:2056c5139666c5e52f01af5b80f0def423a94c3fe824321d74041c11e20c9b72

ENV APP_URL="${docker.app.file}" \
    JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ADD "$APP_URL" /deployments

USER root

# Set appropriate permissions and ownership
RUN chmod -R "ug=rwx" /deployments \
    && chown -R 1001:0 /deployments

# Set user for running the container, according to OpenShift best practices
USER 1001

EXPOSE 8080 8443 9000
