FROM registry.access.redhat.com/ubi8/openjdk-11:latest

ENV APP_URL="${docker.kafkasql.file}"
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV AB_ENABLED=jmx_exporter
ENV JAVA_APP_DIR=/deployments

EXPOSE 8080 8778 9779

USER 185

ADD "$APP_URL" /deployments/
