FROM registry.access.redhat.com/ubi10/openjdk-21-runtime@sha256:b55a353cc6b3c2ad1ba0d78a036bb820dbf6a138f45d11c38d6f0a30bd9e1fb9

ENV APP_URL="${docker.app.file}" \
    JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ADD "$APP_URL" /deployments

USER root

# Set appropriate permissions and ownership
RUN chmod -R "ug=rwx" /deployments \
    && chown -R 1001:0 /deployments

# Set user for running the container, according to OpenShift best practices
USER 1001

EXPOSE 8080 8443 9000
