apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: example-apicurioregistry-keycloak
spec:
  app:
    auth:
      enabled: true
      appClientId: registry-client-api
      uiClientId: registry-client-ui
      authServerUrl: "http://keycloak-http-<namespace>.apps.<cluster host>/realms/registry"
      # ^ Required. Use an HTTP URL in development.
      redirectUri: "http://example-mem-ui.apps.cluster.example"
      logoutUrl: "http://example-mem-ui.apps.cluster.example"
    ingress:
      host: example-mem-app.apps.cluster.example
  ui:
    ingress:
      host: example-mem-ui.apps.cluster.example
