package io.apicurio.registry.operator.rbac;

import io.fabric8.kubernetes.api.model.rbac.ClusterRole;
import io.fabric8.kubernetes.api.model.rbac.PolicyRule;
import io.fabric8.kubernetes.api.model.rbac.Role;
import io.fabric8.kubernetes.client.utils.Serialization;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Guards the least-privilege tier split that becomes the CSV's {@code clusterPermissions} and
 * {@code permissions}.
 * <p>
 * The bundle is generated by {@code kubectl kustomize controller/src/main/deploy/csv | operator-sdk
 * generate bundle} (see operator/Makefile {@code bundle-build}). operator-sdk maps the ClusterRole in
 * {@code rbac/namespaced/cluster-role.yaml} verbatim into the CSV {@code clusterPermissions}
 * (cluster-scoped) and the Role in {@code role.yaml} verbatim into {@code permissions}
 * (namespace-scoped workloads), each bound to the operator ServiceAccount. So the generated split is
 * a direct function of which file each rule lives in, and can be guarded at the source without
 * invoking operator-sdk.
 * <p>
 * {@link RbacInstallerSyncTest} checks the two files stay a subset of the OLM v1 installer role. This
 * test is the complementary guard: it checks they stay correctly <em>partitioned</em>, so a future
 * refactor cannot silently collapse the split by moving a workload rule up into the cluster tier
 * (which OLM would then grant cluster-wide in every install mode, including SingleNamespace) or a
 * cluster-scoped discovery rule down.
 */
class RbacSplitTest {

    private static final Path NAMESPACED_CLUSTER_ROLE = Path
            .of("src/main/deploy/rbac/namespaced/cluster-role.yaml");
    private static final Path NAMESPACED_ROLE = Path.of("src/main/deploy/rbac/namespaced/role.yaml");

    private static final String CR_GROUP = "registry.apicur.io";
    private static final String CR_RESOURCE = "apicurioregistries3";
    private static final String CRD_GROUP = "apiextensions.k8s.io";

    /**
     * The cluster tier (-> {@code clusterPermissions}) must stay read-only CR/CRD discovery only: no
     * mutating verbs and nothing beyond the CR and its CRD. Anything else here would be granted
     * cluster-wide in every install mode.
     */
    @Test
    void clusterTierIsReadOnlyCrAndCrdDiscoveryOnly() throws IOException {
        List<PolicyRule> rules = loadClusterRoleRules(NAMESPACED_CLUSTER_ROLE);
        assertThat(rules).isNotEmpty();
        for (PolicyRule rule : rules) {
            assertThat(groupsOf(rule)).withFailMessage(
                    "cluster-role.yaml (-> clusterPermissions) must only touch the CR and its CRD, but a rule "
                            + "targets apiGroups %s. Workload permissions belong in role.yaml.",
                    rule.getApiGroups()).isSubsetOf(CR_GROUP, CRD_GROUP);
            assertThat(rule.getVerbs()).withFailMessage(
                    "cluster-role.yaml (-> clusterPermissions) must stay read-only (get/list/watch), but a rule "
                            + "grants %s. Mutating verbs belong in the namespace-scoped role.yaml.",
                    rule.getVerbs()).isSubsetOf("get", "list", "watch");
        }
    }

    /**
     * The namespace tier (-> {@code permissions}) is where workloads live. It must contain the
     * workload verbs (asserted via {@code apps/deployments/create} as a marker) and the CR mutation
     * verbs ({@code patch}/{@code update} on the CR and its {@code /status}), and must never contain
     * cluster-scoped CRD access or the cluster-scoped CR discovery ({@code list}/{@code watch} on the
     * CR), which belong to the informer in the cluster tier.
     */
    @Test
    void namespaceTierHoldsWorkloadsAndNoClusterScopedDiscovery() throws IOException {
        List<PolicyRule> rules = loadRoleRules(NAMESPACED_ROLE);

        assertThat(tuples(rules)).withFailMessage(
                "role.yaml (-> permissions) must grant workload access such as creating Deployments.")
                .contains("apps/deployments/create");

        // Positive guard for the CR mutation verbs. Without this, a refactor that removed them from
        // role.yaml entirely would still pass: the "no list/watch" check below only runs when a
        // CR-targeting rule exists, and RbacInstallerSyncTest is satisfied by a smaller operator set.
        assertThat(tuples(rules)).withFailMessage(
                "role.yaml (-> permissions) must grant the CR mutation verbs (patch/update on the CR and "
                        + "its /status), which the operator uses for spec migration, status, and the finalizer.")
                .contains(CR_GROUP + "/" + CR_RESOURCE + "/patch",
                        CR_GROUP + "/" + CR_RESOURCE + "/update",
                        CR_GROUP + "/" + CR_RESOURCE + "/status/patch",
                        CR_GROUP + "/" + CR_RESOURCE + "/status/update");

        for (PolicyRule rule : rules) {
            assertThat(groupsOf(rule)).withFailMessage(
                    "role.yaml (-> permissions) must not grant cluster-scoped CRD access; that belongs in "
                            + "cluster-role.yaml. Offending rule targets apiGroups %s.",
                    rule.getApiGroups()).doesNotContain(CRD_GROUP);

            boolean targetsCr = groupsOf(rule).contains(CR_GROUP) && rule.getResources().contains(CR_RESOURCE);
            if (targetsCr) {
                assertThat(rule.getVerbs()).withFailMessage(
                        "role.yaml (-> permissions) must not grant cluster-wide CR discovery (list/watch); the "
                                + "informer does that via cluster-role.yaml. Offending verbs: %s.",
                        rule.getVerbs()).doesNotContain("list", "watch");
            }
        }
    }

    private static List<String> groupsOf(PolicyRule rule) {
        return rule.getApiGroups().isEmpty() ? List.of("") : rule.getApiGroups();
    }

    private static Set<String> tuples(List<PolicyRule> rules) {
        Set<String> tuples = new LinkedHashSet<>();
        for (PolicyRule rule : rules) {
            for (String group : groupsOf(rule)) {
                for (String resource : rule.getResources()) {
                    for (String verb : rule.getVerbs()) {
                        tuples.add(group + "/" + resource + "/" + verb);
                    }
                }
            }
        }
        return tuples;
    }

    private static List<PolicyRule> loadClusterRoleRules(Path path) throws IOException {
        try (InputStream in = Files.newInputStream(path)) {
            return Serialization.unmarshal(in, ClusterRole.class).getRules();
        }
    }

    private static List<PolicyRule> loadRoleRules(Path path) throws IOException {
        try (InputStream in = Files.newInputStream(path)) {
            return Serialization.unmarshal(in, Role.class).getRules();
        }
    }
}
