quarkus.http.port=9443
quarkus.http.ssl.certificate.files=/var/serving-cert/tls.crt
quarkus.http.ssl.certificate.key-files=/var/serving-cert/tls.key
quarkus.http.insecure-requests=disabled

%dev.quarkus.http.port=9443
%dev.quarkus.http.insecure-requests=enabled
%dev.quarkus.http.ssl.certificate.files=
%dev.quarkus.http.ssl.certificate.key-files=

registry.api.url=${REGISTRY_API_URL:http://localhost:8080}
