FROM registry.access.redhat.com/ubi8/openjdk-11:latest

ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager" \
    AB_ENABLED=jmx_exporter

EXPOSE 8080

USER 185

COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
