FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest

USER 185

COPY --chown=185 target/quarkus-app/ /deployments/

EXPOSE 9443

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0"

ENTRYPOINT ["java", "-jar", "/deployments/quarkus-run.jar"]
