package io.apicurio.registry.operator.api.v1;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import io.apicurio.registry.operator.api.v1.spec.GitOpsMode;
import io.apicurio.registry.operator.api.v1.spec.InsecureRequests;
import io.apicurio.registry.operator.api.v1.spec.StorageType;
import io.apicurio.registry.operator.api.v1.spec.TLSTermination;
import io.apicurio.registry.operator.api.v1.status.ConditionStatus;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.SortedSet;
import java.util.TreeMap;
import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Checks that every value the generated CRD advertises is a value the operator can deserialize.
 * <p>
 * The CRD is generated from these model classes by {@code crd-generator-apt}. If its enums ever
 * listed the Java constant names instead of the values Jackson accepts, a CR that passes CRD
 * validation would fail to deserialize in the operator, which takes down the informer loop for
 * every ApicurioRegistry3 resource rather than failing that one reconcile.
 */
public class CrdEnumValuesTest {

    static final String CRD_RESOURCE = "/META-INF/fabric8/apicurioregistries3.registry.apicur.io-v1.yml";

    /**
     * Path suffix of the {@code app.storage.type} property within the CRD schema. Matched as a
     * suffix so the test survives a change to the CRD version index.
     */
    static final String STORAGE_TYPE_PATH_SUFFIX = ".properties.app.properties.storage.properties.type";

    /**
     * Every enum reachable from {@link ApicurioRegistry3}. A new one shows up as an unmatched CRD
     * enum in {@link #everyCrdEnumValueDeserializes()} until it is added here.
     */
    static final List<Class<? extends Enum<?>>> MODEL_ENUMS = List.of(StorageType.class,
            TLSTermination.class, GitOpsMode.class, InsecureRequests.class, ConditionStatus.class);

    static final ObjectMapper MAPPER = new ObjectMapper(new YAMLFactory());

    @Test
    public void storageTypeListsTheValuesStorageTypeAccepts() throws Exception {
        var sites = crdEnums().entrySet().stream()
                .filter(e -> e.getKey().endsWith(STORAGE_TYPE_PATH_SUFFIX)).toList();

        assertEquals(1, sites.size(), "expected exactly one app.storage.type enum in the CRD, found "
                + sites.stream().map(Map.Entry::getKey).toList());
        assertEquals(List.of("gitops", "kafkasql", "kubernetesops", "mysql", "postgresql"),
                sites.get(0).getValue().stream().sorted().toList(),
                "app.storage.type in the CRD must list the lowercase values StorageType deserializes");
    }

    @Test
    public void everyCrdEnumValueDeserializes() throws Exception {
        crdEnums().forEach((path, values) -> {
            var type = modelEnumFor(new TreeSet<>(values))
                    .orElseThrow(() -> new AssertionError("CRD enum at " + path + " is " + values
                            + ", which no model enum accepts. Known model enums: " + MODEL_ENUMS.stream()
                                    .map(known -> known.getSimpleName() + jacksonValues(known)).toList()));
            for (var value : values) {
                assertNotNull(MAPPER.convertValue(value, type),
                        value + " at " + path + " did not map to a " + type.getSimpleName());
            }
        });
    }

    static Optional<Class<? extends Enum<?>>> modelEnumFor(SortedSet<String> values) {
        return MODEL_ENUMS.stream().filter(type -> jacksonValues(type).equals(values)).findFirst();
    }

    static SortedSet<String> jacksonValues(Class<? extends Enum<?>> type) {
        var values = new TreeSet<String>();
        for (var constant : type.getEnumConstants()) {
            values.add(MAPPER.convertValue(constant, String.class));
        }
        return values;
    }

    /**
     * @return every {@code enum} list in the generated CRD, keyed by its dotted path within the
     *         document
     */
    static Map<String, List<String>> crdEnums() throws Exception {
        try (InputStream in = CrdEnumValuesTest.class.getResourceAsStream(CRD_RESOURCE)) {
            assertNotNull(in, CRD_RESOURCE + " is not on the test classpath. It is generated by "
                    + "crd-generator-apt while this module compiles.");
            Map<String, Object> crd = MAPPER.readValue(in, new TypeReference<Map<String, Object>>() {
            });
            var found = new TreeMap<String, List<String>>();
            collectEnums(crd, "", found);
            assertFalse(found.isEmpty(), "no enums found in " + CRD_RESOURCE);
            return found;
        }
    }

    static void collectEnums(Object node, String path, Map<String, List<String>> found) {
        if (node instanceof Map<?, ?> map) {
            if (map.get("enum") instanceof List<?> values) {
                var strings = new ArrayList<String>();
                values.forEach(value -> strings.add(String.valueOf(value)));
                found.put(path, strings);
            }
            map.forEach((key, value) -> collectEnums(value, path + "." + key, found));
        } else if (node instanceof List<?> list) {
            for (int i = 0; i < list.size(); i++) {
                collectEnums(list.get(i), path + "[" + i + "]", found);
            }
        }
    }
}
