
[id="configuring-registry-ui_{context}"]
= Configuring the {registry} web console 

[role="_abstract"]
You can set optional environment variables to configure the {registry} web console specifically for your deployment environment or to customize its behavior.

.Prerequisites
* You have already installed {registry}.

[discrete]
== Configuring the web console deployment environment

When you access the {registry} web console in your browser, some initial configuration settings are loaded. The following configuration settings are important:

* URL for core {registry} server REST API
* URL for {registry} web console client

Typically, {registry} automatically detects and generates these settings, but there are some deployment environments where this automatic detection can fail. If this happens, you can configure environment variables to explicitly set these URLs for your environment.

.Procedure
Configure the following environment variables to override the default URLs:

* `REGISTRY_UI_CONFIG_APIURL`: Specifies the URL for the core {registry} server REST API. For example, `\https://registry.my-domain.com/apis/registry`
* `REGISTRY_UI_CONFIG_UIURL`: Specifies the URL for the {registry} web console client. For example, `\https://registry.my-domain.com/ui`

[discrete]
== Configuring the web console in read-only mode

You can configure the {registry} web console in read-only mode as an optional feature. This mode disables all features in the {registry} web console that allow users to make changes to registered artifacts. For example, this includes the following:

* Creating an artifact
* Uploading a new artifact version
* Updating artifact metadata
* Deleting an artifact

.Procedure
Configure the following environment variable: 

* `REGISTRY_UI_FEATURES_READONLY`: Set to `true` to enable read-only mode. Defaults to `false`.
