// Metadata created by nebel

[id="registry-rest-api"]
= Registry core REST API overview
Using the {registry} core REST API, client applications can manage the schema and API artifacts in {registry}. This API provides create, read, update, and delete operations for:

Artifacts::
Manage schema and API artifacts stored in the registry. You can also manage the lifecycle state of an artifact: enabled, disabled, or deprecated. 
Artifact versions::
Manage versions that are created when a schema or API artifact is updated. You can also manage the lifecycle state of an artifact version: enabled, disabled, or deprecated.
Artifact metadata::
Manage details about a schema or API artifact, such as when it was created or modified, and its current state. You can edit the artifact name, description, or label. The artifact group and when the artifact was created or modified are read-only.
Global rules::
Configure rules to govern the content evolution of all schema and API artifacts artifacts to prevent invalid or incompatible content from being added to the registry. Global rules are applied only if an artifact does not have its own specific artifact rules configured. 
Artifact rules::
Configure rules to govern the content evolution of a specific schema or API artifact to prevent invalid or incompatible content from being added to the registry. Artifact rules override any global rules configured. 
Search::
Browse or search for schema and API artifacts and versions, for example, by name, group, description, or label.
Admin::
Manage logging levels for the {registry} instance at runtime.

[discrete]
== Compatibility with other schema registry REST APIs
The  {registry} core REST API version {registry-version} is compatible with the following schema registry APIs:

* {registry} core REST API version 1 
* Confluent schema registry version 6
* IBM schema registry version 1
* Cloud Native Computing Foundation schema registry version 0

Applications using Confluent client libraries can use {registry} as a drop-in replacement. 
ifdef::rh-service-registry[]
For more details, see link:https://developers.redhat.com/blog/2019/12/17/replacing-confluent-schema-registry-with-red-hat-integration-service-registry/[Replacing Confluent Schema Registry with Red Hat Integration Service Registry].
endif::[]

.Additional resources
* For detailed information, see the link:{attachmentsdir}/registry-rest-api.htm[Apicurio Registry REST API documentation].
* API documentation for the core {registry} REST API and for all compatible APIs is available from the main endpoint of your {registry} deployment, for example, on `\http://MY-REGISTRY-URL/apis`.  
