// Metadata created by nebel

[id="registry-rest-api_{context}"]

[role="_abstract"]
= {registry} REST API for clients
Client applications can use the Core Registry API v3 to manage the schema and API artifacts in {registry}. This API provides operations for the following features:

Admin::
Export or import {registry} data in a `.zip` file, and manage logging levels for the {registry} at runtime.
Groups::
Manage groups of artifacts in {registry}.  You can create groups to better organize your artifacts.
Group Rules::
Configure rules to govern the content evolution of schemas or API artifacts within a specific group to prevent invalid or incompatible content from being added to {registry}. Group rules override any global rules configured.
Artifacts::
Manage schema and API artifacts stored in {registry}.
Artifact metadata::
Manage details about a schema or API artifact. You can edit details such as artifact name, description, or labels. Details such as artifact group, and when the artifact was created or modified are read-only.
Artifact rules::
Configure rules to govern the content evolution of a specific schema or API artifact to prevent invalid or incompatible content from being added to {registry}. Artifact rules override any group and/or global rules configured.
Artifact versions::
Manage the sequence of versions that make up the content of a schema or API artifact. You can also manage the lifecycle state of an artifact version: enabled, disabled, or deprecated.
Global rules::
Configure rules to govern the content evolution of all schema and API artifacts to prevent invalid or incompatible content from being added to {registry}. Global rules are applied only if an artifact and its group do not have rules configured.
Search::
Browse or search for schema and API artifacts and versions, for example, by name, group, description, or label.
System::
Get the {registry} version and the limits on resources for the {registry} server.
Users::
Get the current {registry} user.

[discrete]
== Compatibility with other schema registry REST APIs
{registry} also provides compatibility with the following schema registries by including implementations of their respective REST APIs:

* {registry} Core Registry API v2
* Confluent Schema Registry API v7

Applications using Confluent client libraries can use {registry} as a drop-in replacement. 
ifdef::rh-service-registry[]
For more details, see link:https://developers.redhat.com/blog/2019/12/17/replacing-confluent-schema-registry-with-red-hat-integration-service-registry/[Replacing Confluent Schema Registry].
endif::[]

[role="_additional-resources"]
.Additional resources
* For more information on the Core Registry API v3, see the {registry-rest-api}.
* For API documentation on the Core Registry API v3 and all compatible APIs, browse to the `/apis` endpoint of your {registry}, for example, `\http://MY-REGISTRY-URL/apis`.
