// Metadata created by nebel

[id="registry-rest-api_{context}"]

[role="_abstract"]
= {registry} core REST API
Client applications can use the Using the {registry} core v2 REST API to manage the schema and API artifacts in {registry}. This API provides create, read, update, and delete operations for:

Artifacts::
Manage schema and API artifacts stored in the registry. You can also manage the lifecycle state of an artifact: enabled, disabled, or deprecated. 
Artifact versions::
Manage versions that are created when a schema or API artifact is updated. You can also manage the lifecycle state of an artifact version: enabled, disabled, or deprecated.
Artifact metadata::
Manage details about a schema or API artifact, such as when it was created or modified, and its current state. You can edit the artifact name, description, or labels. The artifact group and when the artifact was created or modified are read-only.
Artifact rules::
Configure rules to govern the content evolution of a specific schema or API artifact to prevent invalid or incompatible content from being added to the registry. Artifact rules override any global rules configured. 
Global rules::
Configure rules to govern the content evolution of all schema and API artifacts to prevent invalid or incompatible content from being added to the registry. Global rules are applied only if an artifact does not have its own specific artifact rules configured. 
Search::
Browse or search for schema and API artifacts and versions, for example, by name, group, description, or label.
Admin::
Export or import registry content in a `.zip` file, and manage logging levels for the registry server instance at runtime.

[discrete]
== Compatibility with other schema registry REST APIs
{registry} provides compatibility with the following schema registries by including implementations of their respective REST APIs:

* {registry} core v1 
* Confluent Schema Registry v6
ifdef::apicurio-registry,rh-service-registry[]
* IBM Event Streams schema registry v1
endif::[]
* CNCF CloudEvents Schema Registry v0

Applications using Confluent client libraries can use {registry} as a drop-in replacement. 
ifdef::rh-service-registry[]
For more details, see link:https://developers.redhat.com/blog/2019/12/17/replacing-confluent-schema-registry-with-red-hat-integration-service-registry/[Replacing Confluent Schema Registry].
endif::[]

[role="_additional-resources"]
.Additional resources
* For detailed reference information, see the {registry-rest-api}
ifdef::apicurio-registry,rh-service-registry[]
* API documentation for the core {registry} REST API and for all compatible APIs is available from the main endpoint of your {registry} instance, for example, on `\http://MY-REGISTRY-URL/apis`  
endif::[]
