// Metadata created by nebel

[id="registry-rest-api_{context}"]

[role="_abstract"]
= {registry} REST API for clients
Client applications can use the Core Registry API v2 to manage the schema and API artifacts in {registry}. This API provides operations for the following features:

Admin::
Export or import {registry} data in a `.zip` file, and manage logging levels for the {registry} instance at runtime.
Artifacts::
Manage schema and API artifacts stored in {registry}. You can also manage the lifecycle state of an artifact: enabled, disabled, or deprecated. 
Artifact metadata::
Manage details about a schema or API artifact. You can edit details such as artifact name, description, or labels. Details such as artifact group, and when the artifact was created or modified are read-only.
Artifact rules::
Configure rules to govern the content evolution of a specific schema or API artifact to prevent invalid or incompatible content from being added to {registry}. Artifact rules override any global rules configured. 
Artifact versions::
Manage versions that are created when a schema or API artifact is updated. You can also manage the lifecycle state of an artifact version: enabled, disabled, or deprecated.
Global rules::
Configure rules to govern the content evolution of all schema and API artifacts to prevent invalid or incompatible content from being added to {registry}. Global rules are applied only if an artifact does not have its own specific artifact rules configured. 
Search::
Browse or search for schema and API artifacts and versions, for example, by name, group, description, or label.
System::
Get the {registry} version and the limits on resources for the {registry} instance.
Users::
Get the current {registry} user.

[discrete]
== Compatibility with other schema registry REST APIs
{registry} also provides compatibility with the following schema registries by including implementations of their respective REST APIs:

* {registry} Core Registry API v1 
* Confluent Schema Registry API v6
* Confluent Schema Registry API v7
* CNCF CloudEvents Schema Registry API v0

Applications using Confluent client libraries can use {registry} as a drop-in replacement. 
ifdef::rh-service-registry[]
For more details, see link:https://developers.redhat.com/blog/2019/12/17/replacing-confluent-schema-registry-with-red-hat-integration-service-registry/[Replacing Confluent Schema Registry].
endif::[]

[role="_additional-resources"]
.Additional resources
* For more information on the Core Registry API v2, see the {registry-rest-api}.
ifdef::apicurio-registry,rh-service-registry[]
* For API documentation on the Core Registry API v2 and all compatible APIs, browse to the `/apis` endpoint of your {registry} instance, for example, `\http://MY-REGISTRY-URL/apis`.  
endif::[]
