[id="registry-logging"]
= {registry} logging

You can update {registry} logging configuration at runtime. {registry} provides a REST endpoint to set the log level for specific loggers for finer grained logging.

[id="configuring-registry-logging"]
== Configuring {registry} logging at runtime

This section explains how to view and set {registry} log levels at runtime using the admin REST API.

.Prerequisites

* Get the URL to access your {registry} instance, or get your {registry} route if you have {registry} deployed on OpenShift. This simple example uses localhost:8080.

[discrete]
== Check the current log level for a specific logger

Use this `curl` command to obtain the current log level for the logger `io.apicurio.registry.storage`

[source,bash]
----
$ curl -i localhost:8080/api/v2/admin/loggers/io.apicurio.registry.storage
HTTP/1.1 200 OK
[...]
Content-Type: application/json
{"name":"io.apicurio.registry.storage","level":"INFO"}
----

[discrete]
== Change the log level for a specific logger

Use this `curl` command to change the log level for the logger `io.apicurio.registry.storage` to `DEBUG`

[source,bash]
----
$ curl -X PUT -i -H "Content-Type: application/json" --data '{"level":"DEBUG"}' localhost:8080/api/v2/admin/loggers/io.apicurio.registry.storage
HTTP/1.1 200 OK
[...]
Content-Type: application/json
{"name":"io.apicurio.registry.storage","level":"DEBUG"}
----

You can revert to the default log level the configuration of a specific logger.
Use this `curl` command to change the log level for the logger `io.apicurio.registry.storage` to it's default value

[source,bash]
----
$ curl -X DELETE -i localhost:8080/api/v2/admin/loggers/io.apicurio.registry.storage
HTTP/1.1 200 OK
[...]
Content-Type: application/json
{"name":"io.apicurio.registry.storage","level":"INFO"}
----