// Module included in the following assemblies:
//  assembly-using-kafka-client-serdes

[id='registry-serdes-types-json-{context}']
= Configure JSON Schema SerDe with {registry}

{registry} provides the following Kafka client serializer and deserializer classes for JSON Schema:

* `io.apicurio.registry.serde.jsonschema.JsonSchemaKafkaSerializer`
* `io.apicurio.registry.serde.jsonschema.JsonSchemaKafkaDeserializer`

Unlike Apache Avro, JSON Schema is not a serialization technology, and is instead a validation technology. As a result, configuration options for JSON Schema are quite different. For example, there is no encoding option, because data is always encoded as JSON.

.Configure the JSON Schema serializer

You can configure the JSON Schema serializer class as follows:

* {registry} location as a URL
* Artifact resolver strategy 
* Schema resolver strategy 
* Validation enabled/disabled

The only non-standard configuration property is whether JSON Schema validation is enabled or
disabled.  The validation feature is disabled by default but you can enable this by setting
`apicurio.registry.serde.validation-enabled` to `"true"`. For example:
----
props.putIfAbsent(SerdeConfig.VALIDATION_ENABLED, Boolean.TRUE)`
----

.Configure the JSON Schema deserializer

You can configure the JSON Schema deserializer class in the following ways:

* {registry} location as a URL
* Validation enabled/disabled

You must provide the location of {registry} so that the schema can be loaded. The only other configuration is whether or not to perform validation. These configuration properties are the same as for the serializer.

NOTE: Deserializer validation only works if the serializer passes the global ID in the Kafka message, which will only happen when validation is enabled in the serializer.

.Additional resources
* For an example application, see the link:https://github.com/Apicurio/apicurio-registry-examples[Simple JSON Schema example]    
