// Module included in the following assemblies:
//  assembly-using-kafka-client-serdes

[id='registry-serdes-types-avro-{context}']
= Configure Avro SerDe with {registry}

{registry} provides the following Kafka client serializer and deserializer classes for Apache Avro:

* `io.apicurio.registry.serde.avro.AvroKafkaSerializer`
* `io.apicurio.registry.serde.avro.AvroKafkaDeserializer`

.Configure the Avro serializer

You can configure the Avro serializer class as follows:

* {registry} location as a URL
* Artifact resolver strategy 
* Schema resolver strategy 
* Global ID location
* Global ID handler
* Avro datum provider
* Avro encoding

.Global ID location
The serializer passes the unique global ID of the schema as part of the Kafka message so that consumers can use the correct schema for deserialization. The location of that global ID can be in the payload of the message or in the message headers. The default approach is to pass the global ID in the message payload. If you want the ID sent in the message headers instead, you can set the following configuration property:
----
props.putIfAbsent(SerdeConfig.ENABLE_HEADERS, "true")
----
The property name is `apicurio.registry.headers.enabled`.


.Global ID handler
You can customize precisely how the global ID is encoded when passing it in the Kafka message body. Set
the configuration property `apicurio.registry.id-handler` to be a class that implements the
`io.apicurio.registry.serde.IdHandler` interface. {registry} provides two implementations of
that interface:

* `io.apicurio.registry.serde.DefaultIdHandler`: Stores the ID as an 8-byte long
* `io.apicurio.registry.serde.Legacy4ByteIdHandler`:  Stores the ID as an 4-byte integer

{registry} represents the global ID of an artifact as a long, but for legacy reasons, or for compatibility with other registries or serde classes, you might want to use 4 bytes when sending the ID.

.Avro datum provider
Avro provides different datum writers and readers to write and read data. {registry} supports three different types:

* Generic
* Specific
* Reflect

The {registry} `AvroDatumProvider` is the abstraction of which type is actually used, where `DefaultAvroDatumProvider` is used by default.

You can set the following configuration options:

* `apicurio.registry.avro-datum-provider`: Specifies a fully-qualified Java class name of the `AvroDatumProvider` implementation, for example `io.apicurio.registry.serde.avro.ReflectAvroDatumProvider`
* `apicurio.registry.use-specific-avro-reader`: Set to `true` or `false`, to use a specific type when using `DefaultAvroDatumProvider`

.Avro encoding

When using Avro to serialize data, you can use the Avro binary encoding format to ensure the data is encoded in as efficient a format as possible. Avro also supports encoding the data as JSON, which makes it easier to inspect the payload of each message, for example, for logging or debugging. 

You can set the Avro encoding by configuring the `apicurio.registry.avro.encoding` property with a value of `JSON` or `BINARY`. The default is `BINARY`.

.Configure the Avro deserializer

You must configure the Avro deserializer class to match the configuration settings of the serializer.  As a
result, you can configure the Avro deserializer class as follows:

* {registry} location as a URL
* Global ID handler
* Avro datum provider
* Avro encoding

See the serializer section for these configuration options - the property names and values are the same.

[NOTE] 
====
The following options are not required when configuring the deserializer:

* Artifact resolver strategy 
* Schema resolver strategy 
* Global ID location
====

These options are not required because the deserializer class can determine this from the message. The strategies are not required because the serializer is responsible for sending the global ID as part of the message. 

The location of the global ID is determined by checking for the magic byte at the start of the message payload. If that byte is found, the global ID is read from the message payload using the configured handler.  If the magic byte is not found, the global ID is read from the message headers.

.Additional resources

* For more details on Avro configuration, see the link:https://github.com/Apicurio/apicurio-registry/blob/master/serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroKafkaSerdeConfig.java[AvroKafkaSerdeConfig Java class]
* For an example application, see the link:https://github.com/Apicurio/apicurio-registry-examples[Simple Avro example]
