// Module included in the following assemblies:
//  assembly-using-kafka-client-serdes

[id='registry-serdes-concepts-constants-{context}']
= {registry} serializer/deserializer configuration

You can configure specific client serializer/deserializer (SerDe) services and schema lookup strategies directly in a client application using the example constants shown in this section. Alternatively, you can configure the corresponding {registry} application properties in a file or an instance. 

The following sections show examples of some of the available SerDe constants and configuration options.


[discrete]
== Configuration for SerDe services

[source,java,subs="+quotes,attributes"]
----
public class SerdeConfig {

   public static final String REGISTRY_URL = "apicurio.registry.url"; <1>
   public static final String ID_HANDLER = "apicurio.registry.id-handler"; <2>
   public static final String REGISTRY_CONFLUENT_ID_HANDLER = "apicurio.registry.as-confluent"; <3>
----
<1> The required URL of {registry}.
<2> Extends ID handling to support other ID formats and make them compatible with {registry} SerDe services.
For example, changing the default ID format from `Long` to `Integer` supports the Confluent ID format.
<3> Simplifies the handling of Confluent IDs. If set to `true`, an `Integer` is used for the global ID lookup.
The setting should not be used with the `ID_HANDLER` option.

.Additional resources

* For more details, see the link:https://github.com/Apicurio/apicurio-registry/blob/master/serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java[SerdeConfig Java class] 

[discrete]
== Configuration for SerDe lookup strategies

[source,java,subs="+quotes,attributes"]
----
public class SerdeConfig {
    
   public static final String ARTIFACT_RESOLVER_STRATEGY = "apicurio.registry.artifact-resolver-strategy"; <1>
   public static final String REGISTRY_GLOBAL_ID_STRATEGY = "apicurio.registry.global-id"; <2>
----
<1> See xref:service-registry-concepts-artifactid-registry[].
<2> See xref:configuring-globalid-strategy-registry[].

.Additional resources

* For more details, see the link:https://github.com/Apicurio/apicurio-registry/blob/master/serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java[SerdeConfig Java class] 

[discrete]
== Configuration for converters
The following example shows some constants and configuration options:

[source,java,subs="+quotes,attributes"]
----
public class SerdeBasedConverter<S, T> extends SchemaResolverConfigurer<S, T> implements Converter, Closeable {

   public static final String REGISTRY_CONVERTER_SERIALIZER_PARAM = "apicurio.registry.converter.serializer"; <1>
   public static final String REGISTRY_CONVERTER_DESERIALIZER_PARAM = "apicurio.registry.converter.deserializer"; <2>   
----
<1> The required serializer to use with the converter.
<2> The required deserializer to use with the converter.

.Additional resources

* For more details, see the link:https://github.com/Apicurio/apicurio-registry/blob/master/utils/converter/src/main/java/io/apicurio/registry/utils/converter/SerdeBasedConverter.java[SerdeBasedConverter Java class] 

[discrete]
== Configuration for Avro data providers

[source,java,subs="+quotes,attributes"]
----
public class AvroKafkaSerdeConfig extends BaseKafkaSerDeConfig {
    
   String AVRO_DATUM_PROVIDER = "apicurio.registry.avro-datum-provider"; <1>
   String USE_SPECIFIC_AVRO_READER = "apicurio.registry.use-specific-avro-reader"; <2>
----
<1> Avro Datum provider to write data to a schema.
<2> Specify this option to use an Avro-specific datum reader. 


.Additional resources

* For more details, see xref:registry-serdes-types-avro-registry[]

[discrete]
== Configuration for JSON Schema Serde 

For details, see xref:registry-serdes-types-json-registry[].
  

[discrete]
== Configuration for Protobuf SerDe

For details, see xref:registry-serdes-types-protobuf-registry[].




  
