// Module included in the following assemblies:
//  assembly-using-kafka-client-serdes

[id='registry-serdes-types-protobuf-{context}']

= Configure Protobuf SerDe with {registry}

{registry} provides Kafka client serializer and deserializer classes for Google Protobuf to make using Protobuf as easy as possible:

* `io.apicurio.registry.utils.serde.ProtobufKafkaSerializer`
* `io.apicurio.registry.utils.serde.ProtobufKafkaDeserializer`

.Configure the Protobuf serializer

You can configure the Protobuf serializer class in the following ways:

* {registry} location as a URL
* Artifact ID strategy 
* Global ID strategy 
* Global ID location
* Global ID handler

.Configure the Protobuf deserializer

You must configure the Protobuf deserializer class to match the configuration settings of the serializer.  As a result, you can configure the Protobuf deserializer class in the following ways:

* {registry} location as a URL
* Global ID handler

See the serializer section for these configuration options - the property names and values are the same.

[NOTE]
====
The following options are not needed when configuring the deserializer:

* Artifact ID strategy
* Global ID strategy
* Global ID location
====

The reason these options are not necessary is that the deserializer class can figure this information out from
the message itself. In the case of the two strategies, they are not needed because the serializer is responsible for sending the global ID of the schema as part of the message.  

The location of that global ID is determined (by the deserializer) by simply checking for the magic byte at the start of the message payload. If that byte is found, the global ID is read from the message payload (using the configured handler). If the magic byte is not found, the global ID is read from the message headers.

NOTE: The Protobuf deserializer does not deserialize to your exact Protobuf Message implementation,
but rather to a `DynamicMessage` instance (because there is no appropriate API to do otherwise).
