// Module included in the following assemblies:
//  assembly-using-kafka-client-serdes

[id='registry-serdes-types-json-{context}']
= Configure JSON Schema SerDe with {registry}

{registry} provides Kafka client serializer and deserializer classes for JSON Schema to make using JSON Schema as easy as possible:

* `io.apicurio.registry.utils.serde.JsonSchemaKafkaSerializer`
* `io.apicurio.registry.utils.serde.JsonSchemaKafkaDeserializer`

Unlike Apache Avro, JSON Schema is not actually a serialization technology - it is instead a validation
technology. As a result, configuration options for JSON Schema are quite different. For example, there is no
encoding option, because data is always encoded as JSON.

.Configure the JSON Schema serializer

You can configure the JSON Schema serializer class in the following ways:

* {registry} location as a URL
* Artifact ID strategy 
* Global ID strategy
* Validation enabled/disabled

The only non-standard configuration property is whether JSON Schema validation is enabled or
disabled.  The validation feature is disabled by default but can be enabled by setting
`apicurio.registry.serdes.json-schema.validation-enabled` to `"true"`. For example:
----
props.putIfAbsent(JsonSchemaSerDeConstants.REGISTRY_JSON_SCHEMA_VALIDATION_ENABLED, "true")`
----

.Configure the JSON Schema deserializer

You can configure the JSON Schema deserializer class in the following ways:

* {registry} location as a URL
* Validation enabled/disabled

The deserializer is simple to configure. You must provide the location of {registry} so that the schema can be loaded. The only other configuration is whether or not to perform validation.  These
configuration properties are the same as for the serializer.

NOTE: Deserializer validation only works if the serializer passes the global ID in the Kafka message, which will only happen when validation is enabled in the serializer.
