// Metadata created by nebel

[id="registry-client-intro_{context}"]
= {registry} Java SDK

[role="_abstract"]
You can manage artifacts stored in {registry} by using a Java client application. You can create, read, update, or delete artifacts by using the {registry} Java client classes. You can also use the {registry} Java client to perform administrator functions, such as managing global rules or importing and exporting {registry} data.

You can access the {registry} Java client by adding the correct dependency to your Apache Maven project. 
ifdef::apicurio-registry,rh-service-registry[]
For more details, see xref:writing-registry-client_registry[].
endif::[]
ifdef::rh-openshift-sr[]
For more details, see xref:writing-registry-client_java-client[Writing {registry} Java client applications].
endif::[]

The {registry} client is implemented by using the HTTP client provided by the JDK, which you can customize as needed. For example, you can add custom headers or enable configuration options for Transport Layer Security (TLS) authentication. 
ifdef::apicurio-registry,rh-service-registry[]
For more details, see xref:registry-client-config_registry[].
endif::[]
ifdef::rh-openshift-sr[]
For more details, see xref:registry-client-config_java-client[{registry} Java client configuration].
endif::[]
