// Module included in the following assemblies:
//  assembly-using-kafka-client-serdes

[id='registry-serdes-types-avro-{context}']
= Configure Avro SerDe with {registry}

{registry} provides Kafka client serializer and deserializer classes for Apache Avro to make using Avro as
easy as possible:

* `io.apicurio.registry.utils.serde.AvroKafkaSerializer`
* `io.apicurio.registry.utils.serde.AvroKafkaDeserializer`


.Configure the Avro serializer

You can configure the Avro serializer class in the following ways:

* {registry} location as a URL
* Artifact ID strategy 
* Global ID strategy 
* Global ID location
* Global ID handler
* Avro datum provider
* Avro encoding

.Global ID location
The serializer passes the unique global ID of the schema as part of the Kafka message so that consumers can use the right schema for deserialization.  The location of that global ID can be in the payload of the message or in the message headers. The default approach is to pass the global ID in the message payload. If you want the ID sent in the message headers instead, you can set the following configuration property:
----
props.putIfAbsent(AbstractKafkaSerDe.USE_HEADERS, "true")
----
The property name is `apicurio.registry.use.headers`.


.Global ID handler
You can customize precisely how the global ID is encoded when passing it in the Kafka message body. Set
the configuration property `apicurio.registry.id-handler` to be a class that implements the
`io.apicurio.registry.utils.serde.strategy.IdHandler` interface. {registry} provides two implementations of
that interface:

* `io.apicurio.registry.utils.serde.strategy.DefaultIdHandler` - stores the ID as an 8 byte long
* `io.apicurio.registry.utils.serde.strategy.Legacy4ByteIdHandler` - stores the ID as an 4 byte int

{registry} represents the global ID of an artifact as a long, but for legacy reasons (or for compatibility with other registries or serde classes) you may want to use 4 bytes when sending the ID.

.Avro datum provider
Avro provides different datum writers and readers to write and read data. {registry} supports three different types:

* Generic
* Specific
* Reflect

The {registry} `AvroDatumProvider` is the abstraction on which type is then actually used, where `DefaultAvroDatumProvider` is used by default.

There are two configuration options you can set:

* `apicurio.registry.avro-datum-provider` - provide a fully qualified Java class name of the `AvroDatumProvider` implementation, for example `io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider`
* `apicurio.registry.use-specific-avro-reader` - true or false, to use specific type when using `DefaultAvroDatumProvider`

.Avro encoding

When using Apache Avro to serializer data, it is common to use the Avro binary encoding format. This is so that the data is encoded in as efficient a format as possible.  However, Avro also supports encoding the data as JSON. Encoding as JSON is useful because it is much easier to inspect the payload of each message, often for logging, debugging, or other similar use cases.  The {registry} Avro serializer can be configured to change the encoding to JSON from the default (binary).

Set the Avro encoding to use by configuring the `apicurio.avro.encoding` property. The value must be either
`JSON` or `BINARY`.

.Configure the Avro deserializer

You must configure the Avro deserializer class to match the configuration settings of the serializer.  As a
result, you can configure the Avro deserializer class in the following ways:

* {registry} location as a URL
* Global ID handler
* Avro datum provider
* Avro encoding

See the serializer section for these configuration options - the property names and values are the same.

[NOTE] 
====
The following options are not needed when configuring the deserializer:

* Artifact ID strategy
* Global ID strategy
* Global ID location
====

The reason these options are not necessary is that the deserializer class can figure this information out from
the message itself. In the case of the two strategies, they are not needed because the serializer is responsible for sending the global ID of the schema as part of the message. 

The location of that global ID is determined by the deserializer by simply checking for the magic byte at the start of the message payload. If that byte is found, the global ID is read from the message payload using the configured handler.  If the magic byte is not found, the global ID is read from the message headers.
