// Metadata created by nebel

[id="registry-rest-api"]
= Registry REST API overview
Using the core {registry} REST API, client applications can manage the artifacts in {registry}. This API provides create, read, update, and delete operations for:

Artifacts::
Manage schema and API design artifacts stored in the registry. You can also manage the lifecycle state of an artifact: enabled, disabled, or deprecated. 
Artifact versions::
Manage versions that are created when artifact content is updated. You can also manage the lifecycle state of an artifact version: enabled, disabled, or deprecated.
Artifact metadata::
Manage details about an artifact such as when it was created or modified, and its current state. You can edit the artifact name, description, or label, but when the artifact was created or modified is read-only.
Global rules::
Configure rules to govern the content evolution of all artifacts to prevent invalid or incompatible content from being added to the registry. Global rules are applied only if an artifact does not have its own specific artifact rules configured. 
Artifact rules::
Configure rules to govern the content evolution of a specific artifact to prevent invalid or incompatible content from being added to the registry. Artifact rules override any global rules configured. 
Search::
Browse or search for artifacts and versions, for example, by name, ID, description, or label.
Admin::
Get or set logging level configuration at runtime.

[discrete]
== Compatibility with other schema registry REST APIs
The  {registry} REST API version {registry-version} is compatible with the following schema registry REST APIs:

* Core {registry} REST API version 1 
* Confluent schema registry version 6
* IBM schema registry version 1
* Cloud Native Computing Foundation schema registry version 0

Applications using Confluent client libraries can use {registry} as a drop-in replacement instead. 
ifdef::rh-service-registry[]
For more details, see link:https://developers.redhat.com/blog/2019/12/17/replacing-confluent-schema-registry-with-red-hat-integration-service-registry/[Replacing Confluent Schema Registry with Red Hat Integration Service Registry].
endif::[]

.Additional resources
* For detailed information, see the link:{attachmentsdir}/registry-rest-api.htm[Apicurio Registry REST API documentation].
* API documentation for the core {registry} REST API and for all compatible APIs is available from the main endpoint of your {registry} deployment, for example, on `\http://MY-REGISTRY-URL/apis`.  
