// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="installing-registry-infinispan-storage"]
= Installing {registry} with embedded Infinispan storage

This section explains how to install and run {registry} with embedded Infinispan storage from a container image. This storage option is based on Infinispan community Java libraries embedded in the Quarkus-based {registry} server. You do not need to install a separate Infinispan server using this storage option. 

NOTE: The default embedded Infinispan storage is suitable for development only. If you do not configure an Infinispan cluster, all data is lost when the container image is restarted. For more details on Infinispan, see the https://infinispan.org/documentation/[Infinispan documentation].

.Prerequisites

* You must have Docker installed and the Docker daemon running.
* Ensure that you can connect to the container repository: https://hub.docker.com/r/apicurio/apicurio-registry-mem.

.Procedure

. Get the {registry} container image:
+
[source,bash]
----
$ docker pull apicurio/apicurio-registry-infinispan:latest
----
. Run the container image: 
+
[source,bash]
----
$ docker run -it -p 8080:8080 apicurio/apicurio-registry-infinispan:latest
----

. Send a test request using the {registry} REST API. For example, enter the following `curl` command to create a simple Avro schema artifact for a share price application in the registry:
+
[source,bash]
----
$ curl -X POST -H "Content-type: application/json; artifactType=AVRO" -H "X-Registry-ArtifactId: share-price" --data '{"type":"record","name":"price","namespace":"com.example","fields":[{"name":"symbol","type":"string"},{"name":"price","type":"string"}]}' http://localhost:8080/apis/registry/v2/groups/my-group/artifacts
----
. Verify that the response includes the expected JSON body to confirm that the Avro schema artifact was created in the registry. For example:
+
[source,bash]
----
{"name":"price","createdBy":"","createdOn":"2021-03-19T17:48:17+0000","modifiedOn":"2021-03-19T17:48:17+0000","id":"share-price","version":1,"type":"AVRO","globalId":12,"state":"ENABLED","groupId":"my-group","contentId":12}
----

.Additional resources
* For more REST API sample requests, see the link:{attachmentsdir}/registry-rest-api.htm[Apicurio Registry REST API documentation].
* For more details on Infinispan, see https://infinispan.org/[].
* For a demonstration based on Kafka Streams storage, see link:https://github.com/Apicurio/apicurio-registry-demo[].
