// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts.adoc

[id="managing-artifacts-using-rest-api"]
= Managing artifacts using Registry REST API commands

Client applications can use Registry REST API commands to manage artifacts in {registry}, for example, in a CI/CD pipeline deployed in production. The Registry REST API provides create, read, update, and delete operations for artifacts, versions, metadata, and rules stored in the registry. For detailed information, see the link:{attachmentsdir}/registry-rest-api.htm[Apicurio Registry REST API documentation].

This section shows a simple curl-based example of using the Registry REST API to add and retrieve an Apache Avro schema artifact in the registry. 

NOTE: When adding artifacts in {registry} using the REST API, if you do not specify a unique artifact ID, {registry} generates one automatically as a UUID.

.Prerequisites

* See {registry-overview}
* {registry} must be installed and running in your environment. 

.Procedure

. Add an artifact in the registry using the `/artifacts` operation. The following example `curl` command adds a simple artifact for a share price application:
+
[source,bash]
----
$ curl -X POST -H "Content-type: application/json; artifactType=AVRO" -H "X-Registry-ArtifactId: share-price" --data '{"type":"record","name":"price","namespace":"com.example","fields":[{"name":"symbol","type":"string"},{"name":"price","type":"string"}]}' http://MY-REGISTRY-HOST/api/artifacts
----
+
This example shows adding an Avro schema artifact with an artifact ID of `share-price`.
+
ifdef::apicurio-registry[]
`MY-REGISTRY-HOST` is the host name on which {registry} is deployed. For example: `\http://localhost:8080/api/artifacts`.
endif::[]

ifdef::rh-service-registry[]
`MY-REGISTRY-HOST` is the host name on which {registry} is deployed. For example: `my-cluster-service-registry-myproject.example.com`. 
endif::[]

. Verify that the response includes the expected JSON body to confirm that the artifact was added. For example:
+
[source,bash]
----
{"createdOn":1578310374517,"modifiedOn":1578310374517,"id":"share-price","version":1,"type":"AVRO","globalId":8}
----

. Retrieve the artifact from the registry using its artifact ID. For example, in this case the specified ID is `share-price`:
+
[source,bash]
----
$ curl http://MY-REGISTRY-URL/api/artifacts/share-price
'{"type":"record","name":"price","namespace":"com.example","fields":[{"name":"symbol","type":"string"},{"name":"price","type":"string"}]}
----

.Additional resources
* For more REST API sample requests, see the link:{attachmentsdir}/registry-rest-api.htm[Apicurio Registry REST API documentation].
