// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts.adoc

[id="migrating-registry-serdes"]
= Migrating {registry} Kafka client serializers/deserializers

[role="_abstract"]
You must review your existing Kafka client serializer/deserializer (SerDes) applications and update the Maven dependencies and application configuration to meet the new requirements for version 2.x. For example, this includes new Maven dependencies for the Kafka client SerDes libraries. You must also update your application configuration with the new registry v2 API path. 


.Prerequisites 
* Existing {registry} version 1.3.x Kafka client SerDes applications written in Java 

.Procedure



. You must change the Maven dependencies for the SerDes libraries, which have been repackaged in version 2.x. In {registry} 1.3.x, the SerDes libraries were all provided with only one Maven dependency:
+
[source, xml]
----
<dependency>
    <groupId>io.apicurio</groupId>
    <artifactId>apicurio-registry-utils-serde</artifactId>
    <version>1.3.2.Final</version>
</dependency>
----
+
In {registry} 2.x, the SerDes libraries have been split into three Maven dependencies, one for each supported data format: `avro`, `protobuf`, and `json schema`, depending on your use cases:
+
[source, xml]
----
<dependency>
    <groupId>io.apicurio</groupId>
    <artifactId>apicurio-registry-serdes-avro-serde</artifactId>
    <version>2.0.0.Final</version>
</dependency>
<dependency>
    <groupId>io.apicurio</groupId>
    <artifactId>apicurio-registry-serdes-protobuf-serde</artifactId>
    <version>2.0.0.Final</version>
</dependency>
<dependency>
    <groupId>io.apicurio</groupId>
    <artifactId>apicurio-registry-serdes-jsonschema-serde</artifactId>
    <version>2.0.0.Final</version>
</dependency>
----

. In your Kafka producer and consumer Java applications, you must change your registry URL configuration from pointing to the existing v1 API path to the new v2 path. For example:
+
_Existing v1 registry v1 API path_:
+
[source,java]
----
props.putIfAbsent(AbstractKafkaSerDe.REGISTRY_URL_CONFIG_PARAM, "http://old-registry.my-company.com/api");
----
+
_New registry v2 API path_:
+
[source,java]
----
props.putIfAbsent(SerdeConfig.REGISTRY_URL, "http://new-registry.my-company.com/apis/registry/v2");
----
+
The refactored SerDes libraries also include other changes to optional configuration properties. You can find more details in 
ifdef::apicurio-registry[]
{kafka-client-serdes}. 
endif::[]
ifdef::rh-service-registry[]
link:{LinkServiceRegistryUser}[{NameServiceRegistryUser}]
endif::[]

[role="_additional-resources"]
.Additional resources
* For detailed configuration examples, see the link:https://github.com/Apicurio/apicurio-registry-examples/tree/2.0.x[Apicurio Registry example applications].
