// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts.adoc

[id="exporting-importing-using-web-console_{context}"]
= Exporting and importing registry content using the {registry} web console

[role="_abstract"]
As an administrator, you can use the {registry} web console to export data from one {registry} instance, and import it into another {registry} instance. You can use this feature to easily migrate data between different instances.

The following example shows how to export and import existing data in a `.zip` file from one {registry} instance to another instance. All of the artifact data contained in the {registry} instance is exported in the `.zip` file.

NOTE: You can import only {registry} data that has been exported from another {registry} instance. 

ifdef::rh-openshift-sr[]
This example shows exporting and importing {registry} data from the *Artifacts* tab for that instance. You can also export {registry} data when prompted before deleting an instance. 
endif::[]

.Prerequisites

* {registry} instances have been created as follows: 
** The source instance that you are exporting from contains at least one schema or API artifact 
** The target instance that you are importing into is empty to preserve unique IDs 
* You are logged into the {registry} web console with administrator access: 
+
`{registry-url}`

.Procedure

ifdef::apicurio-registry,rh-service-registry[]
. In the web console for the source {registry} instance, view the *Artifacts* tab.  
endif::[] 

ifdef::rh-openshift-sr[]
. In the web console, in the list of instances, click the source {registry} instance, and view the *Artifacts* tab.  
endif::[] 

. Click the options icon (three vertical dots) next to *Upload artifact*, and select *Download all artifacts (.zip file)* to export the registry data for this instance to a `.zip` download file. 

ifdef::apicurio-registry,rh-service-registry[]
. In the the web console for the target {registry} instance, view the *Artifacts* tab.  
endif::[] 

ifdef::rh-openshift-sr[]
. Return to the list of instances, click the target {registry} instance, and view the *Artifacts* tab.     
endif::[]

. Click the options icon next to *Upload artifact*, and select *Upload multiple artifacts*.

. Drag and drop or browse to the `.zip` download file that you exported earlier.

. Click *Upload* and wait for the data to be imported.

//[role="_additional-resources"]
//.Additional resources
