// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts.adoc

[id="exporting-importing-using-web-console_{context}"]
= Exporting and importing registry content using {registry} web console

[role="_abstract"]
This section shows an example of using the {registry} web console to export and import existing registry data in `.zip` format from one {registry} instance to another. For example, this is useful when migrating data between {registry} instances. All of the artifact data contained in the {registry} instance is exported in the `.zip` file.

ifdef::rh-openshift-sr[]
IMPORTANT: You can import {registry} data that has been exported from another {product-long-registry} instance. You cannot currently import {registry} data from a {org-name} Integration {registry} instance.   
endif::[]

.Prerequisites

* {registry} instances have been created: 
** The source instance that you want to export data from contains at least one schema or API artifact 
** The target instance that you want to export data from  can contain artifacts or be empty 
* You have access to the {registry} web console 
ifdef::apicurio-registry,rh-service-registry[]
for each instance
endif::[] 
running on: 
+
`{registry-url}`

.Procedure

ifdef::apicurio-registry,rh-service-registry[]
. In the web console for the source {registry} instance that you want to export data from, select the *Artifacts* page.  
endif::[] 

ifdef::rh-openshift-sr[]
. In the web console, in the list of instances, select the source {registry} instance that you want to export data from.  
endif::[] 

. Next to the *Upload artifacts* button, select the options icon (three vertical dots), and click *Download all artifacts (.zip file)* to export the registry data for this instance to a `.zip` download file.

ifdef::rh-openshift-sr[]
. Go back to the list of instances and select the target {registry} instance that you want to import data into.    
endif::[] 

ifdef::apicurio-registry,rh-service-registry[]
. In the  the web console for the target {registry} instance that you want to export data to, select the *Artifacts* page.  
endif::[] 

. Next to the *Upload artifacts* button, select the options icon (three vertical dots), and click *Upload multiple artifacts*.

. Drag and drop or browse to the previously exported `.zip` download file that contains the data from the previously exported registry instance that you want to import.

. Click *Upload* and wait for the upload to complete.

//[role="_additional-resources"]
//.Additional resources
