// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

[id="setting-up-infinispan-storage"]


= Configuring {registry} with embedded Infinispan storage on OpenShift

This section explains how to configure Infinispan cache-based storage for {registry} on OpenShift. This storage option is based on Infinispan community Java libraries embedded in the Quarkus-based {registry} server. You do not need to install a separate Infinispan server using this storage option. This option is suitable for development or demonstration only, and is not suitable for production environments.

.Prerequisites
* You must have an OpenShift cluster with cluster administrator access.
* You must have already installed {registry}. See {installing-the-registry-openshift}.


.Procedure

. In the OpenShift Container Platform web console, log in using an account with cluster administrator privileges.

ifdef::apicurio-registry[]
. Click *Installed Operators* > *{registry}* > *ApicurioRegistry* > *Create ApicurioRegistry*. 
endif::[]
ifdef::rh-service-registry[]
. Click *Installed Operators* > *Red Hat Integration - {registry}* > *ApicurioRegistry* > *Create ApicurioRegistry*. 
endif::[]

. Paste in the following custom resource definition: 
+
[source,yaml]
----
apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  configuration:
    persistence: "infinispan"
    infinispan: # Currently uses embedded version of Infinispan
      clusterName: "example-apicurioregistry"
      # ^ Optional
----
      
. Click *Create* and wait for the {registry} route to be created on OpenShift.

. Click *Networking* > *Route* to access the new route for the {registry} web console. For example:
+
[source]
----
http://example-apicurioregistry.my-project.my-domain-name.com/   
----

.Additional resources

* For more details on configuring Infinispan clusters, see the example custom resources available from the link:https://github.com/Apicurio/apicurio-registry-demo/blob/master/kubernetes/resources-infinispan.yaml[Apicurio Registry demonstration]. 
* For more details on Infinispan, see https://infinispan.org/[]
