// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts.adoc

[id="exporting-importing-using-web-console_{context}"]
= Exporting and importing data using the {registry} web console

[role="_abstract"]
As an administrator, you can use the {registry} web console to export data from one {registry} instance, and import this data into another {registry} instance. You can use this feature to easily migrate data between different instances.

The following example shows how to export and import existing data in a `.zip` file from one {registry} instance to another instance. All the artifact data contained in the {registry} instance is exported in the `.zip` file.

NOTE: You can import only {registry} data that has been exported from another {registry} instance. 

.Prerequisites

* {registry} instances have been created as follows: 
** The source instance that you are exporting from contains at least one schema or API artifact 
** The target instance that you are importing into is empty to preserve unique IDs 
* You are logged into the {registry} web console with administrator access: 
+
`{registry-url}`

.Procedure

. In the web console for the source {registry} instance, view the *Artifacts* tab.

. Click the options icon (three vertical dots) next to *Upload artifact*, and select *Download all artifacts (.zip file)* to export the data for this {registry} instance to a `.zip` download file.

. In the the web console for the target {registry} instance, view the *Artifacts* tab.

. Click the options icon next to *Upload artifact*, and select *Upload multiple artifacts*.

. Drag and drop or browse to the `.zip` download file that you exported earlier.

. Click *Upload* and wait for the data to be imported.

//[role="_additional-resources"]
//.Additional resources
