// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts-api.adoc

[id="managing-artifacts-using-rest-api_{context}"]
= Managing schema and API artifacts using {registry} REST API commands

[role="_abstract"]
This section shows a simple curl-based example of using the Core Registry API v3 to add and retrieve a simple schema artifact in {registry}.

.Prerequisites

* {registry} is installed and running in your environment.

.Procedure

. Add an artifact to {registry} using the `/groups/\{group\}/artifacts` operation. The following example `curl` command adds a simple schema artifact for a share price application:
+
[source,bash]
----
$ curl -X POST -H "Content-Type: application/json; artifactType=AVRO" \ 
  -H "X-Registry-ArtifactId: share-price" \ 
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  --data '{"type":"record","name":"price","namespace":"com.example", \ 
   "fields":[{"name":"symbol","type":"string"},{"name":"price","type":"string"}]}' \ 
  MY-REGISTRY-URL/apis/registry/v3/groups/my-group/artifacts
----
+
* This example adds an Apache Avro schema artifact with an artifact ID of `share-price`. If you do not specify a unique artifact ID, {registry} generates one automatically as a UUID. 
* `MY-REGISTRY-URL` is the 
ifdef::apicurio-registry[]
host name on which {registry} is deployed. For example: `\http://localhost:8080`.
endif::[]
ifdef::rh-service-registry[]
host name on which {registry} is deployed. For example: `my-cluster-service-registry-myproject.example.com`. 
endif::[]
* This example specifies a group ID of `my-group` in the API path. If you do not specify a unique group ID, you must specify `../groups/default` in the API path.

. Verify that the response includes the expected JSON body to confirm that the artifact was added. For example:
+
[source,bash]
----
{"createdBy":"","createdOn":"2021-04-16T09:07:51+0000","modifiedBy":"", 
"modifiedOn":"2021-04-16T09:07:51+0000","id":"share-price","version":"1", 
"type":"AVRO","globalId":2,"state":"ENABLED","groupId":"my-group","contentId":2} 
----
+
* No version was specified when adding the artifact, so the default version `1` is created automatically.
* This was the second artifact added to {registry}, so the global ID and content ID have a value of `2`. 
. Retrieve the artifact content from {registry} using its artifact ID in the API path. In this example, the specified ID is `share-price`:
+
[source,bash]
----
$ curl -H "Authorization: Bearer $ACCESS_TOKEN" \
 MY-REGISTRY-URL/apis/registry/v3/groups/my-group/artifacts/share-price
 {"type":"record","name":"price","namespace":"com.example", 
  "fields":[{"name":"symbol","type":"string"},{"name":"price","type":"string"}]}
----

[role="_additional-resources"]
.Additional resources
* For more details, see the {registry-rest-api}.
