// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_registry-reference.adoc

[id="registry-rule-types_{context}"]
= {registry} content rule types

[role="_abstract"]
You can specify `VALIDITY`, `COMPATIBILITY`, and `INTEGRITY` rule types to govern content evolution in {registry}. Theses rule types apply to both global rules and artifact-specific rules. 

.{registry} content rule types
[%header,cols=2*]
|===
|Type
|Description
|`VALIDITY`
a| Validate content before adding it to {registry}. The possible configuration values for this rule are as follows:

* `FULL`: The validation is both syntax and semantic.
* `SYNTAX_ONLY`: The validation is syntax only.
* `NONE`: All validation checks are disabled.

|`COMPATIBILITY`
a| Enforce a compatibility level when updating artifacts (for example, select `BACKWARD` for backwards compatibility). Ensures that new artifacts are compatible with previously added artifact versions or clients. The possible configuration values for this rule are as follows:

* `FULL`: The new artifact is forward and backward compatible with the most recently added artifact.
* `FULL_TRANSITIVE`: The new artifact is forward and backward compatible with all previously added artifacts.
* `BACKWARD`: Clients using the new artifact can read data written using the most recently added artifact.
* `BACKWARD_TRANSITIVE`: Clients using the new artifact can read data written using all previously added artifacts.
* `FORWARD`: Clients using the most recently added artifact can read data written using the new artifact.
* `FORWARD_TRANSITIVE`: Clients using all previously added artifacts can read data written using the new artifact.
* `NONE`: All backward and forward compatibility checks are disabled.

|`INTEGRITY`
a| Enforce artifact reference integrity when creating or updating artifacts. Enable and configure this rule to ensure that any artifact references provided are correct. The possible configuration values for this rule are as follows:

* `FULL`: All artifact reference integrity checks are enabled.
* `NO_DUPLICATES`: Detect if there are any duplicate artifact references.
* `REFS_EXIST`: Detect if there are any references to non-existent artifacts.
* `ALL_REFS_MAPPED`: Ensure that all artifact references are mapped.
* `NONE`: All artifact reference integrity checks are disabled.
|===
