// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: root.proto

package io.apicurio.registry.noprofile.ccompat.rest.v7;

public final class Root {
  private Root() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReferrerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReferrerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string root_id = 1;</code>
     * @return The rootId.
     */
    String getRootId();
    /**
     * <code>string root_id = 1;</code>
     * @return The bytes for rootId.
     */
    com.google.protobuf.ByteString
        getRootIdBytes();

    /**
     * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
     * @return Whether the ref field is set.
     */
    boolean hasRef();
    /**
     * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
     * @return The ref.
     */
    Ref.ReferencedMessage getRef();
    /**
     * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
     */
    Ref.ReferencedMessageOrBuilder getRefOrBuilder();
  }
  /**
   * Protobuf type {@code ReferrerMessage}
   */
  public static final class ReferrerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReferrerMessage)
      ReferrerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReferrerMessage.newBuilder() to construct.
    private ReferrerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReferrerMessage() {
      rootId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReferrerMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Root.internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Root.internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Root.ReferrerMessage.class, Root.ReferrerMessage.Builder.class);
    }

    public static final int ROOT_ID_FIELD_NUMBER = 1;
    private volatile Object rootId_;
    /**
     * <code>string root_id = 1;</code>
     * @return The rootId.
     */
    @Override
    public String getRootId() {
      Object ref = rootId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rootId_ = s;
        return s;
      }
    }
    /**
     * <code>string root_id = 1;</code>
     * @return The bytes for rootId.
     */
    @Override
    public com.google.protobuf.ByteString
        getRootIdBytes() {
      Object ref = rootId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rootId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REF_FIELD_NUMBER = 2;
    private Ref.ReferencedMessage ref_;
    /**
     * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
     * @return Whether the ref field is set.
     */
    @Override
    public boolean hasRef() {
      return ref_ != null;
    }
    /**
     * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
     * @return The ref.
     */
    @Override
    public Ref.ReferencedMessage getRef() {
      return ref_ == null ? Ref.ReferencedMessage.getDefaultInstance() : ref_;
    }
    /**
     * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
     */
    @Override
    public Ref.ReferencedMessageOrBuilder getRefOrBuilder() {
      return getRef();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rootId_);
      }
      if (ref_ != null) {
        output.writeMessage(2, getRef());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rootId_);
      }
      if (ref_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRef());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Root.ReferrerMessage)) {
        return super.equals(obj);
      }
      Root.ReferrerMessage other = (Root.ReferrerMessage) obj;

      if (!getRootId()
          .equals(other.getRootId())) return false;
      if (hasRef() != other.hasRef()) return false;
      if (hasRef()) {
        if (!getRef()
            .equals(other.getRef())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRootId().hashCode();
      if (hasRef()) {
        hash = (37 * hash) + REF_FIELD_NUMBER;
        hash = (53 * hash) + getRef().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Root.ReferrerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Root.ReferrerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Root.ReferrerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Root.ReferrerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Root.ReferrerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Root.ReferrerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Root.ReferrerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Root.ReferrerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Root.ReferrerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Root.ReferrerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Root.ReferrerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Root.ReferrerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Root.ReferrerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReferrerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReferrerMessage)
        Root.ReferrerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Root.internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Root.internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Root.ReferrerMessage.class, Root.ReferrerMessage.Builder.class);
      }

      // Construct using Root.ReferrerMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        rootId_ = "";

        if (refBuilder_ == null) {
          ref_ = null;
        } else {
          ref_ = null;
          refBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Root.internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_descriptor;
      }

      @Override
      public Root.ReferrerMessage getDefaultInstanceForType() {
        return Root.ReferrerMessage.getDefaultInstance();
      }

      @Override
      public Root.ReferrerMessage build() {
        Root.ReferrerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Root.ReferrerMessage buildPartial() {
        Root.ReferrerMessage result = new Root.ReferrerMessage(this);
        result.rootId_ = rootId_;
        if (refBuilder_ == null) {
          result.ref_ = ref_;
        } else {
          result.ref_ = refBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Root.ReferrerMessage) {
          return mergeFrom((Root.ReferrerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Root.ReferrerMessage other) {
        if (other == Root.ReferrerMessage.getDefaultInstance()) return this;
        if (!other.getRootId().isEmpty()) {
          rootId_ = other.rootId_;
          onChanged();
        }
        if (other.hasRef()) {
          mergeRef(other.getRef());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                rootId_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getRefFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private Object rootId_ = "";
      /**
       * <code>string root_id = 1;</code>
       * @return The rootId.
       */
      public String getRootId() {
        Object ref = rootId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rootId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string root_id = 1;</code>
       * @return The bytes for rootId.
       */
      public com.google.protobuf.ByteString
          getRootIdBytes() {
        Object ref = rootId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rootId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string root_id = 1;</code>
       * @param value The rootId to set.
       * @return This builder for chaining.
       */
      public Builder setRootId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rootId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string root_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRootId() {
        
        rootId_ = getDefaultInstance().getRootId();
        onChanged();
        return this;
      }
      /**
       * <code>string root_id = 1;</code>
       * @param value The bytes for rootId to set.
       * @return This builder for chaining.
       */
      public Builder setRootIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rootId_ = value;
        onChanged();
        return this;
      }

      private Ref.ReferencedMessage ref_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Ref.ReferencedMessage, Ref.ReferencedMessage.Builder, Ref.ReferencedMessageOrBuilder> refBuilder_;
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       * @return Whether the ref field is set.
       */
      public boolean hasRef() {
        return refBuilder_ != null || ref_ != null;
      }
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       * @return The ref.
       */
      public Ref.ReferencedMessage getRef() {
        if (refBuilder_ == null) {
          return ref_ == null ? Ref.ReferencedMessage.getDefaultInstance() : ref_;
        } else {
          return refBuilder_.getMessage();
        }
      }
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       */
      public Builder setRef(Ref.ReferencedMessage value) {
        if (refBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ref_ = value;
          onChanged();
        } else {
          refBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       */
      public Builder setRef(
          Ref.ReferencedMessage.Builder builderForValue) {
        if (refBuilder_ == null) {
          ref_ = builderForValue.build();
          onChanged();
        } else {
          refBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       */
      public Builder mergeRef(Ref.ReferencedMessage value) {
        if (refBuilder_ == null) {
          if (ref_ != null) {
            ref_ =
              Ref.ReferencedMessage.newBuilder(ref_).mergeFrom(value).buildPartial();
          } else {
            ref_ = value;
          }
          onChanged();
        } else {
          refBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       */
      public Builder clearRef() {
        if (refBuilder_ == null) {
          ref_ = null;
          onChanged();
        } else {
          ref_ = null;
          refBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       */
      public Ref.ReferencedMessage.Builder getRefBuilder() {
        
        onChanged();
        return getRefFieldBuilder().getBuilder();
      }
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       */
      public Ref.ReferencedMessageOrBuilder getRefOrBuilder() {
        if (refBuilder_ != null) {
          return refBuilder_.getMessageOrBuilder();
        } else {
          return ref_ == null ?
              Ref.ReferencedMessage.getDefaultInstance() : ref_;
        }
      }
      /**
       * <code>.ReferencedMessage ref = 2 [(.confluent.field_meta) = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Ref.ReferencedMessage, Ref.ReferencedMessage.Builder, Ref.ReferencedMessageOrBuilder> 
          getRefFieldBuilder() {
        if (refBuilder_ == null) {
          refBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Ref.ReferencedMessage, Ref.ReferencedMessage.Builder, Ref.ReferencedMessageOrBuilder>(
                  getRef(),
                  getParentForChildren(),
                  isClean());
          ref_ = null;
        }
        return refBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReferrerMessage)
    }

    // @@protoc_insertion_point(class_scope:ReferrerMessage)
    private static final Root.ReferrerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Root.ReferrerMessage();
    }

    public static Root.ReferrerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReferrerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ReferrerMessage>() {
      @Override
      public ReferrerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReferrerMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReferrerMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public Root.ReferrerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nroot.proto\022,io.confluent.kafka.seriali" +
      "zers.protobuf.test\032\tref.proto\032\024confluent" +
      "/meta.proto\"\236\001\n\017ReferrerMessage\022\017\n\007root_" +
      "id\030\001 \001(\t\022d\n\003ref\030\002 \001(\0132?.io.confluent.kaf" +
      "ka.serializers.protobuf.test.ReferencedM" +
      "essageB\026\202D\023\n\021ReferencedMessage:\024\202D\021\n\017Ref" +
      "errerMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Ref.getDescriptor(),
          io.confluent.protobuf.MetaProto.getDescriptor(),
        });
    internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_kafka_serializers_protobuf_test_ReferrerMessage_descriptor,
        new String[] { "RootId", "Ref", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.confluent.protobuf.MetaProto.fieldMeta);
    registry.add(io.confluent.protobuf.MetaProto.messageMeta);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    Ref.getDescriptor();
    io.confluent.protobuf.MetaProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
