// Metadata created by nebel
//

[id="intro-to-the-registry"]
= Introduction to {registry}
//If the assembly covers a task, start the title with a verb in the gerund form, such as Creating or Configuring.

This chapter introduces {registry} concepts and features and provides details on the supported artifact types that are stored in the registry:

* xref:registry-overview[]
* xref:registry-artifact-types[]



ifdef::rh-service-registry[]
[IMPORTANT]
====
{registry} is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. 

These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information about the support scope of Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview.
====
endif::[]

//INCLUDES
include::../../modules/getting-started/con_registry-overview.adoc[leveloffset=+1]
include::../../modules/getting-started/ref_registry-artifact-types.adoc[leveloffset=+1]
