// Metadata created by nebel
//

[id="intro-to-registry-rules"]
= Introduction to {registry} rules
//If the assembly covers a task, start the title with a verb in the gerund form, such as Creating or Configuring.

This chapter introduces the optional rules used to govern registry content and provides details on the available rule types:

* xref:registry-rules[]
* xref:registry-rule-types[]

ifdef::rh-service-registry[]
[IMPORTANT]
====
{registry} is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. 

These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information about the support scope of Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview.
====
endif::[]

//INCLUDES
include::../../modules/getting-started/con_registry-rules.adoc[leveloffset=+1]
include::../../modules/getting-started/ref_registry-rule-types.adoc[leveloffset=+1]
