= Explanation of the `doc` directory structure

The Apicurio Registry `docs` directory is organized for delivering flexible content, which is a framework for putting together exactly the content you need and making it easier to reuse the same content in multiple places. 

Apicurio Registry user doc is organized into the following documents. The following table lists the `apicurio-registry/docs` directories that contain the content for each document.  

[options="header"]
[cols="1,2,3"]
|===
|Document
|`master.adoc` location
|Content location

|_Getting Started with Apicurio Registry_
|`getting-started`
|`assemblies/getting-started`  
`modules/getting-started`  
`images/getting-started`

|===


For each document, the `master.adoc` file includes the relevant assemblies and modules. 

* Assemblies are files that introduce a subject and 
include two or more modules, which provide the content.
* Modules provide content and do not include other files. 
There are three kinds of modules: 
** Concept
** Procedure
** Reference

The Apicurio Registry `docs` directory contains these directories: 

* `assemblies` contains a folder for each category of information. 
These folders contain assembly files:  
** `getting-started` 


* `modules` also contains a folder for each category of information. 
These folders contains concept, procedure, and reference modules, which contain the details:
** `getting-started`


* `images` also contains a folder for each category of information.
These folders contain image files: 
** `getting-started`
