gatling {
  ssl {
    useInsecureTrustManager = false
    trustStore {
      type = "PKCS12"
      file = ${?BENCHMARK_TRUSTSTORE}
      password = ${?BENCHMARK_TRUSTSTORE_PASSWORD}
    }
  }
  http {
    enableHostnameVerification = true
    warmUpUrl = ""
  }
  data.enableAnalytics = false
  charting.indicators {
    percentile1 = 50
    percentile2 = 95
    percentile3 = 99
    percentile4 = 99.9
  }
}
