name: Trivy Image Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  vulnerability-scan:
    name: Container vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: quay.io/apicurio/apicurio-registry:latest-snapshot
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
