name: Trivy Image Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  vulnerability-scan:
    name: Container vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          image-ref: quay.io/apicurio/apicurio-registry:latest-snapshot
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: 'os,library'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@02c5e83432fe5497fd85b873b6c9f16a8578e1d9 # v3
        with:
          sarif_file: 'trivy-results.sarif'
