name: Validate Docs & Playbook
on:
  workflow_call: { }
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'docs-playbook/**'

permissions:
  contents: read

jobs:
  validate:
    name: Validate Docs
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Generate Documentation
        run: |
          cd docs-playbook
          ./_build-all.sh
