name: Validate OpenAPI schema with Spectral
on:
  workflow_call: { }
  pull_request:
    branches: [ main ]
    paths:
      - common/src/main/resources/META-INF/openapi.json

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.18.0
      - name: Install RHOAS Guidelines linter
        run: |
          npm i @rhoas/spectral-ruleset
          echo 'extends: "@rhoas/spectral-ruleset"' > .spectral.yaml
      - name: Validate OpenAPI schema with Spectral and RHOAS Guidelines
        run: npx rhoasapi lint common/src/main/resources/META-INF/openapi.json
      - name: Cleanup
        run: |
          rm .spectral.yaml
