name: Validate Docs & Playbook
on:
  workflow_call: { }
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'docs-playbook/**'

permissions:
  contents: read

jobs:
  validate:
    name: Validate Docs
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Generate Documentation
        run: |
          cd docs-playbook
          ./_build-all.sh
