name: SDK Verification

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'
      image-tag:
        type: string
        required: true
        description: 'Docker image tag to test'

permissions:
  contents: read

jobs:
  verify-python-sdk:
    name: Verify Python SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@d45b6d76012debf457ab49dffc7fb7b2efe8071d

      - name: Install the package
        working-directory: python-sdk
        run: make install

      - name: Check linting
        working-directory: python-sdk
        run: make lint-check

      - uses: apicurio/apicurio-github-actions/load-docker-image@1da7e1fef5962e611805b46e181e623efba5a5f9 # v2
        with:
          artifact-name: 'apicurio-registry-${{ inputs.image-tag }}.tar'
          image-file: '/tmp/apicurio-registry-${{ inputs.image-tag }}.tar'
          image-name: 'apicurio/apicurio-registry'
          tag: '${{ inputs.image-tag }}'

      - name: Run the tests
        working-directory: python-sdk
        run: |
          docker run -d -p 8080:8080 apicurio/apicurio-registry:${{ inputs.image-tag }}
          sleep 5
          make test

  verify-go-sdk:
    name: Verify Go SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Go - Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26.4'

      - uses: apicurio/apicurio-github-actions/load-docker-image@1da7e1fef5962e611805b46e181e623efba5a5f9 # v2
        with:
          artifact-name: 'apicurio-registry-${{ inputs.image-tag }}.tar'
          image-file: '/tmp/apicurio-registry-${{ inputs.image-tag }}.tar'
          image-name: 'apicurio/apicurio-registry'
          tag: '${{ inputs.image-tag }}'

      - name: Run the tests
        working-directory: go-sdk
        run: |
          docker run -d -p 8080:8080 apicurio/apicurio-registry:${{ inputs.image-tag }}
          sleep 5
          make test
