name: SDK Verification

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'
      image-tag:
        type: string
        required: true
        description: 'Docker image tag to test'

permissions:
  contents: read

jobs:
  verify-python-sdk:
    name: Verify Python SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.14.6'

      - name: Install Poetry
        uses: snok/install-poetry@d45b6d76012debf457ab49dffc7fb7b2efe8071d

      - name: Install the package
        working-directory: python-sdk
        run: make install

      - name: Check linting
        working-directory: python-sdk
        run: make lint-check

      - uses: apicurio/apicurio-github-actions/load-docker-image@97d452c41f1abd7142c0ce2ac37e87922e35e71d # v2
        with:
          artifact-name: 'apicurio-registry-${{ inputs.image-tag }}.tar'
          image-file: '/tmp/apicurio-registry-${{ inputs.image-tag }}.tar'
          image-name: 'apicurio/apicurio-registry'
          tag: '${{ inputs.image-tag }}'

      - name: Run the tests
        working-directory: python-sdk
        run: |
          docker run -d -p 8080:8080 apicurio/apicurio-registry:${{ inputs.image-tag }}
          sleep 5
          make test

  verify-go-sdk:
    name: Verify Go SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Go - Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: '1.26.5'

      - uses: apicurio/apicurio-github-actions/load-docker-image@97d452c41f1abd7142c0ce2ac37e87922e35e71d # v2
        with:
          artifact-name: 'apicurio-registry-${{ inputs.image-tag }}.tar'
          image-file: '/tmp/apicurio-registry-${{ inputs.image-tag }}.tar'
          image-name: 'apicurio/apicurio-registry'
          tag: '${{ inputs.image-tag }}'

      - name: Run the tests
        working-directory: go-sdk
        run: |
          docker run -d -p 8080:8080 apicurio/apicurio-registry:${{ inputs.image-tag }}
          sleep 5
          make test
